-- GENERATED by tools/gen_captain.py -- do not edit by hand.
--
-- Captain Titus's conversation (CAPTAIN.md 5). Every string here is a
-- translation key into Translate/EN/Print_Text.json, written by the same
-- program, so the two cannot disagree. The server walks this for each
-- player who talks to her; the panel draws the lines it names.

TREK_CaptainTree = {}
local T = TREK_CaptainTree

T.voices = {
    captain = { name = "Print_Text_TREK_CAPT_Voice_captain", r = 0.96, g = 0.80, b = 0.42 },
    note = { name = "Print_Text_TREK_CAPT_Voice_note", r = 0.62, g = 0.62, b = 0.68 },
    you = { name = "Print_Text_TREK_CAPT_Voice_you", r = 0.80, g = 0.80, b = 0.80 },
}

T.dynamic = { "^truth$", "^promotionDue$", "^ranked$", "^uniform$", "^shipDark$", "^distressLive$", "^probed$", "^myRescues>=\\d+$" }

T.hub = { entry = { { go = { "HUB_FIRST" }, forbids = { "me:introduced" } }, { go = { "HUB_COMMISSION" }, requires = { "promotionDue" }, forbids = { "ranked" } }, { go = { "HUB_PROMOTE" }, requires = { "promotionDue" } }, { go = { "HUB_TOLD" }, requires = { "revealDone" }, forbids = { "me:toldReveal" } }, { go = { "HUB_AGAIN1", "HUB_AGAIN2", "HUB_AGAIN3", "HUB_AGAIN4" } } },
          home = { { go = { "HUB_COMMISSION" }, requires = { "promotionDue" }, forbids = { "ranked" } }, { go = { "HUB_PROMOTE" }, requires = { "promotionDue" } }, { go = { "HUB_HOME1", "HUB_HOME2", "HUB_HOME3" } } },
          bye = { { go = { "HUB_BYE1", "HUB_BYE2", "HUB_BYE3", "HUB_BYE4" } } } }

-- The topics, in the order the hub lists them.
T.order = { "WHO", "POST", "FEB", "COUNTY", "ELEVEN", "SHEPARD", "WHODID", "WORLD", "CURE", "ORDERS", "YOU" }

T.topics = {
    WHO = { title = "Print_Text_TREK_CAPT_WHO_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} } },
        entry = { { go = { "WHO_01" } } } },
    POST = { title = "Print_Text_TREK_CAPT_POST_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} } },
        entry = { { go = { "POST_01" } } } },
    FEB = { title = "Print_Text_TREK_CAPT_FEB_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} } },
        entry = { { go = { "FEB_01" } } } },
    COUNTY = { title = "Print_Text_TREK_CAPT_COUNTY_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} }, { id = "2", requires = { "scienceDone" }, forbids = {} } },
        entry = { { go = { "COUNTY_01" } } } },
    ELEVEN = { title = "Print_Text_TREK_CAPT_ELEVEN_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} }, { id = "2", requires = { "rescued>=1" }, forbids = {} }, { id = "3", requires = { "elevenDone" }, forbids = {} } },
        entry = { { go = { "ELEVEN_01" } } } },
    SHEPARD = { title = "Print_Text_TREK_CAPT_SHEPARD_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = { "met" } }, { id = "2", requires = { "met" }, forbids = {} }, { id = "3", requires = { "stayed" }, forbids = {} } },
        entry = { { go = { "SHEPARD_10" }, requires = { "met" } }, { go = { "SHEPARD_01" } } } },
    WHODID = { title = "Print_Text_TREK_CAPT_WHODID_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} }, { id = "2", requires = { "denialDone" }, forbids = {} }, { id = "T", requires = { "truth" }, forbids = {} } },
        entry = { { go = { "WHODID_01" } } } },
    WORLD = { title = "Print_Text_TREK_CAPT_WORLD_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} }, { id = "2", requires = { "clueTold" }, forbids = {} }, { id = "3", requires = { "goldDone" }, forbids = {} } },
        entry = { { go = { "WORLD_01" } } } },
    CURE = { title = "Print_Text_TREK_CAPT_CURE_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} }, { id = "2", requires = { "archiveDone" }, forbids = {} } },
        entry = { { go = { "CURE_01" } } } },
    ORDERS = { title = "Print_Text_TREK_CAPT_ORDERS_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} } },
        entry = { { go = { "ORDERS_DARK" }, requires = { "shipDark" } }, { go = { "ORDERS_TAPES" }, forbids = { "me:toldTapes", "watched:TREK_LogOne" } }, { go = { "ORDERS_FRAG" }, requires = { "carrying" } }, { go = { "ORDERS_BEACON" }, requires = { "distressLive" } }, { go = { "ORDERS_PROBE" }, forbids = { "probed" } }, { go = { "ORDERS_STATION" }, forbids = { "me:toldStation" } }, { go = { "ORDERS_REST1", "ORDERS_REST2", "ORDERS_REST3" } } } },
    YOU = { title = "Print_Text_TREK_CAPT_YOU_Title", requires = {}, forbids = {},
        tiers = { { id = "1", requires = {}, forbids = {} } },
        entry = { { go = { "YOU_01" }, requires = { "uniform" } }, { go = { "YOU_02" } } } },
}

T.nodes = {
    ["HUB_FIRST"] = { topic = "HUB", lines = { { v = "note", k = "Print_Text_TREK_CAPT_HUB_FIRST_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_FIRST_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_FIRST_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_FIRST_L4" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_FIRST_L5" } }, options = {
        { k = "Print_Text_TREK_CAPT_HUB_FIRST_O1", go = "HUB_NAMED", mark = { "named" } },
        { k = "Print_Text_TREK_CAPT_HUB_FIRST_O2", go = "HUB_UNNAMED" },
        { k = "Print_Text_TREK_CAPT_HUB_FIRST_O3", go = "HUB_UNNAMED" },
    }, mark = { "introduced" } },
    ["HUB_NAMED"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_NAMED_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_NAMED_L2" } } },
    ["HUB_UNNAMED"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_UNNAMED_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_UNNAMED_L2" } } },
    ["HUB_COMMISSION"] = { topic = "HUB", lines = { { v = "note", k = "Print_Text_TREK_CAPT_HUB_COMMISSION_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_COMMISSION_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_COMMISSION_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_COMMISSION_L4" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_COMMISSION_L5" } }, options = {
        { k = "Print_Text_TREK_CAPT_HUB_COMMISSION_O1", go = "HUB" },
        { k = "Print_Text_TREK_CAPT_HUB_COMMISSION_O2", go = "HUB_COMMISSIONX" },
        { k = "Print_Text_TREK_CAPT_HUB_COMMISSION_O3", go = "HUB_PROMOTEQ" },
    }, promote = true },
    ["HUB_COMMISSIONX"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_COMMISSIONX_L1" } } },
    ["HUB_PROMOTE"] = { topic = "HUB", lines = { { v = "note", k = "Print_Text_TREK_CAPT_HUB_PROMOTE_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_PROMOTE_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_PROMOTE_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_PROMOTE_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_HUB_PROMOTE_O1", go = "HUB" },
        { k = "Print_Text_TREK_CAPT_HUB_PROMOTE_O2", go = "HUB_PROMOTEQ" },
    }, promote = true },
    ["HUB_PROMOTEQ"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_PROMOTEQ_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_PROMOTEQ_L2" } } },
    ["HUB_TOLD"] = { topic = "HUB", lines = { { v = "note", k = "Print_Text_TREK_CAPT_HUB_TOLD_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_TOLD_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_TOLD_L3" } }, mark = { "toldReveal" } },
    ["HUB_AGAIN1"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_AGAIN1_L1" } } },
    ["HUB_AGAIN2"] = { topic = "HUB", lines = { { v = "note", k = "Print_Text_TREK_CAPT_HUB_AGAIN2_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_AGAIN2_L2" } } },
    ["HUB_AGAIN3"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_AGAIN3_L1" } } },
    ["HUB_AGAIN4"] = { topic = "HUB", lines = { { v = "note", k = "Print_Text_TREK_CAPT_HUB_AGAIN4_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_AGAIN4_L2" } } },
    ["HUB_HOME1"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_HOME1_L1" } } },
    ["HUB_HOME2"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_HOME2_L1" } } },
    ["HUB_HOME3"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_HOME3_L1" } } },
    ["HUB_BYE1"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_BYE1_L1" } } },
    ["HUB_BYE2"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_BYE2_L1" } } },
    ["HUB_BYE3"] = { topic = "HUB", lines = { { v = "note", k = "Print_Text_TREK_CAPT_HUB_BYE3_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_HUB_BYE3_L2" } } },
    ["HUB_BYE4"] = { topic = "HUB", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_HUB_BYE4_L1" } } },
    ["WHO_01"] = { topic = "WHO", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHO_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_01_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_01_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHO_01_O1", go = "WHO_02" },
        { k = "Print_Text_TREK_CAPT_WHO_01_O2", go = "WHO_03" },
    } },
    ["WHO_02"] = { topic = "WHO", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHO_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_02_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_02_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_02_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHO_02_O1", go = "WHO_03" },
    } },
    ["WHO_03"] = { topic = "WHO", tier = "1", lines = { { v = "note", k = "Print_Text_TREK_CAPT_WHO_03_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_03_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_03_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHO_03_L4" } } },
    ["POST_01"] = { topic = "POST", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_POST_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_01_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_01_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_POST_01_O1", go = "POST_02" },
        { k = "Print_Text_TREK_CAPT_POST_01_O2", go = "POST_03" },
    } },
    ["POST_02"] = { topic = "POST", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_POST_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_02_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_02_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_02_L4" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_02_L5" } }, options = {
        { k = "Print_Text_TREK_CAPT_POST_02_O1", go = "POST_04" },
    } },
    ["POST_03"] = { topic = "POST", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_POST_03_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_03_L2" } }, options = {
        { k = "Print_Text_TREK_CAPT_POST_03_O1", go = "POST_04" },
    } },
    ["POST_04"] = { topic = "POST", tier = "1", lines = { { v = "note", k = "Print_Text_TREK_CAPT_POST_04_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_04_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_POST_04_L3" } } },
    ["FEB_01"] = { topic = "FEB", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_FEB_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_01_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_01_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_FEB_01_O1", go = "FEB_02" },
        { k = "Print_Text_TREK_CAPT_FEB_01_O2", go = "FEB_03" },
        { k = "Print_Text_TREK_CAPT_FEB_01_O3", go = "FEB_04" },
    } },
    ["FEB_02"] = { topic = "FEB", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_FEB_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_02_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_02_L3" } }, options = {
        { k = "Print_Text_TREK_CAPT_FEB_02_O1", go = "FEB_03" },
        { k = "Print_Text_TREK_CAPT_FEB_02_O2", go = "FEB_04" },
    } },
    ["FEB_03"] = { topic = "FEB", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_FEB_03_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_03_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_03_L3" } }, options = {
        { k = "Print_Text_TREK_CAPT_FEB_03_O1", go = "FEB_02" },
        { k = "Print_Text_TREK_CAPT_FEB_03_O2", go = "FEB_04" },
    } },
    ["FEB_04"] = { topic = "FEB", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_FEB_04_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_04_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_FEB_04_L3" } } },
    ["COUNTY_01"] = { topic = "COUNTY", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_01_L2" }, { v = "note", k = "Print_Text_TREK_CAPT_COUNTY_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_01_L4" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_01_L5" } }, options = {
        { k = "Print_Text_TREK_CAPT_COUNTY_01_O1", go = "COUNTY_02" },
        { k = "Print_Text_TREK_CAPT_COUNTY_01_O2", go = "COUNTY_20" },
        { k = "Print_Text_TREK_CAPT_COUNTY_01_O3", go = "COUNTY_03", forbids = { "scienceDone" } },
    } },
    ["COUNTY_02"] = { topic = "COUNTY", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_02_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_02_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_02_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_COUNTY_02_O1", go = "COUNTY_20" },
    } },
    ["COUNTY_03"] = { topic = "COUNTY", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_03_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_03_L2" } } },
    ["COUNTY_20"] = { topic = "COUNTY", tier = "2", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_20_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_20_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_20_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_COUNTY_20_L4" } } },
    ["ELEVEN_01"] = { topic = "ELEVEN", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_01_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_01_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_ELEVEN_01_O1", go = "ELEVEN_02" },
        { k = "Print_Text_TREK_CAPT_ELEVEN_01_O2", go = "ELEVEN_20" },
        { k = "Print_Text_TREK_CAPT_ELEVEN_01_O3", go = "ELEVEN_30" },
        { k = "Print_Text_TREK_CAPT_ELEVEN_01_O4", go = "ELEVEN_03" },
    } },
    ["ELEVEN_02"] = { topic = "ELEVEN", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_02_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_02_L3" } }, options = {
        { k = "Print_Text_TREK_CAPT_ELEVEN_02_O1", go = "ELEVEN_20" },
        { k = "Print_Text_TREK_CAPT_ELEVEN_02_O2", go = "ELEVEN_03" },
    } },
    ["ELEVEN_03"] = { topic = "ELEVEN", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_03_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_03_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_03_L3" } } },
    ["ELEVEN_20"] = { topic = "ELEVEN", tier = "2", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_20_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_20_L2" }, { v = "note", k = "Print_Text_TREK_CAPT_ELEVEN_20_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_20_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_ELEVEN_20_O1", go = "ELEVEN_30" },
    } },
    ["ELEVEN_30"] = { topic = "ELEVEN", tier = "3", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_30_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_30_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_ELEVEN_30_L3" } } },
    ["SHEPARD_01"] = { topic = "SHEPARD", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_01_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_01_L4" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_01_L5" } }, options = {
        { k = "Print_Text_TREK_CAPT_SHEPARD_01_O1", go = "SHEPARD_02" },
    } },
    ["SHEPARD_02"] = { topic = "SHEPARD", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_02_L2" } } },
    ["SHEPARD_10"] = { topic = "SHEPARD", tier = "2", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_10_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_10_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_10_L3" } }, options = {
        { k = "Print_Text_TREK_CAPT_SHEPARD_10_O1", go = "SHEPARD_20" },
        { k = "Print_Text_TREK_CAPT_SHEPARD_10_O2", go = "SHEPARD_12" },
    } },
    ["SHEPARD_12"] = { topic = "SHEPARD", tier = "2", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_12_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_12_L2" } } },
    ["SHEPARD_20"] = { topic = "SHEPARD", tier = "3", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_20_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_20_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_20_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_SHEPARD_20_L4" } } },
    ["WHODID_01"] = { topic = "WHODID", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_01_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_01_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHODID_01_O1", go = "WHODID_T1" },
        { k = "Print_Text_TREK_CAPT_WHODID_01_O2", go = "WHODID_05", forbids = { "truth" } },
        { k = "Print_Text_TREK_CAPT_WHODID_01_O3", go = "WHODID_02" },
        { k = "Print_Text_TREK_CAPT_WHODID_01_O4", go = "WHODID_03" },
    } },
    ["WHODID_02"] = { topic = "WHODID", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_02_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_02_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_02_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHODID_02_O1", go = "WHODID_03" },
    } },
    ["WHODID_03"] = { topic = "WHODID", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_03_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_03_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_03_L3" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHODID_03_O1", go = "WHODID_20" },
    } },
    ["WHODID_05"] = { topic = "WHODID", tier = "1", lines = { { v = "note", k = "Print_Text_TREK_CAPT_WHODID_05_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_05_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_05_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_05_L4" } } },
    ["WHODID_20"] = { topic = "WHODID", tier = "2", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_20_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_20_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_20_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_20_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHODID_20_O1", go = "WHODID_21", requires = { "pressed" } },
        { k = "Print_Text_TREK_CAPT_WHODID_20_O2", go = "WHODID_T1" },
        { k = "Print_Text_TREK_CAPT_WHODID_20_O3", go = "WHODID_05", forbids = { "truth" } },
    } },
    ["WHODID_21"] = { topic = "WHODID", tier = "2", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_21_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_21_L2" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHODID_21_O1", go = "WHODID_T1" },
        { k = "Print_Text_TREK_CAPT_WHODID_21_O2", go = "WHODID_05", forbids = { "truth" } },
    } },
    ["WHODID_T1"] = { topic = "WHODID", tier = "T", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T1_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T1_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T1_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T1_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHODID_T1_O1", go = "WHODID_T2" },
        { k = "Print_Text_TREK_CAPT_WHODID_T1_O2", go = "WHODID_T3" },
    } },
    ["WHODID_T2"] = { topic = "WHODID", tier = "T", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T2_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T2_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T2_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T2_L4" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T2_L5" } }, options = {
        { k = "Print_Text_TREK_CAPT_WHODID_T2_O1", go = "WHODID_T3" },
    } },
    ["WHODID_T3"] = { topic = "WHODID", tier = "T", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T3_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T3_L2" }, { v = "note", k = "Print_Text_TREK_CAPT_WHODID_T3_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T3_L4" }, { v = "captain", k = "Print_Text_TREK_CAPT_WHODID_T3_L5" } } },
    ["WORLD_01"] = { topic = "WORLD", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_01_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_01_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_WORLD_01_O1", go = "WORLD_02" },
        { k = "Print_Text_TREK_CAPT_WORLD_01_O2", go = "WORLD_03" },
        { k = "Print_Text_TREK_CAPT_WORLD_01_O3", go = "WORLD_04" },
        { k = "Print_Text_TREK_CAPT_WORLD_01_O4", go = "WORLD_20" },
        { k = "Print_Text_TREK_CAPT_WORLD_01_O5", go = "WORLD_30" },
    } },
    ["WORLD_02"] = { topic = "WORLD", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_02_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_02_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_02_L4" } } },
    ["WORLD_03"] = { topic = "WORLD", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_03_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_03_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_03_L3" } } },
    ["WORLD_04"] = { topic = "WORLD", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_04_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_04_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_04_L3" } } },
    ["WORLD_20"] = { topic = "WORLD", tier = "2", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_20_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_20_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_20_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_20_L4" } } },
    ["WORLD_30"] = { topic = "WORLD", tier = "3", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_30_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_30_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_30_L3" }, { v = "note", k = "Print_Text_TREK_CAPT_WORLD_30_L4" }, { v = "captain", k = "Print_Text_TREK_CAPT_WORLD_30_L5" } } },
    ["CURE_01"] = { topic = "CURE", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_CURE_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_CURE_01_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_CURE_01_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_CURE_01_L4" } }, options = {
        { k = "Print_Text_TREK_CAPT_CURE_01_O1", go = "CURE_20" },
        { k = "Print_Text_TREK_CAPT_CURE_01_O2", go = "CURE_02", forbids = { "archiveDone" } },
    } },
    ["CURE_02"] = { topic = "CURE", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_CURE_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_CURE_02_L2" } } },
    ["CURE_20"] = { topic = "CURE", tier = "2", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_CURE_20_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_CURE_20_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_CURE_20_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_CURE_20_L4" } } },
    ["ORDERS_DARK"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_DARK_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_DARK_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_DARK_L3" } } },
    ["ORDERS_TAPES"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_TAPES_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_TAPES_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_TAPES_L3" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_TAPES_L4" } }, mark = { "toldTapes" } },
    ["ORDERS_FRAG"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_FRAG_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_FRAG_L2" } } },
    ["ORDERS_BEACON"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_BEACON_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_BEACON_L2" } } },
    ["ORDERS_PROBE"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_PROBE_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_PROBE_L2" } } },
    ["ORDERS_STATION"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_STATION_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_STATION_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_STATION_L3" } }, mark = { "toldStation" } },
    ["ORDERS_REST1"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_REST1_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_REST1_L2" } } },
    ["ORDERS_REST2"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_REST2_L1" } } },
    ["ORDERS_REST3"] = { topic = "ORDERS", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_REST3_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_ORDERS_REST3_L2" } } },
    ["YOU_01"] = { topic = "YOU", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_YOU_01_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_YOU_01_L2" } }, options = {
        { k = "Print_Text_TREK_CAPT_YOU_01_O1", go = "YOU_03" },
    } },
    ["YOU_02"] = { topic = "YOU", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_YOU_02_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_YOU_02_L2" }, { v = "captain", k = "Print_Text_TREK_CAPT_YOU_02_L3" } }, options = {
        { k = "Print_Text_TREK_CAPT_YOU_02_O1", go = "YOU_03" },
    } },
    ["YOU_03"] = { topic = "YOU", tier = "1", lines = { { v = "captain", k = "Print_Text_TREK_CAPT_YOU_03_L1" }, { v = "captain", k = "Print_Text_TREK_CAPT_YOU_03_L2" } } },
}

return T
