-- GENERATED by tools/gen_comms.py -- do not edit by hand.
--
-- The Adirondack channel's dialogue tree (COMMS.md 3). Every string
-- here is a translation key into Translate/EN/Print_Text.json, and
-- both files come out of the generator together. The server walks
-- this; the PADD renders history from it, so a line fixed here is
-- fixed in every player's transcript (PADD.md 12.2).

TREK_CommsTree = {}
local T = TREK_CommsTree

T.voices = {
    card = { name = "Print_Text_TREK_COMM_Voice_card", r = 1.00, g = 1.00, b = 1.00 },
    shepard = { name = "Print_Text_TREK_COMM_Voice_shepard", r = 1.00, g = 0.75, b = 0.00 },
    emh = { name = "Print_Text_TREK_COMM_Voice_emh", r = 0.00, g = 0.69, b = 0.31 },
    officer = { name = "Print_Text_TREK_COMM_Voice_officer", r = 0.62, g = 0.45, b = 0.85 },
    crew = { name = "Print_Text_TREK_COMM_Voice_crew", r = 0.00, g = 0.69, b = 0.94 },
    you = { name = "Print_Text_TREK_COMM_Voice_you", r = 0.80, g = 0.80, b = 0.80 },
}

-- The order threads are considered in, which is their priority.
T.order = { "FIRST", "THANKS", "LOST", "QUIET", "RESUME" }

T.systemFlags = { "clueSeen", "commissioned", "lostDue", "thanksDue" }

T.threads = {
    FIRST = { title = "Print_Text_TREK_COMM_FIRST_Title", kind = "incoming", entries = { "FIRST_01", "FIRST_01M", "FIRST_01MM" }, requires = {}, forbids = { "quiet" }, retry = true, repeatable = false, day = 7 },
    THANKS = { title = "Print_Text_TREK_COMM_THANKS_Title", kind = "incoming", entries = { "THANKS_01" }, requires = { "thanksDue", "met" }, forbids = { "quiet" }, retry = false, repeatable = true },
    LOST = { title = "Print_Text_TREK_COMM_LOST_Title", kind = "incoming", entries = { "LOST_01" }, requires = { "lostDue", "met" }, forbids = { "quiet" }, retry = false, repeatable = true },
    QUIET = { title = "Print_Text_TREK_COMM_QUIET_Title", kind = "hail", entries = { "QUIET_01" }, requires = { "met" }, forbids = { "quiet" }, retry = true, repeatable = true, cooldown = 24 },
    RESUME = { title = "Print_Text_TREK_COMM_RESUME_Title", kind = "hail", entries = { "RESUME_01" }, requires = { "quiet" }, forbids = {}, retry = true, repeatable = false },
}

T.nodes = {
    ["FIRST_01"] = { thread = "FIRST", lines = { { v = "card", k = "Print_Text_TREK_COMM_FIRST_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_01_O1", go = "FIRST_02" },
        { k = "Print_Text_TREK_COMM_FIRST_01_O2", go = "FIRST_02R" },
        { k = "Print_Text_TREK_COMM_FIRST_01_O3", go = "FIRST_02H" },
    }, timeout = 60, silence = "FIRST_01S" },
    ["FIRST_01M"] = { thread = "FIRST", lines = { { v = "card", k = "Print_Text_TREK_COMM_FIRST_01M_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01M_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01M_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01M_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_01M_O1", go = "FIRST_02" },
        { k = "Print_Text_TREK_COMM_FIRST_01M_O2", go = "FIRST_02R" },
        { k = "Print_Text_TREK_COMM_FIRST_01M_O3", go = "FIRST_02H" },
    }, timeout = 60, silence = "FIRST_01S" },
    ["FIRST_01MM"] = { thread = "FIRST", lines = { { v = "card", k = "Print_Text_TREK_COMM_FIRST_01MM_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01MM_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01MM_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_01MM_O1", go = "FIRST_02" },
        { k = "Print_Text_TREK_COMM_FIRST_01MM_O2", go = "FIRST_02R" },
    }, timeout = 45, silence = "FIRST_01S" },
    ["FIRST_01S"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01S_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01S_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_01S_O1", go = "FIRST_02" },
    } },
    ["FIRST_02R"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02R_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02R_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02R_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_02R_O1", go = "FIRST_02" },
    } },
    ["FIRST_02H"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02H_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02H_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_02H_O1", go = "FIRST_02" },
        { k = "Print_Text_TREK_COMM_FIRST_02H_O2", go = "FIRST_02" },
    } },
    ["FIRST_02"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L4" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_02_O1", go = "FIRST_03" },
        { k = "Print_Text_TREK_COMM_FIRST_02_O2", go = "FIRST_03" },
        { k = "Print_Text_TREK_COMM_FIRST_02_O3", go = "FIRST_03J" },
    } },
    ["FIRST_03J"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_03J_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_03J_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_03J_O1", go = "FIRST_03" },
    } },
    ["FIRST_03"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_03_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_03_O1", go = "FIRST_04N" },
        { k = "Print_Text_TREK_COMM_FIRST_03_O2", go = "FIRST_04S" },
        { k = "Print_Text_TREK_COMM_FIRST_03_O3", go = "FIRST_04X", sets = { "named" } },
        { k = "Print_Text_TREK_COMM_FIRST_03_O4", go = "FIRST_04X" },
    }, timeout = 60, silence = "FIRST_04Q" },
    ["FIRST_04N"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04N_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04N_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04N_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04N_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_04N_O1", go = "FIRST_05" },
        { k = "Print_Text_TREK_COMM_FIRST_04N_O2", go = "FIRST_05" },
        { k = "Print_Text_TREK_COMM_FIRST_04N_O3", go = "FIRST_05" },
    } },
    ["FIRST_04S"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04S_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04S_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04S_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04S_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_04S_O1", go = "FIRST_05" },
        { k = "Print_Text_TREK_COMM_FIRST_04S_O2", go = "FIRST_05" },
    } },
    ["FIRST_04X"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04X_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_04X_O1", go = "FIRST_05" },
    } },
    ["FIRST_04Q"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04Q_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04Q_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_04Q_O1", go = "FIRST_05" },
    } },
    ["FIRST_05"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_05_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_05_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_05_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_05_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_05_O1", go = "FIRST_06" },
        { k = "Print_Text_TREK_COMM_FIRST_05_O2", go = "FIRST_06U" },
        { k = "Print_Text_TREK_COMM_FIRST_05_O3", go = "FIRST_06W" },
    } },
    ["FIRST_06U"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06U_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06U_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06U_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06U_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_06U_O1", go = "FIRST_06" },
        { k = "Print_Text_TREK_COMM_FIRST_06U_O2", go = "FIRST_06" },
    } },
    ["FIRST_06W"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06W_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06W_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_06W_O1", go = "FIRST_06" },
    } },
    ["FIRST_06"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_06_O1", go = "FIRST_07" },
        { k = "Print_Text_TREK_COMM_FIRST_06_O2", go = "FIRST_06Q" },
        { k = "Print_Text_TREK_COMM_FIRST_06_O3", go = "FIRST_07" },
    } },
    ["FIRST_06Q"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06Q_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06Q_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06Q_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_06Q_O1", go = "FIRST_07" },
    } },
    ["FIRST_07"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_07_O1", go = "FIRST_07A", requires = { "watched:TREK_LogSix" } },
        { k = "Print_Text_TREK_COMM_FIRST_07_O2", go = "FIRST_08" },
        { k = "Print_Text_TREK_COMM_FIRST_07_O3", go = "FIRST_08" },
    } },
    ["FIRST_07A"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07A_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07A_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07A_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_07A_O1", go = "FIRST_08" },
        { k = "Print_Text_TREK_COMM_FIRST_07A_O2", go = "FIRST_08" },
    } },
    ["FIRST_08"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_08_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_08_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_08_L3" } }, sets = { "met" }, terminal = true },
    ["THANKS_01"] = { thread = "THANKS", lines = { { v = "card", k = "Print_Text_TREK_COMM_THANKS_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_THANKS_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_THANKS_01_O1", go = "THANKS_02" },
        { k = "Print_Text_TREK_COMM_THANKS_01_O2", go = "THANKS_03" },
    }, clears = { "thanksDue" } },
    ["THANKS_02"] = { thread = "THANKS", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_THANKS_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_THANKS_02_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_THANKS_02_O1", go = "THANKS_03" },
        { k = "Print_Text_TREK_COMM_THANKS_02_O2", go = "THANKS_03" },
    } },
    ["THANKS_03"] = { thread = "THANKS", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_THANKS_03_L1" } }, terminal = true },
    ["LOST_01"] = { thread = "LOST", lines = { { v = "card", k = "Print_Text_TREK_COMM_LOST_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_LOST_01_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_LOST_01_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_LOST_01_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_LOST_01_O1", go = "LOST_02" },
        { k = "Print_Text_TREK_COMM_LOST_01_O2", go = "LOST_02" },
        { k = "Print_Text_TREK_COMM_LOST_01_O3", go = "LOST_03" },
    }, clears = { "lostDue" } },
    ["LOST_02"] = { thread = "LOST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_LOST_02_L1" } }, terminal = true },
    ["LOST_03"] = { thread = "LOST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_LOST_03_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_LOST_03_L2" } }, terminal = true },
    ["QUIET_01"] = { thread = "QUIET", lines = { { v = "card", k = "Print_Text_TREK_COMM_QUIET_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_QUIET_01_O1", go = "QUIET_02" },
        { k = "Print_Text_TREK_COMM_QUIET_01_O2", go = "QUIET_09" },
    } },
    ["QUIET_02"] = { thread = "QUIET", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_02_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_02_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_QUIET_02_O1", go = "QUIET_03" },
        { k = "Print_Text_TREK_COMM_QUIET_02_O2", go = "QUIET_03" },
    } },
    ["QUIET_03"] = { thread = "QUIET", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_03_L1" } }, sets = { "quiet" }, terminal = true },
    ["QUIET_09"] = { thread = "QUIET", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_09_L1" } }, terminal = true },
    ["RESUME_01"] = { thread = "RESUME", lines = { { v = "card", k = "Print_Text_TREK_COMM_RESUME_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_01_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_01_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_RESUME_01_O1", go = "RESUME_02" },
        { k = "Print_Text_TREK_COMM_RESUME_01_O2", go = "RESUME_03" },
    } },
    ["RESUME_02"] = { thread = "RESUME", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_02_L2" } }, clears = { "quiet" }, terminal = true },
    ["RESUME_03"] = { thread = "RESUME", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_03_L1" } }, terminal = true },
}

return T
