-- GENERATED by tools/gen_adirondack_crops.py -- do not edit.
-- The hydroponics crops' growth sprites (FARMING.md): five tables of
-- eight per crop, as vanilla farming wants them, and the tray's soil.
TREK_FarmSprites = {
    TrekAndorianTuber = {
        sprite = { "trek_adirondack_03_160", "trek_adirondack_03_161", "trek_adirondack_03_162", "trek_adirondack_03_163", "trek_adirondack_03_164", "trek_adirondack_03_165", "trek_adirondack_03_166", "trek_adirondack_03_167" },
        unhealthy = { "trek_adirondack_03_168", "trek_adirondack_03_169", "trek_adirondack_03_170", "trek_adirondack_03_171", "trek_adirondack_03_172", "trek_adirondack_03_173", "trek_adirondack_03_174", "trek_adirondack_03_175" },
        dying = { "trek_adirondack_03_176", "trek_adirondack_03_177", "trek_adirondack_03_178", "trek_adirondack_03_179", "trek_adirondack_03_180", "trek_adirondack_03_181", "trek_adirondack_03_182", "trek_adirondack_03_183" },
        dead = { "trek_adirondack_03_184", "trek_adirondack_03_185", "trek_adirondack_03_186", "trek_adirondack_03_187", "trek_adirondack_03_188", "trek_adirondack_03_189", "trek_adirondack_03_190", "trek_adirondack_03_191" },
        trampled = { "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224" },
    },
    TrekBergamot = {
        sprite = { "trek_adirondack_03_32", "trek_adirondack_03_33", "trek_adirondack_03_34", "trek_adirondack_03_35", "trek_adirondack_03_36", "trek_adirondack_03_37", "trek_adirondack_03_38", "trek_adirondack_03_39" },
        unhealthy = { "trek_adirondack_03_40", "trek_adirondack_03_41", "trek_adirondack_03_42", "trek_adirondack_03_43", "trek_adirondack_03_44", "trek_adirondack_03_45", "trek_adirondack_03_46", "trek_adirondack_03_47" },
        dying = { "trek_adirondack_03_48", "trek_adirondack_03_49", "trek_adirondack_03_50", "trek_adirondack_03_51", "trek_adirondack_03_52", "trek_adirondack_03_53", "trek_adirondack_03_54", "trek_adirondack_03_55" },
        dead = { "trek_adirondack_03_56", "trek_adirondack_03_57", "trek_adirondack_03_58", "trek_adirondack_03_59", "trek_adirondack_03_60", "trek_adirondack_03_61", "trek_adirondack_03_62", "trek_adirondack_03_63" },
        trampled = { "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224" },
    },
    TrekHasperatPepper = {
        sprite = { "trek_adirondack_03_192", "trek_adirondack_03_193", "trek_adirondack_03_194", "trek_adirondack_03_195", "trek_adirondack_03_196", "trek_adirondack_03_197", "trek_adirondack_03_198", "trek_adirondack_03_199" },
        unhealthy = { "trek_adirondack_03_200", "trek_adirondack_03_201", "trek_adirondack_03_202", "trek_adirondack_03_203", "trek_adirondack_03_204", "trek_adirondack_03_205", "trek_adirondack_03_206", "trek_adirondack_03_207" },
        dying = { "trek_adirondack_03_208", "trek_adirondack_03_209", "trek_adirondack_03_210", "trek_adirondack_03_211", "trek_adirondack_03_212", "trek_adirondack_03_213", "trek_adirondack_03_214", "trek_adirondack_03_215" },
        dead = { "trek_adirondack_03_216", "trek_adirondack_03_217", "trek_adirondack_03_218", "trek_adirondack_03_219", "trek_adirondack_03_220", "trek_adirondack_03_221", "trek_adirondack_03_222", "trek_adirondack_03_223" },
        trampled = { "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224" },
    },
    TrekKlingonCoffee = {
        sprite = { "trek_adirondack_03_64", "trek_adirondack_03_65", "trek_adirondack_03_66", "trek_adirondack_03_67", "trek_adirondack_03_68", "trek_adirondack_03_69", "trek_adirondack_03_70", "trek_adirondack_03_71" },
        unhealthy = { "trek_adirondack_03_72", "trek_adirondack_03_73", "trek_adirondack_03_74", "trek_adirondack_03_75", "trek_adirondack_03_76", "trek_adirondack_03_77", "trek_adirondack_03_78", "trek_adirondack_03_79" },
        dying = { "trek_adirondack_03_80", "trek_adirondack_03_81", "trek_adirondack_03_82", "trek_adirondack_03_83", "trek_adirondack_03_84", "trek_adirondack_03_85", "trek_adirondack_03_86", "trek_adirondack_03_87" },
        dead = { "trek_adirondack_03_88", "trek_adirondack_03_89", "trek_adirondack_03_90", "trek_adirondack_03_91", "trek_adirondack_03_92", "trek_adirondack_03_93", "trek_adirondack_03_94", "trek_adirondack_03_95" },
        trampled = { "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224" },
    },
    TrekLeolaRoot = {
        sprite = { "trek_adirondack_03_128", "trek_adirondack_03_129", "trek_adirondack_03_130", "trek_adirondack_03_131", "trek_adirondack_03_132", "trek_adirondack_03_133", "trek_adirondack_03_134", "trek_adirondack_03_135" },
        unhealthy = { "trek_adirondack_03_136", "trek_adirondack_03_137", "trek_adirondack_03_138", "trek_adirondack_03_139", "trek_adirondack_03_140", "trek_adirondack_03_141", "trek_adirondack_03_142", "trek_adirondack_03_143" },
        dying = { "trek_adirondack_03_144", "trek_adirondack_03_145", "trek_adirondack_03_146", "trek_adirondack_03_147", "trek_adirondack_03_148", "trek_adirondack_03_149", "trek_adirondack_03_150", "trek_adirondack_03_151" },
        dead = { "trek_adirondack_03_152", "trek_adirondack_03_153", "trek_adirondack_03_154", "trek_adirondack_03_155", "trek_adirondack_03_156", "trek_adirondack_03_157", "trek_adirondack_03_158", "trek_adirondack_03_159" },
        trampled = { "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224" },
    },
    TrekPlomeek = {
        sprite = { "trek_adirondack_03_96", "trek_adirondack_03_97", "trek_adirondack_03_98", "trek_adirondack_03_99", "trek_adirondack_03_100", "trek_adirondack_03_101", "trek_adirondack_03_102", "trek_adirondack_03_103" },
        unhealthy = { "trek_adirondack_03_104", "trek_adirondack_03_105", "trek_adirondack_03_106", "trek_adirondack_03_107", "trek_adirondack_03_108", "trek_adirondack_03_109", "trek_adirondack_03_110", "trek_adirondack_03_111" },
        dying = { "trek_adirondack_03_112", "trek_adirondack_03_113", "trek_adirondack_03_114", "trek_adirondack_03_115", "trek_adirondack_03_116", "trek_adirondack_03_117", "trek_adirondack_03_118", "trek_adirondack_03_119" },
        dead = { "trek_adirondack_03_120", "trek_adirondack_03_121", "trek_adirondack_03_122", "trek_adirondack_03_123", "trek_adirondack_03_124", "trek_adirondack_03_125", "trek_adirondack_03_126", "trek_adirondack_03_127" },
        trampled = { "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224" },
    },
    TrekTeaBush = {
        sprite = { "trek_adirondack_03_0", "trek_adirondack_03_1", "trek_adirondack_03_2", "trek_adirondack_03_3", "trek_adirondack_03_4", "trek_adirondack_03_5", "trek_adirondack_03_6", "trek_adirondack_03_7" },
        unhealthy = { "trek_adirondack_03_8", "trek_adirondack_03_9", "trek_adirondack_03_10", "trek_adirondack_03_11", "trek_adirondack_03_12", "trek_adirondack_03_13", "trek_adirondack_03_14", "trek_adirondack_03_15" },
        dying = { "trek_adirondack_03_16", "trek_adirondack_03_17", "trek_adirondack_03_18", "trek_adirondack_03_19", "trek_adirondack_03_20", "trek_adirondack_03_21", "trek_adirondack_03_22", "trek_adirondack_03_23" },
        dead = { "trek_adirondack_03_24", "trek_adirondack_03_25", "trek_adirondack_03_26", "trek_adirondack_03_27", "trek_adirondack_03_28", "trek_adirondack_03_29", "trek_adirondack_03_30", "trek_adirondack_03_31" },
        trampled = { "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224", "trek_adirondack_03_224" },
    },
}
TREK_FarmSoil = "trek_adirondack_03_224"
return TREK_FarmSprites
