--[[ Shuttlecraft -- shared configuration.

    Everything the mod hard-codes about the world lives here: where the cabin
    is parked, how it is laid out, which sprites dress it, how much ground the
    hull needs before it will set down, and what is stocked into the lockers.

    Sprite names come from media/newtiledefinitions.tiles.txt and item ids
    from media/scripts/generated/items/, both for build 42.20. A wrong name
    fails *silently* in game -- the square is simply empty -- so every one of
    them is checked by tests/test_assets.py before the game is ever launched.
]]

TREK = TREK or {}

local C = {}
TREK.Config = C

C.Version   = "1.3.0"
-- The key predates multiplayer and is kept so single-player saves carry over;
-- the table inside is migrated by U.state() (schema 2).
C.StateKey  = "TREK_State_v1"
C.ModPrefix = "[TREK]"

-- Bumped whenever the cabin needs rebuilding to pick up changes to the way it
-- is generated. A cabin built at an older revision is quietly brought up to
-- date the next time the player is aboard; the rebuild preserves furniture,
-- stored items and anything dropped on the deck.
C.BuildRev = 17

-- Flip to true for verbose build logging in console.txt.
C.Debug = false

-- Design-time only. Normally a rebuild leaves every container exactly as the
-- player left it -- a ship in play is meant to be lived in, and what gets
-- eaten stays eaten. With this on a rebuild restocks as well, which is what
-- you want while iterating on loot lists and never want in a world somebody
-- is playing. TREK_Rebuild() turns it on for one rebuild instead.
C.DevRestock = false

---------------------------------------------------------------------------
-- Where the cabin lives
---------------------------------------------------------------------------
-- Build 42 cells are 256 squares and vanilla ships cells out to x=77. The
-- Fifth-Wheel RV interior squats on cell 85,40 and the TARDIS mod, if it is
-- also installed, runs from cell 92,40 east across six deck footprints. Cell
-- 96,40 clears all three, and its y stays under 12000 so it also falls
-- outside the unbounded exit-menu test Project RV Interior applies.
C.InteriorCell = { x = 96, y = 40 }

-- The mod's map folder (media/maps/TrekShuttle): empty map cells around the
-- interior cell, so the world generator never grows grass, trees or zombies
-- there and the space outside the cabin is black. Generated by
-- tools/gen_void_map.py. Single player and the in-game Host settings add it
-- by themselves; a dedicated server lists it in its Map= setting.
C.VoidMap = "TrekShuttle"

-- Offset of the cabin inside that cell, so nothing touches a cell edge; chunk
-- seams make edge squares awkward to generate reliably.
C.RoomOffset = 16

-- The cabin is one compartment on one storey. There is no deck stack, so
-- none of the TARDIS's sideways-stepping is needed -- but the reason for it
-- still applies and is worth keeping in mind before adding a second level:
-- Project Zomboid draws every z level above the player and only hides what is
-- overhead when it believes you are inside a building, which means RoomDef
-- metadata baked into a map lotheader that runtime squares cannot have. A
-- deck above this one would be drawn straight over it.
C.CabinZ = 4

-- Cabin extent, as inclusive offsets: 0..CabinW across, 0..CabinL fore-aft.
-- oy 0 is the bow.
--
-- Four across by six fore-and-aft: twenty-four squares, one wider and one
-- longer than the 3x5 hull that is drawn outside. The cabin was 6x9 until
-- the refit, and fifty-four squares of lockers, fridges, a cargo bay and a
-- berth read as a warehouse the shuttle was parked next to rather than as
-- the inside of the shuttle. Everything the ship needs still has a place;
-- nothing has a spare one.
C.CabinW = 3
C.CabinL = 5

-- What the cabin used to be, and the only reason it is written down: a save
-- made before the refit has tagged furniture standing on squares that are now
-- outside the hull, and nothing that walks the *new* shape will ever visit
-- them. B.refitCabin sweeps this extent once. See DEV_GUIDE.md,
-- "Moving geometry is a migration, not a rebuild".
C.LegacyCabin = { w = 5, l = 8 }

-- How far beyond the hull to strip the procedural wilderness the engine grows
-- in unmapped cells. Everything in this ring is removed down to bare nothing,
-- which renders as the black void the Fifth-Wheel RV interior sits in.
C.ClearMargin = 24

-- The transporter pad, aft, beside the foot of the biobed. Arrivals -- beaming
-- up, walking in through the hatch, coming back from a failed landing -- all
-- put the player down here, and it is refused by every placement helper so
-- nothing is ever in the way.
--
-- Aft rather than amidships so that materialising puts the length of the ship
-- in front of you rather than half of it behind: you arrive at the sick bay,
-- walk forward past the lockers and the galley, and the viewscreen is what
-- you are looking at. It is also where the contents of a container the refit
-- deletes are spilled.
C.Landing = { x = 2, y = 5, clearance = 0 }

--- True for the pad square and the ring of squares around it.
function C.isLanding(ox, oy)
    return math.abs(ox - C.Landing.x) <= C.Landing.clearance
       and math.abs(oy - C.Landing.y) <= C.Landing.clearance
end

-- Deckhead lighting. The server places the fittings; each client hangs the
-- light itself, because a light source is not a synced world object.
-- tests/test_layout.py checks these offsets against the floor plan.
C.LampSpots = {
    { 1, 1 }, { 1, 4 },
}

---------------------------------------------------------------------------
-- Hull shape
---------------------------------------------------------------------------
-- Project Zomboid has no diagonal wall sprites -- a wall only ever sits on
-- the north or west edge of a square -- so a smoothly curved hull is not
-- available at any size. What is available is a stepped chamfer, and at the
-- game's camera angle a bow cut back six squares reads clearly as a nose.
--
-- NoseCut is how far the bow is pinched in, TailCut the same at the stern.
-- Bigger noses are pointier; past about half of CabinW the bow stops being
-- wide enough to stand in.
C.NoseCut = 0
C.TailCut = 0

--- True when an offset is inside the cabin floor plan.
---
--- Walls are derived from this rather than hard-coded, so changing the cuts
--- reshapes the hull and its walls together and nothing else needs touching.
function C.inShape(ox, oy, w, l, nose, tail)
    w = w or C.CabinW
    l = l or C.CabinL
    nose = nose or C.NoseCut
    tail = tail or C.TailCut
    if ox < 0 or oy < 0 or ox > w or oy > l then return false end
    -- cut a right triangle off each corner: a deeper cut forward than aft,
    -- which is what makes it read as a bow rather than a lozenge
    if (ox + oy) < nose then return false end
    if ((w - ox) + oy) < nose then return false end
    if (ox + (l - oy)) < tail then return false end
    if ((w - ox) + (l - oy)) < tail then return false end
    return true
end

---------------------------------------------------------------------------
-- The hull outside
---------------------------------------------------------------------------
-- How much clear ground the shuttle needs before it will set down, in
-- squares, centred on the square being asked about. This is the whole
-- difference between calling this ship down and materialising a police box:
-- a box needs one tile and can appear in a hallway, and a shuttle needs a
-- street or a field.
--
-- Kept in step by hand with HULL_W / HULL_L in tools/gen_shuttle.py, which is
-- how big the model is actually drawn. Nothing in the engine ties the two
-- together -- a world model is drawn from one square and simply overhangs the
-- rest -- so if you change one, change the other.
C.Footprint = { w = 3, h = 5 }

--- Every offset the hull covers, relative to the square it is anchored on.
--- Even-sided footprints are biased to the north-west, which is the corner
--- the isometric camera shows least of.
---
--- Built once and handed back. This is walked inside the landing search,
--- which examines thousands of candidate squares in a single pass, and
--- rebuilding a fifteen-entry table for each of them is pure garbage.
local footprint = nil

function C.footprintOffsets()
    if footprint then return footprint end
    local out = {}
    local hw = math.floor((C.Footprint.w - 1) / 2)
    local hh = math.floor((C.Footprint.h - 1) / 2)
    for dx = -hw, C.Footprint.w - 1 - hw do
        for dy = -hh, C.Footprint.h - 1 - hh do
            table.insert(out, { dx, dy })
        end
    end
    footprint = out
    return out
end

-- Radius, in tiles, of the field that holds the dead back from the hatch.
C.FieldRadius = 10

-- Whether a new world starts with the shields up. They can be lowered and
-- raised from the helm; there is deliberately no radius control, only the
-- state. The setting is saved with the world, so this is only the default.
C.ShieldsDefault = true

---------------------------------------------------------------------------
-- The transporter
---------------------------------------------------------------------------
-- Beaming is the shuttle's own trick and is deliberately not gated on the
-- ship being anywhere in particular: when it is not sitting on the ground it
-- is overhead, and the pad reaches you either way.
--
-- The delay is flavour with a purpose -- an instant snap reads as a debug
-- teleport, and a second and a half of dematerialising reads as a transporter
-- and gives the halo note time to be seen. Ticks.
C.BeamDelay = 90

-- How far a beam-down may miss by when the exact square is occupied.
C.BeamScatter = 6

-- Transporter charges. On a server whose speed anti-cheat kicks or bans
-- (AntiCheatSpeed 1 or 2), every long move of a character is one strike and
-- four uncleared strikes remove the player; one strike clears every 150
-- seconds. So each player gets that budget as charges, and the fourth beam is
-- refused in lore ("recharging") instead of the server kicking them. Single
-- player, and servers that only log or ignore the check, are unlimited.
C.TransporterCharges       = 3
C.TransporterRechargeSecs  = 150

---------------------------------------------------------------------------
-- Flight: the sky plane
---------------------------------------------------------------------------
-- The shuttle flies by *driving*, on an invisible floor the mod lays at
-- altitude. This is not a flourish, it is the only thing build 42 allows.
--
-- BaseVehicle.update() sets a vehicle's z to 0 every single tick, and then
-- puts it back to its physics level only if a floor tile exists under the
-- vehicle's centre square at that level (or the one below). Everything that
-- matters reads that clamped z: the render camera, where the occupants are
-- drawn, isIntersectingSquare, breakingObjects/damageObjects, and -- on every
-- other player's machine -- clientUpdateVehiclePos, which writes setZ(0)
-- outright. Lifting the physics body alone therefore gives a ship that flies
-- in the physics engine and sits on the ground in the game, ploughing through
-- fences as it goes. That was tried on paper and disproved from the bytecode
-- before a line of it was written (PILOTING.md section 5.1).
--
-- Put a floor there and the whole problem dissolves: the z is legitimate, so
-- the ship and its crew are drawn in the air; collision resolves at the flight
-- level, so it passes over a two-storey building instead of demolishing it;
-- the wheels have something to rest on, so the engine's own physics drives it
-- and no part of this mod has to fight gravity; and because the floor holds
-- the ship up, nothing falls out of the sky when the pilot leaves the seat.
--
-- The tile is vanilla. invisible_01_0's only two properties are attachedFloor
-- and solidfloor: a floor that is solid and cannot be seen.
C.SkyTile = "invisible_01_0"

-- Bullet units per z level, read straight out of BaseVehicle.setDebugZ's
-- bytecode: it computes fastfloor(origin.y / 2.4494900703430176). Three times
-- 0.8164966702461243 is the same number; both constants are in that method.
C.LevelUnits = 2.4494900703430176

-- How far around the ship the plane extends, in squares.
--
-- Deliberately small, and it was not always. A floor is a floor: the engine
-- treats everything under one as being indoors and stops drawing the ground
-- below it, so a wide plane put a disc of blackness around the ship and hid
-- the very world she was flying over. Seen in game, 2026-09-17 -- "I can see
-- the world but near me is a sphere of blackness."
--
-- The hull is 3 by 5, so 2 squares out is a 5 by 5 patch: the smallest that
-- still covers her at any heading and gives the wheels something under them.
--
-- This is the only real lever on the darkness. A floor darkens whatever is
-- beneath it and nothing can stop that, so the patch has to be small enough
-- that the hull is drawn over it. It was 16, then 4, then 3, and at 3 with a
-- square of margin the kept area was a 9 by 9 box -- 81 squares of shadow
-- around a hull that covers 15, which is the "trailing dark blotch". 5 by 5 is
-- 25 against the hull's 15, so what is left is a one-square rim under her
-- rather than a wake behind her.
C.SkyRadius = 2

-- No margin at all: a square is lifted the moment she is not over it. The
-- margin existed so she was never chasing her own floor, but the paver
-- recentres every tick and lays the centre square first, so there is nothing
-- to chase -- and every square of margin is a square of shadow trailing her.
C.SkyTrailMargin = 0

-- How far around a player to hunt for invisible floors nobody is using, in
-- squares. Much larger than the patch, because this is not about the plane the
-- ship is flying on -- it is about the ones it left behind.
--
-- A floor is a world object and world objects are saved. Every build of this
-- feature that laid a wider plane, or trimmed it less eagerly, left its floors
-- in whatever world it was tested in, and they are still there: a black
-- blotch across a car park, seen in a screenshot after the plane itself was
-- already down to 25 squares. The ship's own record only remembers the last
-- flight, so the only way to clear the rest is to go and look.
C.SkyCleanRadius = 32

-- How far a player must move before that area is swept again. There is no
-- timer besides this: ground that has been swept has nothing left to find, and
-- ground that has not should not be made to wait.
C.SkyCleanStride = 20

-- Squares paved per tick. The plane is laid the way the landing search is
-- walked -- a cursor and a slice -- because a thousand addFloor calls in one
-- frame is not slow, it is the hard lock described in DEV_GUIDE.md under
-- "Slice any search that touches thousands of squares".
C.SkyTilesPerTick = 96

-- A ceiling on the plane, so a long flight cannot grow the list without
-- bound. Past this the squares furthest behind the ship are lifted first.
C.SkyMaxTiles = 40000

-- Cruising height, and the levels the pilot may climb and dive between. Level
-- 0 is the ground and is never paved -- a floor laid there would be a floor
-- laid on Kentucky. Three clears a two-storey building with room to spare.
C.FlightCruise   = 3
C.FlightMinLevel = 1

-- One level above the cruise and no more. Higher was offered and was not worth
-- having: the levels above this are past the height the world has any geometry
-- at, the ship has nothing to be "over" up there, and every trip that far up
-- ended badly. Kept as cruise + 1 rather than a bare number so the two cannot
-- drift apart.
C.FlightMaxLevel = 4

-- Ticks to wait for the engine to accept a level before giving up on the lift.
C.FlightLiftTicks = 60

-- Degrees of pitch or roll tolerated before she is levelled off again. She
-- rests on an invisible floor with real physics running, and a 1200kg box on a
-- one-tile-thick shelf will tip if it is nudged -- she went over backwards in
-- game. flipUpright touches only the rotation, never the height.
C.FlightLevelTolerance = 4

-- The helm's flight speeds, as the vehicle's own top speed in the units
-- setMaxSpeed takes (the shuttle's script sets 70 on the ground).
--
-- Absolute figures, not multipliers, and that is a correction. They were
-- multipliers of a base of 30, capped at 0.6 of the server's SpeedLimit of
-- 70 -- which is 42, so the top three steps all clamped to exactly the same
-- number and the control appeared to do nothing at all. Anything the pilot can
-- pick must be distinguishable from its neighbours or it is not a control.
C.FlightSpeedSteps       = { 15, 30, 50, 70, 95, 120 }
C.FlightSpeedDefaultStep = 3

-- On a server the vehicle speed limiter is the server owner's business, so the
-- choice is capped by it. In single player there is nobody to protect and no
-- anti-cheat to trip, so the pilot gets the whole range.
C.FlightSpeedCapFraction = 1.0

-- Consecutive server checks with no pilot in the driver's seat before the
-- ship is brought down by itself. A ship left parked in the sky by somebody's
-- disconnect would otherwise stay there for the life of the world.
C.FlightPilotGrace = 5

---------------------------------------------------------------------------
-- Photon torpedoes
---------------------------------------------------------------------------
-- A cooldown, not ammunition: the shuttle makes her own, so there is nothing
-- to run out of and nothing to stock a locker with.
--
-- These numbers are vanilla's, deliberately. A build 42 explosion is an
-- IsoTrap, and vanilla's PipeBomb is ExplosionPower 90 over ExplosionRange 7
-- -- so a torpedo is a pipe bomb's blast delivered from the air. Borrowing
-- the figures rather than inventing them means the damage is already
-- balanced against everything else that explodes in this game.
C.TorpedoPower = 90
C.TorpedoRange = 7

-- The warhead. Not an item anyone ever holds: IsoTrap.new copies the whole
-- explosion off a HandWeapon and throws on a nil one, so this exists to be
-- handed to it and discarded. Its own script block carries the same numbers.
C.TorpedoItem = "TrekShuttle.TrekTorpedo"

-- **The fire is the weapon, and this number is how much of it there is.**
--
-- This said 0 for three commits, with a comment insisting it must stay there.
-- That was a misreading of the roadmap's "an explosion that does not set the
-- street on fire", taken to mean no fire at all. It meant fire that is an
-- intended weapon effect rather than an accident. At 0 a torpedo is a silent
-- stat change: zombies fall over and nothing is seen, because **in this engine
-- the visible part of an explosion IS the fire and the smoke.** There is no
-- separate explosion effect to fall back on.
--
-- What the bytecode actually does with it (tools/javadis.py on
-- IsoTrap.drawCircleExplosion, which is worth re-reading before touching this):
--
--   * the roll is `Rand.Next(100) < getFireStartingChance()` and it is taken
--     **once per square, inside the double loop** -- so this is a *density*
--     dial, not a yes/no. At 60, about three squares in five ignite;
--   * there are **two independent rolls** in Explosion mode, not one: bci 197
--     gates IsoFireManager.StartFire, bci 254 gates IsoGridSquare.Burn().
--     An earlier note here called it a single roll;
--   * Burn() -> BurnWalls(true, true) is what actually **destroys structures**,
--     and it is gated on `!GameClient.client`, so it is server-authoritative
--     for free. It also checks ServerOptions.noFire and SafeHouse.isSafeHouse
--     itself, which is why a server owner who has turned fire off is already
--     respected without a line of ours.
C.TorpedoFireChance = 60

-- Handed to IsoFireManager.StartFire as its energy argument (read once at
-- bci 7). Vanilla's own fire brush and the campfire code both use 100.
C.TorpedoFireEnergy = 100

-- **Three ranges, not one.** triggerExplosion() calls drawCircleExplosion
-- three separate times -- ExplosionRange in Explosion mode, FireRange in Fire
-- mode, SmokeRange in Smoke mode -- and skips any of them whose range is <= 0.
-- That is how the build was silent on two of the three: they were zero, so
-- those two calls never happened at all.
--
-- FireRange is a ring *beyond* the blast that only ever starts fire, so the
-- burn is wider than the damage: the torpedo kills inside 7 and lights inside
-- 10. Smoke is wider still, because smoke is what you see from the air.
--
-- **Every one of these is clamped to 15 by the engine** (`Math.min(range, 15)`
-- is the first instruction in drawCircleExplosion). Setting any of them higher
-- does nothing and only misleads whoever reads it next.
C.TorpedoFireRange = 3
C.TorpedoSmokeRange = 9

-- How far from the ship the pilot may put one, in tiles. Bounded because the
-- target square arrives from a client and a client is a request, never a fact:
-- without this, a crafted command is a mortar with map-wide reach.
C.TorpedoMaxRange = 28

-- Between shots, in milliseconds, held on the ship rather than the player --
-- there is one set of tubes, so two crew cannot take turns to halve it.
C.TorpedoCooldownMs = 6000

-- The blast is centred on the ground, so a torpedo fired at your own shadow
-- would catch the ship. **Raised from 4 to 12 when the fire was turned on**,
-- and the arithmetic is the reason: the blast is C.TorpedoRange (7) and the
-- fire ring reaches C.TorpedoRange + C.TorpedoFireRange (10), so at the old
-- distance the pilot lit a fire they were sitting in and had to land in later.
-- If either range grows, this must grow with it.
C.TorpedoMinRange = 12

-- Sandbox: 1 = Full (the torpedo burns), 2 = Blast only (damage, no fire).
-- Read server-side in TREK_Server.lua. A server owner who wants the weapon
-- without the arson gets it here; one who wants no fire anywhere at all
-- already has ServerOptions.noFire, which Burn() checks by itself.
C.TorpedoFireFull = 1
C.TorpedoFireNone = 2

---------------------------------------------------------------------------
-- Photon torpedoes: the projectile
---------------------------------------------------------------------------
-- **The torpedo is drawn in screen space, and nothing about it touches the
-- world.** The obvious build is an IsoObject walked along the ground from ship
-- to target, and it was the wrong one twice over: there is no explosion,
-- flame or smoke tile anywhere in the tileset to put on it (fire is an
-- attached animation, not a sprite), and a client laying world objects every
-- tick is the sky plane's whole catalogue of trouble -- squares that will not
-- answer, shadows outliving the thing that cast them, debris left in the air
-- when a flight ends badly.
--
-- Instead the flight is a texture drawn on the reticle's own overlay, placed
-- with isoToScreenX/Y -- GlobalObject statics with ten non-debug vanilla call
-- sites (the foraging icons, the fishing tension UI, ISButtonPrompt). It
-- cannot leave anything behind, because it never put anything anywhere.
--
-- The one thing that does reach the world is a moving light, and that is the
-- same documented exception the cabin's lamps and the sky plane already use:
-- scenery, per client, never ship state.

-- Tiles per second. A 28-tile shot at 30 is a touch under a second: long
-- enough to watch it go, short enough that it reads as a weapon rather than a
-- thrown rock.
C.TorpedoSpeed = 30

-- Floor and ceiling on the flight, in milliseconds. The floor stops a
-- minimum-range shot being a single frame; the ceiling is a safety net so a
-- silly speed cannot leave a detonation pending for ever.
C.TorpedoMinFlightMs = 250
C.TorpedoMaxFlightMs = 2000

-- How many fading echoes trail behind the head, and how far apart in
-- milliseconds. Drawn, never placed -- a trail costs nothing but alpha.
C.TorpedoTrail = 6
C.TorpedoTrailMs = 45

-- The light that rides with it: colour and radius for addLamppost. Removed
-- with removeLamppost when the torpedo detonates, and rebuilt at most once a
-- tile -- a light moved every frame is a lot of engine churn for a thing in
-- the air for one second.
C.TorpedoLight = { r = 0.55, g = 0.80, b = 1.00, radius = 5 }

---------------------------------------------------------------------------
-- Photon torpedoes: the controller
---------------------------------------------------------------------------
-- The reticle is moved by the **right** stick, because the left one is
-- steering -- BaseVehicle drives off forwardAxis and setAngleAxis -- and
-- firing is the right stick click. The triggers are deliberately untouched:
-- they are the obvious home for accelerate and brake, that binding lives in
-- Java where this mod cannot read it, and an input that fights the controls
-- is worse than no input at all.

-- Pixels per second at full deflection. Tuned so a reticle crosses a 1080p
-- screen in about two seconds -- fast enough to swing onto a target while
-- flying past it, slow enough to place on one building rather than the next.
C.TorpedoAimSpeed = 950

-- Radial dead zone. Below this the stick is treated as centred, so a worn
-- one cannot walk the reticle across the screen on its own.
C.TorpedoAimDeadzone = 0.18

-- How near the screen edge the reticle may be pushed. Not zero: at the very
-- edge half the reticle is off-screen and screenToIso is being asked about a
-- point the camera is barely showing.
C.TorpedoAimMargin = 24

---------------------------------------------------------------------------
-- Travel
---------------------------------------------------------------------------
-- Travel is also by the helm: lay in a course, then take her down. That is
-- the way to cross the map; flight above is the way to fly it by hand.
C.MaxBookmarks        = 40
C.MaxBookmarkName     = 40   -- characters; a name is sent to the server
C.LandingSearchRadius = 24   -- squares to spiral out from a chosen site

-- How long to keep trying to set down at a destination before giving up and
-- beaming the player back aboard. Ticks; the first few hundred are spent
-- waiting for the area to stream in at all.
C.LandingTimeout = 420

---------------------------------------------------------------------------
-- Phasers
---------------------------------------------------------------------------
-- Two names for one item: the engine's inventory search compares the bare
-- type, while anything that spawns or places the item wants the full id.
C.PhaserItem = "TrekShuttle.TrekPhaser"
C.PhaserType = "TrekPhaser"

-- A phaser never runs out, never jams and never wears out. TREK_Phaser.lua
-- tops up every one the player is carrying on a slow tick; these are the
-- three things it puts back.
C.PhaserInfiniteAmmo = true
C.PhaserNeverJams    = true
C.PhaserNeverWears   = true

-- How often to top a carried phaser up, in ticks. It only has to beat the
-- rate a player can empty a magazine, so this is deliberately slow.
C.PhaserInterval = 30

-- The locker they are kept in -- the armoury, first of the starboard run --
-- and how many are in it. tests/test_layout.py holds this in step with the
-- authored entry marked `special = "phasers"`.
C.PhaserRack  = { x = 3, y = 0 }
C.PhaserCount = 4

---------------------------------------------------------------------------
-- The medical set
---------------------------------------------------------------------------
-- Three items, and the same two-names-for-one-item rule the phaser follows:
-- the engine's recursive inventory search compares the *bare* type, and
-- anything that spawns or places the item wants the full id.
C.HyposprayItem    = "TrekShuttle.TrekHypospray"
C.HyposprayType    = "TrekHypospray"
C.MedTricorderItem = "TrekShuttle.TrekMedTricorder"
C.MedTricorderType = "TrekMedTricorder"
C.TricorderItem    = "TrekShuttle.TrekTricorder"
C.TricorderType    = "TrekTricorder"
C.DermalRegenItem  = "TrekShuttle.TrekDermalRegen"
C.DermalRegenType  = "TrekDermalRegen"

-- The dermal regenerator has **no charge economy at all**, and that is a
-- decision rather than an omission. The hypospray already owns the
-- six-doses-and-go-home limit, and giving this one the same thing would make
-- them the same item twice. It is a powered instrument: you run it over the
-- skin and the skin closes.
--
-- What keeps it from replacing the hypospray is scope, not cost. It closes
-- what is *open* -- cuts, scratches, deep wounds, bleeding, burns, and the
-- stitches and dressing that were holding them together -- and it does not
-- touch an infected cut, pain, stiffness or a fracture. Those are still the
-- hypospray's, and an infected wound is still what kills you.
--
-- It also will not work on a part with glass or a bullet still in it. Skin
-- does not close over a shard, and tweezers keep a reason to exist.

-- Doses in a full hypospray, and how often the ship replicates another one
-- into it, in ticks, **while the carrier is aboard**.
--
-- This is the one real limit on the item and it is deliberate. Everything
-- else Starfleet issues in this mod is unlimited -- the phaser never runs
-- dry, the torpedo tubes make their own -- and a pocket device that also
-- cures every wound in the game at will is a different proposition: it
-- removes the whole medical layer of Project Zomboid rather than adding to
-- it. Six doses is a bad day survived; the seventh means going home.
--
-- Sixty ticks is a second, so this is one dose every fifteen seconds aboard
-- and a minute and a half from empty to full. The recharge is deliberately
-- tied to the cabin rather than to time: it is the ship that makes them.
C.HyposprayDoses         = 6
C.HyposprayRechargeTicks = 900

-- What a dose will not touch, and there is deliberately no constant for it.
--
-- A bite and the zombie infection are the EMH's, and they are the entire
-- reason the EMH is worth building. That is enforced by `Med.TREATMENTS` in
-- TREK_Medical.lua not containing them, and by a test that bites a body
-- before every dose and asserts the bite survived -- not by a flag. A
-- `C.HyposprayCuresBites = false` that nothing ever branches on would be a
-- decoration: it would keep saying false long after somebody had added
-- SetBitten to the treatment list.
--
-- Worth knowing while reading that list, because the names give no help:
-- BodyPart.setInfectedWound is an ordinary infected cut and **is** cured;
-- BodyDamage.setInfected is the virus and is never touched.

-- The Doctor level the medical tricorder reports at. ISHealthPanel gates its
-- readouts at > 2, > 4, > 6 and > 8, so anything past 8 opens all of them;
-- 10 is the top of the skill and says what it means.
--
-- Set on the panel *instance* (panel.doctorLevel), never through
-- ISHealthPanel.cheat -- that global is `false or getDebug()` and otherwise
-- admin-only, so it would work here and for nobody on the Workshop.
C.MedDoctorLevel = 10

-- The sensor sweep. Radius in tiles, and how many contacts to classify per
-- tick: the list is walked with a cursor and a slice for the same reason the
-- landing search is, and a sweep that ran in one frame on a horde would be
-- the hard lock described in DEV_GUIDE.md.
--
-- 40 tiles is about twice what a player can see, which is the point of
-- having one at all, and comfortably inside the chunks a client has loaded.
C.SweepRadius      = 40
C.SweepPerTick     = 96
C.SweepIntervalMs  = 3000    -- between sweeps, so the panel cannot be spammed

-- The three range bands the contacts are sorted into, as fractions of the
-- radius. Named in the readout rather than given as numbers: a tricorder
-- reports "close" before it reports "thirteen metres".
C.SweepBands = { 0.33, 0.66 }

-- The lock override. Range in tiles from the player to the lock, and the
-- cooldown between overrides in milliseconds, held per player on the server.
--
-- The range is small because the server validates it and a client is a
-- request, never a fact: without a bound, a crafted command unlocks the map.
C.UnlockRange       = 2
C.UnlockCooldownMs  = 20000

---------------------------------------------------------------------------
-- Sprites
---------------------------------------------------------------------------
-- Facing keys name the wall an object stands against, which is also the way
-- it looks into the room. A sprite whose set has fewer than four facings only
-- lists the ones that exist, and the placement helpers fall back to S.
C.Sprites = {
    -- Hull: industry_01 is a light-metal wall set, which is as close to a
    -- ship's bulkhead as build 42 ships. Index 0 is the west face, 1 the
    -- north face, 2 the corner post -- the same layout every wall set uses.
    wallW = "industry_01_0",
    wallN = "industry_01_1",
    wallC = "industry_01_2",

    deckFloor = "floors_interior_tilesandwood_01_0",  -- solid deck
    padFloor  = "floors_interior_tilesandwood_01_1",  -- solid transporter tile

    lamp   = { S = "lighting_indoor_01_32", E = "lighting_indoor_01_8",
               W = "lighting_indoor_01_40", N = "lighting_indoor_01_48" },

    sink   = { N = "fixtures_sinks_01_0", E = "fixtures_sinks_01_1",
               S = "fixtures_sinks_01_2", W = "fixtures_sinks_01_3" },
    toilet = { S = "fixtures_bathroom_01_0", E = "fixtures_bathroom_01_1",
               W = "fixtures_bathroom_01_2", N = "fixtures_bathroom_01_3" },
    shower = { N = "fixtures_bathroom_01_22", W = "fixtures_bathroom_01_23" },

    -- Steel counters rather than the wooden kitchen sets: this is a galley in
    -- a metal hull, not somebody's kitchen.
    counter = { N = "fixtures_counters_01_33", E = "fixtures_counters_01_35",
                S = "fixtures_counters_01_37", W = "fixtures_counters_01_39" },
    fridge  = { S = "appliances_refrigeration_01_0", E = "appliances_refrigeration_01_1",
                N = "appliances_refrigeration_01_2", W = "appliances_refrigeration_01_3" },
    oven    = { E = "appliances_cooking_01_0", S = "appliances_cooking_01_1",
                W = "appliances_cooking_01_2", N = "appliances_cooking_01_3" },
    microwave = { S = "appliances_cooking_01_25", E = "appliances_cooking_01_24",
                  W = "appliances_cooking_01_26", N = "appliances_cooking_01_27" },

    metalShelf = { S = "furniture_shelving_01_28", E = "furniture_shelving_01_29",
                   W = "furniture_shelving_01_30", N = "furniture_shelving_01_31" },
    locker     = { S = "furniture_storage_02_8", E = "furniture_storage_02_9",
                   N = "furniture_storage_02_10", W = "furniture_storage_02_11" },
    crate      = "location_military_generic_01_0",
    chair      = { E = "furniture_seating_indoor_01_8", S = "furniture_seating_indoor_01_9",
                   W = "furniture_seating_indoor_01_10", N = "furniture_seating_indoor_01_11" },

    -- The cockpit. security_01 "Terminal" is a floor-standing console and
    -- security_01_4/5 a bank of wall-mounted screens, which between them read
    -- as a helm without a single custom tile.
    terminal = { S = "security_01_0", E = "security_01_1",
                 N = "security_01_2", W = "security_01_3" },
    monitors = { S = "security_01_4", E = "security_01_5" },
    computer = { S = "appliances_com_01_72", E = "appliances_com_01_73",
                 N = "appliances_com_01_74", W = "appliances_com_01_75" },

    -- Sick bay. The wide medical cabinet holds thirty, which is what makes a
    -- "large container of medical supplies" actually large.
    medCabinet = { E = "location_community_medical_01_152",
                   S = "location_community_medical_01_154",
                   N = "location_community_medical_01_238",
                   W = "location_community_medical_01_246" },
    medDrawers = { E = "location_community_medical_01_36",
                   S = "location_community_medical_01_37",
                   W = "location_community_medical_01_38",
                   N = "location_community_medical_01_39" },
}

---------------------------------------------------------------------------
-- Multi-tile furniture
---------------------------------------------------------------------------
-- A bed covers more than one square and which half goes where is not
-- guessable: it comes from the tileset's SpriteGridPos property, given here
-- as {sprite, dx, dy}. Getting it backwards lays the foot of the bed where
-- its head belongs, which is invisible in the code and obvious in game.
-- tests/test_layout.py checks every offset here against the game data.
-- The bunk went with the refit: the biobed carries BedType = goodBed, so the
-- sick bay is also where you sleep, and a shuttle with both in twenty-four
-- squares is a shuttle with nowhere to stand.
C.Pieces = {
    biobedS = { { "location_community_medical_01_17", 0, 0 },
                { "location_community_medical_01_16", 0, 1 } },
}

---------------------------------------------------------------------------
-- Water
---------------------------------------------------------------------------
-- Which layout tags are plumbed. Anything tagged one of these is kept full,
-- so adding a fixture in BuildingEd needs no code change -- only the tag.
C.WaterTags = { sink = true, shower = true, toilet = true }

-- The ship makes its own water, so the fixtures are topped up rather than
-- piped. This matters more than it sounds: the sink sprites carry the
-- vanilla `waterPiped` property, which feeds them from the town mains, and
-- the mains shut off a few weeks into any world. A shuttle whose tap stops
-- working the same week Louisville's does is not much of a shuttle.
--
-- Ticks between top-ups while somebody is aboard. The ten-minute timer keeps
-- it full when nobody is; this makes it impossible to drain in front of you.
C.WaterInterval = 120

-- How much each plumbed fixture holds, in litres. A runtime sink has no water
-- store of its own, so the server gives it one this size (vanilla's own
-- addWaterContainer command does exactly this) and keeps it topped up.
C.WaterCapacity = 20

---------------------------------------------------------------------------
-- Power
---------------------------------------------------------------------------
-- What a powered fitting's cell is kept at, 0..1. DeviceData.setPower clamps
-- to that range, and a device that is switched on loses its item script's
-- UseDelta every game minute -- 0.007 for a television, so a full cell is
-- about two and a half game hours. TREK_Power tops every fitting back up
-- once a game minute, in every process, so it can never be outrun.
--
-- The whole reason it is the *device's* power rather than the square's is in
-- the header of TREK_Power.lua: setHaveElectricity does not set a flag, and
-- haveElectricity() means "a generator is running in this chunk".
C.DevicePower = 1.0

---------------------------------------------------------------------------
-- Items placed in the cabin
---------------------------------------------------------------------------
-- The hull outside is a world model, defined in media/scripts/trekshuttle.txt.
C.ExteriorItem = "TrekShuttle.TrekShuttleHull"

-- The helm console. Not placed any more: it was a 70-weight static model
-- standing in the cabin that did nothing at all. The helm panel opens from
-- the aboard menu -- right-click anywhere aboard, Shuttlecraft, Helm -- and
-- never from that object. In a fifty-four square cabin it read as furniture;
-- in twenty-four it was a big box in the middle of the room.
--
-- The *item* is still declared in media/scripts/trekshuttle.txt on purpose.
-- Saves made before this have one lying on the deck, and deleting an item
-- type that existing world items refer to is a question about the engine's
-- save loader that nobody here has answered. B.refitCabin removes them; the
-- script block, the mesh and tools/gen_helm.py go once that has been seen to
-- work in a real save.
C.LegacyHelmItem = "TrekShuttle.TrekHelmConsole"

---------------------------------------------------------------------------
-- Stores
---------------------------------------------------------------------------
C.Loot = {}

-- How full a stocked container should end up, as a fraction of its capacity.
--
-- Containers are filled by weight, not by item count, because item count says
-- nothing about how full a container looks: a locker holds 40 units and a
-- microwave 5, so "eight items" is a heaped microwave and a nearly empty
-- locker. The capacity comes from the tile's own ContainerCapacity property,
-- read back off the object at build time, so every fitting the map editor
-- drops in gets stocked to the same lived-in level whatever size it is.
--
-- Slightly over a half: weight comes in coarse steps (a tin is 0.8 of the 40
-- a locker holds) and stopping at the first item past the line can otherwise
-- land just under it.
C.FillFraction = 0.55

-- Ceiling on the item count for one container, whatever the weight says.
-- Medical is mostly bandages and pills at 0.1 each, and half a locker of those
-- is two hundred items -- a full container by weight and an absurd one to look
-- at. Whichever limit is reached first stops the fill.
--
-- Set from the two lists that need the most items to reach the target: at 48
-- every container in the cabin makes FillFraction, and the heavy lists stop
-- on weight long before this binds. tests/test_stock.py holds it to the cap.
C.FillItemCap = 48

-- The ship's stores, and every id in them is the mod's own.
--
-- This is the refit's other half. Nineteen containers became eight, and five
-- of the eight -- the fridge, the oven, the two counters and the replicator's
-- berth -- are stocked with nothing at all: they are the player's shelves,
-- and a player fills a shuttle with vanilla loot within a week of flying it.
-- What the *ship* is issued with is Starfleet issue, so the three lockers
-- hold the mod's own items and no tins of beans. A locker of pistols and
-- bandages was what a 40-unit container needed when there were eight of them;
-- with three it is just the vanilla game, in a cupboard, on a spaceship.
--
-- The lists are short, so quantity is set by the entry's `cap` in
-- TREK_InteriorLayout.lua rather than left to weight: a cap that is a
-- multiple of the list length puts the same number of every item in whatever
-- the rolling cursor is doing, which makes the contents of a locker a
-- decision rather than an outcome. The `special` rules in TREK_Build.lua
-- guarantee the headline items on top of that and read the container back to
-- prove it.

-- Sick bay. The hypospray treats everything short of a bite, the dermal
-- regenerator closes skin, and the two tricorders are the diagnosis and the
-- sensor sweep. The forward locker also stocks one of each outright
-- (`special = "medkit"`), so a fresh ship always has the set aboard even if
-- the fill goes wrong.
C.Loot.medical = {
    "TrekShuttle.TrekHypospray", "TrekShuttle.TrekDermalRegen",
    "TrekShuttle.TrekMedTricorder", "TrekShuttle.TrekTricorder",
}

-- The rations locker: the galley dishes and the drinks together, because the
-- ship has one food locker now and a crew that keeps bloodwine keeps it with
-- the rations. Each drink is a vessel carrying its own fluid, filled when the
-- item is created (InitialPercentMin/Max in trekshuttle.txt), so what is
-- stocked is a full mug or a full bottle rather than empty glass.
C.Loot.food = {
    "TrekShuttle.TrekRationPack", "TrekShuttle.TrekGagh",
    "TrekShuttle.TrekLeolaStew", "TrekShuttle.TrekPlomeekSoup",
    "TrekShuttle.TrekJumjaStick",
    "TrekShuttle.TrekRaktajinoMug", "TrekShuttle.TrekEarlGreyCup",
    "TrekShuttle.TrekRomulanAle", "TrekShuttle.TrekBloodwine",
}

-- The armoury. The phasers are guaranteed separately (`special = "phasers"`),
-- so this is the blade rack -- all four together, because a crew who keep a
-- bat'leth keep the rest of the set and one alien weapon among the pistols
-- read as a souvenir where four read as an armoury. There are no pistols now.
C.Loot.weapons = {
    "TrekShuttle.TrekBatleth", "TrekShuttle.TrekMekleth",
    "TrekShuttle.TrekLirpa", "TrekShuttle.TrekUshaanTor",
}

return C
