--[[ Shuttlecraft -- the Borg among the dead (BORG.md).

    The horde is a Founder virus and Borg nanoprobes grafted together (LORE.md,
    "A horde is a Collective with no Queen"). In a few of the dead the
    nanoprobes went on building. They are two outfits, generated by
    tools/gen_borg.py: an assimilated civilian and a finished drone.

    **Almost none of it is code.** An outfit is chosen by the server when a
    zombie is made, from vanilla's ZombiesZoneDefinition.Default, and the
    outfit id rides the zombie's own packet, so every client dresses it from
    the clothing definitions with nothing from this mod (CREW.md: a zombie's
    packet carries its outfit id and nothing more). This file does two things:

      * **puts the two outfits in the table**, at the sandbox's share
        (`TrekShuttle.Borg`), in every process -- the table is read by the
        engine once, at its first pick, and it is plain shared data;
      * **gives them their walk**, in every process that updates a zombie: the
        walk type `TrekBorg` and the variable `TrekBorg`, which the nodes in
        common/media/AnimSets/zombie/ match. It is decided from the outfit's
        name, which every machine already has, so nothing is sent.

    The outfit is read with `IsoZombie.getOutfitName()`, and only once
    `shouldDressInRandomOutfit()` is false: before that the getter dresses
    the zombie itself (bytecode, bci 0-11), and on a client that would be a
    random outfit of its own choosing rather than the server's.
]]

require "TREK/TREK_Config"
require "TREK/TREK_Util"

TREK = TREK or {}
local C = TREK.Config
local U = TREK.Util

local B = {}
TREK.Borg = B

---------------------------------------------------------------------------
-- How many
---------------------------------------------------------------------------
--- The sandbox's scale on the two chances: 1 as police, 2 scarce, 3 common,
--- 4 none.
function B.scale()
    local ok, v = pcall(function() return SandboxVars.TrekShuttle and SandboxVars.TrekShuttle.Borg end)
    v = ok and tonumber(v) or 1
    return C.BorgScale[v] or C.BorgScale[1]
end

B.entries = {
    drone = { name = C.BorgDrone, chance = C.BorgDroneChance },
    assimilated = { name = C.BorgAssimilated, chance = C.BorgAssimilatedChance },
}

--- Puts both entries in the Default table (once) at the sandbox's share. The
--- entries are tables the engine reads by reference at its first pick, so
--- setting their chance again before then is enough.
function B.apply(quiet)
    local k = B.scale()
    B.entries.drone.chance = C.BorgDroneChance * k
    B.entries.assimilated.chance = C.BorgAssimilatedChance * k
    local list = ZombiesZoneDefinition and ZombiesZoneDefinition.Default
    if type(list) ~= "table" then
        if quiet then return false end
        U.warnOnce("borg.table", "ZombiesZoneDefinition.Default is missing: no Borg will spawn")
        return false
    end
    if not B.added then
        table.insert(list, B.entries.drone)
        table.insert(list, B.entries.assimilated)
        B.added = true
    end
    return true
end

-- Now, if vanilla's table is already loaded (a mod's shared Lua loads after
-- the game's), and again when the world's data is, which is after the sandbox
-- is known and before the first zombie is dressed.
B.apply(true)
Events.OnInitGlobalModData.Add(function()
    if B.apply() then
        U.log("borg: %s drones and %s assimilated in vanilla's Default outfits (sandbox scale %s)",
            tostring(B.entries.drone.chance), tostring(B.entries.assimilated.chance), tostring(B.scale()))
    end
end)

---------------------------------------------------------------------------
-- Knowing one, and its walk
---------------------------------------------------------------------------
--- True for either Borg outfit's name.
function B.isBorgOutfit(name)
    return name == C.BorgDrone or name == C.BorgAssimilated
end

-- Per zombie object, what it was last seen to be, keyed on its persistent
-- outfit id: the engine recycles IsoZombie objects, and one reused for an
-- ordinary zombie has to lose the walk. Weak, so a dropped zombie takes its
-- row with it.
local known = setmetatable({}, { __mode = "k" })
local KNOWN_ID, KNOWN_BORG = 1, 2

--- Decides, and keeps, whether this zombie is a Borg. Nil while it cannot be
--- told yet (not dressed on this machine).
function B.isBorg(z)
    local id = z:getPersistentOutfitID()
    local row = known[z]
    if row and row[KNOWN_ID] == id then return row[KNOWN_BORG] end
    if z:shouldDressInRandomOutfit() then return nil end
    local name = z:getOutfitName()
    if name == nil then return nil end
    local borg = B.isBorgOutfit(name)
    if row and row[KNOWN_BORG] and not borg then
        z:setVariable(C.BorgVariable, false)
    end
    known[z] = { id, borg }
    return borg
end

function B.update(z)
    if not B.isBorg(z) or z:isCrawling() then return end
    z:setWalkType(C.BorgWalkType)
    z:setVariable(C.BorgVariable, true)
end

-- Every zombie, every tick, so no closure and no table per call: a failure
-- is logged once and the hook stops trying.
local broken = false
Events.OnZombieUpdate.Add(function(z)
    if broken then return end
    local ok, err = pcall(B.update, z)
    if not ok then
        broken = true
        U.warnOnce("borg.update", tostring(err))
    end
end)

return B
