--[[ Shuttlecraft -- shared configuration.

    Everything the mod hard-codes about the world lives here: where the cabin
    is parked, how it is laid out, which sprites dress it, how much ground the
    hull needs before it will set down, and what is stocked into the lockers.

    Sprite names come from media/newtiledefinitions.tiles.txt and item ids
    from media/scripts/generated/items/, both for build 42.20. A wrong name
    fails *silently* in game -- the square is simply empty -- so every one of
    them is checked by tests/test_assets.py before the game is ever launched.
]]

TREK = TREK or {}

local C = {}
TREK.Config = C

C.Version   = "1.3.0"
-- The key predates multiplayer and is kept so single-player saves carry over;
-- the table inside is migrated by U.state() (schema 2).
C.StateKey  = "TREK_State_v1"
C.ModPrefix = "[TREK]"

-- Bumped whenever the cabin needs rebuilding to pick up changes to the way it
-- is generated. A cabin built at an older revision is quietly brought up to
-- date the next time the player is aboard; the rebuild preserves furniture,
-- stored items and anything dropped on the deck.
C.BuildRev = 10

-- Flip to true for verbose build logging in console.txt.
C.Debug = false

-- Design-time only. Normally a rebuild leaves every container exactly as the
-- player left it -- a ship in play is meant to be lived in, and what gets
-- eaten stays eaten. With this on a rebuild restocks as well, which is what
-- you want while iterating on loot lists and never want in a world somebody
-- is playing. TREK_Rebuild() turns it on for one rebuild instead.
C.DevRestock = false

---------------------------------------------------------------------------
-- Where the cabin lives
---------------------------------------------------------------------------
-- Build 42 cells are 256 squares and vanilla ships cells out to x=77. The
-- Fifth-Wheel RV interior squats on cell 85,40 and the TARDIS mod, if it is
-- also installed, runs from cell 92,40 east across six deck footprints. Cell
-- 96,40 clears all three, and its y stays under 12000 so it also falls
-- outside the unbounded exit-menu test Project RV Interior applies.
C.InteriorCell = { x = 96, y = 40 }

-- The mod's map folder (media/maps/TrekShuttle): empty map cells around the
-- interior cell, so the world generator never grows grass, trees or zombies
-- there and the space outside the cabin is black. Generated by
-- tools/gen_void_map.py. Single player and the in-game Host settings add it
-- by themselves; a dedicated server lists it in its Map= setting.
C.VoidMap = "TrekShuttle"

-- Offset of the cabin inside that cell, so nothing touches a cell edge; chunk
-- seams make edge squares awkward to generate reliably.
C.RoomOffset = 16

-- The cabin is one compartment on one storey. There is no deck stack, so
-- none of the TARDIS's sideways-stepping is needed -- but the reason for it
-- still applies and is worth keeping in mind before adding a second level:
-- Project Zomboid draws every z level above the player and only hides what is
-- overhead when it believes you are inside a building, which means RoomDef
-- metadata baked into a map lotheader that runtime squares cannot have. A
-- deck above this one would be drawn straight over it.
C.CabinZ = 4

-- Cabin extent, as inclusive offsets: 0..CabinW across, 0..CabinL fore-aft.
-- oy 0 is the bow. A shuttle is a small ship and this is deliberately a small
-- room -- roomy enough for a galley, a berth, a med station and real cargo,
-- and nothing like a TARDIS deck.
C.CabinW = 5
C.CabinL = 8

-- How far beyond the hull to strip the procedural wilderness the engine grows
-- in unmapped cells. Everything in this ring is removed down to bare nothing,
-- which renders as the black void the Fifth-Wheel RV interior sits in.
C.ClearMargin = 24

-- The transporter pad, amidships and aft of the galley. Arrivals -- beaming
-- up, walking in through the hatch, coming back from a failed landing -- all
-- put the player down here, and the pad and the ring of squares around it are
-- refused by every placement helper so nothing is ever in the way.
C.Landing = { x = 2, y = 6, clearance = 0 }

--- True for the pad square and the ring of squares around it.
function C.isLanding(ox, oy)
    return math.abs(ox - C.Landing.x) <= C.Landing.clearance
       and math.abs(oy - C.Landing.y) <= C.Landing.clearance
end

-- Deckhead lighting. The server places the fittings; each client hangs the
-- light itself, because a light source is not a synced world object.
-- tests/test_layout.py checks these offsets against the floor plan.
C.LampSpots = {
    { 3, 1 }, { 2, 3 }, { 3, 6 },
}

---------------------------------------------------------------------------
-- Hull shape
---------------------------------------------------------------------------
-- Project Zomboid has no diagonal wall sprites -- a wall only ever sits on
-- the north or west edge of a square -- so a smoothly curved hull is not
-- available at any size. What is available is a stepped chamfer, and at the
-- game's camera angle a bow cut back six squares reads clearly as a nose.
--
-- NoseCut is how far the bow is pinched in, TailCut the same at the stern.
-- Bigger noses are pointier; past about half of CabinW the bow stops being
-- wide enough to stand in.
C.NoseCut = 0
C.TailCut = 0

--- True when an offset is inside the cabin floor plan.
---
--- Walls are derived from this rather than hard-coded, so changing the cuts
--- reshapes the hull and its walls together and nothing else needs touching.
function C.inShape(ox, oy, w, l, nose, tail)
    w = w or C.CabinW
    l = l or C.CabinL
    nose = nose or C.NoseCut
    tail = tail or C.TailCut
    if ox < 0 or oy < 0 or ox > w or oy > l then return false end
    -- cut a right triangle off each corner: a deeper cut forward than aft,
    -- which is what makes it read as a bow rather than a lozenge
    if (ox + oy) < nose then return false end
    if ((w - ox) + oy) < nose then return false end
    if (ox + (l - oy)) < tail then return false end
    if ((w - ox) + (l - oy)) < tail then return false end
    return true
end

---------------------------------------------------------------------------
-- The hull outside
---------------------------------------------------------------------------
-- How much clear ground the shuttle needs before it will set down, in
-- squares, centred on the square being asked about. This is the whole
-- difference between calling this ship down and materialising a police box:
-- a box needs one tile and can appear in a hallway, and a shuttle needs a
-- street or a field.
--
-- Kept in step by hand with HULL_W / HULL_L in tools/gen_shuttle.py, which is
-- how big the model is actually drawn. Nothing in the engine ties the two
-- together -- a world model is drawn from one square and simply overhangs the
-- rest -- so if you change one, change the other.
C.Footprint = { w = 3, h = 5 }

--- Every offset the hull covers, relative to the square it is anchored on.
--- Even-sided footprints are biased to the north-west, which is the corner
--- the isometric camera shows least of.
---
--- Built once and handed back. This is walked inside the landing search,
--- which examines thousands of candidate squares in a single pass, and
--- rebuilding a fifteen-entry table for each of them is pure garbage.
local footprint = nil

function C.footprintOffsets()
    if footprint then return footprint end
    local out = {}
    local hw = math.floor((C.Footprint.w - 1) / 2)
    local hh = math.floor((C.Footprint.h - 1) / 2)
    for dx = -hw, C.Footprint.w - 1 - hw do
        for dy = -hh, C.Footprint.h - 1 - hh do
            table.insert(out, { dx, dy })
        end
    end
    footprint = out
    return out
end

-- Radius, in tiles, of the field that holds the dead back from the hatch.
C.FieldRadius = 10

-- Whether a new world starts with the shields up. They can be lowered and
-- raised from the helm; there is deliberately no radius control, only the
-- state. The setting is saved with the world, so this is only the default.
C.ShieldsDefault = true

---------------------------------------------------------------------------
-- The transporter
---------------------------------------------------------------------------
-- Beaming is the shuttle's own trick and is deliberately not gated on the
-- ship being anywhere in particular: when it is not sitting on the ground it
-- is overhead, and the pad reaches you either way.
--
-- The delay is flavour with a purpose -- an instant snap reads as a debug
-- teleport, and a second and a half of dematerialising reads as a transporter
-- and gives the halo note time to be seen. Ticks.
C.BeamDelay = 90

-- How far a beam-down may miss by when the exact square is occupied.
C.BeamScatter = 6

-- Transporter charges. On a server whose speed anti-cheat kicks or bans
-- (AntiCheatSpeed 1 or 2), every long move of a character is one strike and
-- four uncleared strikes remove the player; one strike clears every 150
-- seconds. So each player gets that budget as charges, and the fourth beam is
-- refused in lore ("recharging") instead of the server kicking them. Single
-- player, and servers that only log or ignore the check, are unlimited.
C.TransporterCharges       = 3
C.TransporterRechargeSecs  = 150

---------------------------------------------------------------------------
-- Flight: the sky plane
---------------------------------------------------------------------------
-- The shuttle flies by *driving*, on an invisible floor the mod lays at
-- altitude. This is not a flourish, it is the only thing build 42 allows.
--
-- BaseVehicle.update() sets a vehicle's z to 0 every single tick, and then
-- puts it back to its physics level only if a floor tile exists under the
-- vehicle's centre square at that level (or the one below). Everything that
-- matters reads that clamped z: the render camera, where the occupants are
-- drawn, isIntersectingSquare, breakingObjects/damageObjects, and -- on every
-- other player's machine -- clientUpdateVehiclePos, which writes setZ(0)
-- outright. Lifting the physics body alone therefore gives a ship that flies
-- in the physics engine and sits on the ground in the game, ploughing through
-- fences as it goes. That was tried on paper and disproved from the bytecode
-- before a line of it was written (PILOTING.md section 5.1).
--
-- Put a floor there and the whole problem dissolves: the z is legitimate, so
-- the ship and its crew are drawn in the air; collision resolves at the flight
-- level, so it passes over a two-storey building instead of demolishing it;
-- the wheels have something to rest on, so the engine's own physics drives it
-- and no part of this mod has to fight gravity; and because the floor holds
-- the ship up, nothing falls out of the sky when the pilot leaves the seat.
--
-- The tile is vanilla. invisible_01_0's only two properties are attachedFloor
-- and solidfloor: a floor that is solid and cannot be seen.
C.SkyTile = "invisible_01_0"

-- Bullet units per z level, read straight out of BaseVehicle.setDebugZ's
-- bytecode: it computes fastfloor(origin.y / 2.4494900703430176). Three times
-- 0.8164966702461243 is the same number; both constants are in that method.
C.LevelUnits = 2.4494900703430176

-- How far around the ship the plane extends, in squares.
--
-- Deliberately small, and it was not always. A floor is a floor: the engine
-- treats everything under one as being indoors and stops drawing the ground
-- below it, so a wide plane put a disc of blackness around the ship and hid
-- the very world she was flying over. Seen in game, 2026-09-17 -- "I can see
-- the world but near me is a sphere of blackness."
--
-- The hull is 3 by 5, so 2 squares out is a 5 by 5 patch: the smallest that
-- still covers her at any heading and gives the wheels something under them.
--
-- This is the only real lever on the darkness. A floor darkens whatever is
-- beneath it and nothing can stop that, so the patch has to be small enough
-- that the hull is drawn over it. It was 16, then 4, then 3, and at 3 with a
-- square of margin the kept area was a 9 by 9 box -- 81 squares of shadow
-- around a hull that covers 15, which is the "trailing dark blotch". 5 by 5 is
-- 25 against the hull's 15, so what is left is a one-square rim under her
-- rather than a wake behind her.
C.SkyRadius = 2

-- No margin at all: a square is lifted the moment she is not over it. The
-- margin existed so she was never chasing her own floor, but the paver
-- recentres every tick and lays the centre square first, so there is nothing
-- to chase -- and every square of margin is a square of shadow trailing her.
C.SkyTrailMargin = 0

-- How far around a player to hunt for invisible floors nobody is using, in
-- squares. Much larger than the patch, because this is not about the plane the
-- ship is flying on -- it is about the ones it left behind.
--
-- A floor is a world object and world objects are saved. Every build of this
-- feature that laid a wider plane, or trimmed it less eagerly, left its floors
-- in whatever world it was tested in, and they are still there: a black
-- blotch across a car park, seen in a screenshot after the plane itself was
-- already down to 25 squares. The ship's own record only remembers the last
-- flight, so the only way to clear the rest is to go and look.
C.SkyCleanRadius = 32

-- How far a player must move before that area is swept again. There is no
-- timer besides this: ground that has been swept has nothing left to find, and
-- ground that has not should not be made to wait.
C.SkyCleanStride = 20

-- Squares paved per tick. The plane is laid the way the landing search is
-- walked -- a cursor and a slice -- because a thousand addFloor calls in one
-- frame is not slow, it is the hard lock described in DEV_GUIDE.md under
-- "Slice any search that touches thousands of squares".
C.SkyTilesPerTick = 96

-- A ceiling on the plane, so a long flight cannot grow the list without
-- bound. Past this the squares furthest behind the ship are lifted first.
C.SkyMaxTiles = 40000

-- Cruising height, and the levels the pilot may climb and dive between. Level
-- 0 is the ground and is never paved -- a floor laid there would be a floor
-- laid on Kentucky. Three clears a two-storey building with room to spare.
C.FlightCruise   = 3
C.FlightMinLevel = 1

-- One level above the cruise and no more. Higher was offered and was not worth
-- having: the levels above this are past the height the world has any geometry
-- at, the ship has nothing to be "over" up there, and every trip that far up
-- ended badly. Kept as cruise + 1 rather than a bare number so the two cannot
-- drift apart.
C.FlightMaxLevel = 4

-- Ticks to wait for the engine to accept a level before giving up on the lift.
C.FlightLiftTicks = 60

-- Degrees of pitch or roll tolerated before she is levelled off again. She
-- rests on an invisible floor with real physics running, and a 1200kg box on a
-- one-tile-thick shelf will tip if it is nudged -- she went over backwards in
-- game. flipUpright touches only the rotation, never the height.
C.FlightLevelTolerance = 4

-- The helm's flight speeds, as the vehicle's own top speed in the units
-- setMaxSpeed takes (the shuttle's script sets 70 on the ground).
--
-- Absolute figures, not multipliers, and that is a correction. They were
-- multipliers of a base of 30, capped at 0.6 of the server's SpeedLimit of
-- 70 -- which is 42, so the top three steps all clamped to exactly the same
-- number and the control appeared to do nothing at all. Anything the pilot can
-- pick must be distinguishable from its neighbours or it is not a control.
C.FlightSpeedSteps       = { 15, 30, 50, 70, 95, 120 }
C.FlightSpeedDefaultStep = 3

-- On a server the vehicle speed limiter is the server owner's business, so the
-- choice is capped by it. In single player there is nobody to protect and no
-- anti-cheat to trip, so the pilot gets the whole range.
C.FlightSpeedCapFraction = 1.0

-- Consecutive server checks with no pilot in the driver's seat before the
-- ship is brought down by itself. A ship left parked in the sky by somebody's
-- disconnect would otherwise stay there for the life of the world.
C.FlightPilotGrace = 5

---------------------------------------------------------------------------
-- Travel
---------------------------------------------------------------------------
-- Travel is also by the helm: lay in a course, then take her down. That is
-- the way to cross the map; flight above is the way to fly it by hand.
C.MaxBookmarks        = 40
C.MaxBookmarkName     = 40   -- characters; a name is sent to the server
C.LandingSearchRadius = 24   -- squares to spiral out from a chosen site

-- How long to keep trying to set down at a destination before giving up and
-- beaming the player back aboard. Ticks; the first few hundred are spent
-- waiting for the area to stream in at all.
C.LandingTimeout = 420

---------------------------------------------------------------------------
-- Phasers
---------------------------------------------------------------------------
-- Two names for one item: the engine's inventory search compares the bare
-- type, while anything that spawns or places the item wants the full id.
C.PhaserItem = "TrekShuttle.TrekPhaser"
C.PhaserType = "TrekPhaser"

-- A phaser never runs out, never jams and never wears out. TREK_Phaser.lua
-- tops up every one the player is carrying on a slow tick; these are the
-- three things it puts back.
C.PhaserInfiniteAmmo = true
C.PhaserNeverJams    = true
C.PhaserNeverWears   = true

-- How often to top a carried phaser up, in ticks. It only has to beat the
-- rate a player can empty a magazine, so this is deliberately slow.
C.PhaserInterval = 30

-- The locker they are kept in, just off the transporter pad, and how many are
-- in it.
C.PhaserRack  = { x = 5, y = 6 }
C.PhaserCount = 4

---------------------------------------------------------------------------
-- Sprites
---------------------------------------------------------------------------
-- Facing keys name the wall an object stands against, which is also the way
-- it looks into the room. A sprite whose set has fewer than four facings only
-- lists the ones that exist, and the placement helpers fall back to S.
C.Sprites = {
    -- Hull: industry_01 is a light-metal wall set, which is as close to a
    -- ship's bulkhead as build 42 ships. Index 0 is the west face, 1 the
    -- north face, 2 the corner post -- the same layout every wall set uses.
    wallW = "industry_01_0",
    wallN = "industry_01_1",
    wallC = "industry_01_2",

    deckFloor = "floors_interior_tilesandwood_01_0",  -- solid deck
    padFloor  = "floors_interior_tilesandwood_01_1",  -- solid transporter tile

    lamp   = { S = "lighting_indoor_01_32", E = "lighting_indoor_01_8",
               W = "lighting_indoor_01_40", N = "lighting_indoor_01_48" },

    sink   = { N = "fixtures_sinks_01_0", E = "fixtures_sinks_01_1",
               S = "fixtures_sinks_01_2", W = "fixtures_sinks_01_3" },
    toilet = { S = "fixtures_bathroom_01_0", E = "fixtures_bathroom_01_1",
               W = "fixtures_bathroom_01_2", N = "fixtures_bathroom_01_3" },
    shower = { N = "fixtures_bathroom_01_22", W = "fixtures_bathroom_01_23" },

    -- Steel counters rather than the wooden kitchen sets: this is a galley in
    -- a metal hull, not somebody's kitchen.
    counter = { N = "fixtures_counters_01_33", E = "fixtures_counters_01_35",
                S = "fixtures_counters_01_37", W = "fixtures_counters_01_39" },
    fridge  = { S = "appliances_refrigeration_01_0", E = "appliances_refrigeration_01_1",
                N = "appliances_refrigeration_01_2", W = "appliances_refrigeration_01_3" },
    oven    = { E = "appliances_cooking_01_0", S = "appliances_cooking_01_1",
                W = "appliances_cooking_01_2", N = "appliances_cooking_01_3" },
    microwave = { S = "appliances_cooking_01_25", E = "appliances_cooking_01_24",
                  W = "appliances_cooking_01_26", N = "appliances_cooking_01_27" },

    metalShelf = { S = "furniture_shelving_01_28", E = "furniture_shelving_01_29",
                   W = "furniture_shelving_01_30", N = "furniture_shelving_01_31" },
    locker     = { S = "furniture_storage_02_8", E = "furniture_storage_02_9",
                   N = "furniture_storage_02_10", W = "furniture_storage_02_11" },
    crate      = "location_military_generic_01_0",
    chair      = { E = "furniture_seating_indoor_01_8", S = "furniture_seating_indoor_01_9",
                   W = "furniture_seating_indoor_01_10", N = "furniture_seating_indoor_01_11" },

    -- The cockpit. security_01 "Terminal" is a floor-standing console and
    -- security_01_4/5 a bank of wall-mounted screens, which between them read
    -- as a helm without a single custom tile.
    terminal = { S = "security_01_0", E = "security_01_1",
                 N = "security_01_2", W = "security_01_3" },
    monitors = { S = "security_01_4", E = "security_01_5" },
    computer = { S = "appliances_com_01_72", E = "appliances_com_01_73",
                 N = "appliances_com_01_74", W = "appliances_com_01_75" },

    -- Sick bay. The wide medical cabinet holds thirty, which is what makes a
    -- "large container of medical supplies" actually large.
    medCabinet = { E = "location_community_medical_01_152",
                   S = "location_community_medical_01_154",
                   N = "location_community_medical_01_238",
                   W = "location_community_medical_01_246" },
    medDrawers = { E = "location_community_medical_01_36",
                   S = "location_community_medical_01_37",
                   W = "location_community_medical_01_38",
                   N = "location_community_medical_01_39" },
}

---------------------------------------------------------------------------
-- Multi-tile furniture
---------------------------------------------------------------------------
-- A bed covers more than one square and which half goes where is not
-- guessable: it comes from the tileset's SpriteGridPos property, given here
-- as {sprite, dx, dy}. Getting it backwards lays the foot of the bed where
-- its head belongs, which is invisible in the code and obvious in game.
-- tests/test_layout.py checks every offset here against the game data.
C.Pieces = {
    bunkS   = { { "furniture_bedding_01_9", 0, 0 }, { "furniture_bedding_01_8", 0, 1 } },
    biobedS = { { "location_community_medical_01_17", 0, 0 },
                { "location_community_medical_01_16", 0, 1 } },
}

---------------------------------------------------------------------------
-- Water
---------------------------------------------------------------------------
-- Which layout tags are plumbed. Anything tagged one of these is kept full,
-- so adding a fixture in BuildingEd needs no code change -- only the tag.
C.WaterTags = { sink = true, shower = true, toilet = true }

-- The ship makes its own water, so the fixtures are topped up rather than
-- piped. This matters more than it sounds: the sink sprites carry the
-- vanilla `waterPiped` property, which feeds them from the town mains, and
-- the mains shut off a few weeks into any world. A shuttle whose tap stops
-- working the same week Louisville's does is not much of a shuttle.
--
-- Ticks between top-ups while somebody is aboard. The ten-minute timer keeps
-- it full when nobody is; this makes it impossible to drain in front of you.
C.WaterInterval = 120

-- How much each plumbed fixture holds, in litres. A runtime sink has no water
-- store of its own, so the server gives it one this size (vanilla's own
-- addWaterContainer command does exactly this) and keeps it topped up.
C.WaterCapacity = 20

---------------------------------------------------------------------------
-- Items placed in the cabin
---------------------------------------------------------------------------
-- The hull outside and the helm console inside are world models, defined in
-- media/scripts/trekshuttle.txt.
C.ExteriorItem = "TrekShuttle.TrekShuttleHull"
C.HelmItem     = "TrekShuttle.TrekHelmConsole"

---------------------------------------------------------------------------
-- Stores
---------------------------------------------------------------------------
C.Loot = {}

-- How full a stocked container should end up, as a fraction of its capacity.
--
-- Containers are filled by weight, not by item count, because item count says
-- nothing about how full a container looks: a locker holds 40 units and a
-- microwave 5, so "eight items" is a heaped microwave and a nearly empty
-- locker. The capacity comes from the tile's own ContainerCapacity property,
-- read back off the object at build time, so every fitting the map editor
-- drops in gets stocked to the same lived-in level whatever size it is.
--
-- Slightly over a half: weight comes in coarse steps (a tin is 0.8 of the 40
-- a locker holds) and stopping at the first item past the line can otherwise
-- land just under it.
C.FillFraction = 0.55

-- Ceiling on the item count for one container, whatever the weight says.
-- Medical is mostly bandages and pills at 0.1 each, and half a locker of those
-- is two hundred items -- a full container by weight and an absurd one to look
-- at. Whichever limit is reached first stops the fill.
--
-- Set from the two lists that need the most items to reach the target: at 48
-- every container in the cabin makes FillFraction, and the heavy lists stop
-- on weight long before this binds. tests/test_stock.py holds it to the cap.
C.FillItemCap = 48

-- Sick bay. Deliberately long: the fill walks a list with a rolling cursor,
-- so a longer list spreads further across the cabinets rather than repeating.
--
-- The order is not arbitrary and the boxes are not padding. Containers fill
-- by weight, and medical supplies are the lightest loot in the game -- a
-- bandage is 0.1 of the 40 a locker holds, so a list of nothing but dressings
-- and pills cannot fill a locker at any sane item count. Every third or
-- fourth entry is therefore something substantial (a box, a kit, a splint),
-- which is both what carries the cabinet to a believable fill and what a
-- ship's sick bay would actually be stocked with.
C.Loot.medical = {
    "Base.FirstAidKit", "Base.Bandage", "Base.Antibiotics", "Base.Disinfectant",
    "Base.BandageBox", "Base.AlcoholWipes", "Base.AlcoholBandage", "Base.Pills",
    "Base.AdhesiveBandageBox", "Base.PillsAntiDep", "Base.PillsBeta",
    "Base.PillsVitamins", "Base.Bag_MedicalBag", "Base.SutureNeedle",
    "Base.SutureNeedleHolder", "Base.PillsSleepingTablets",
    "Base.CottonBallsBox", "Base.Tweezers", "Base.Scalpel",
    "Base.WaterPurificationTablets", "Base.Splint", "Base.Bleach",
    "Base.AdhesiveTapeBox", "Base.CottonBalls", "Base.HottieZ",
    "Base.AlcoholedCottonBalls", "Base.Sheet", "Base.Gloves_Surgical",
}

-- Ship's stores. Long-life first: this is what a shuttle is provisioned with,
-- not what somebody left in a fridge.
C.Loot.food = {
    "TrekShuttle.TrekRationPack",
    "Base.TinnedBeans", "Base.TinnedSoup", "Base.CannedCorn", "Base.CannedPeas",
    "Base.CannedCarrots", "Base.CannedPotato", "Base.CannedChili",
    "Base.CannedBolognese", "Base.CannedMushroomSoup", "Base.CannedTomato",
    "Base.CannedSardines", "Base.CannedFruitCocktail", "Base.CannedPeaches",
    "TrekShuttle.TrekRationPack", "TrekShuttle.TrekJumjaStick",
    "Base.Rice", "Base.Pasta", "Base.Flour2", "Base.Sugar", "Base.Salt",
    "Base.Coffee2", "Base.Crisps", "Base.GranolaBar", "Base.BeefJerky",
    "Base.WaterBottle", "Base.WaterRationCan",
}

-- The two galley fridges. Produce is light -- an apple is 0.2 of the 40 a
-- fridge holds -- so the same rule as the sick bay applies: the hams, the
-- pumpkin and the watermelon are what let a fridge look stocked without
-- putting eighty eggs in it.
C.Loot.fresh = {
    "TrekShuttle.TrekLeolaStew", "TrekShuttle.TrekGagh", "TrekShuttle.TrekPlomeekSoup",
    "Base.Ham", "Base.Bread", "Base.Cheese", "Base.Butter", "Base.Milk",
    "Base.Pumpkin", "Base.Egg", "Base.Potato", "Base.Carrots", "Base.Onion",
    "Base.Watermelon", "Base.Tomato", "Base.Apple", "Base.Orange",
    "Base.RoastingPan", "Base.Steak", "Base.Chicken", "Base.Bacon",
    "Base.Pie", "Base.Cabbage", "Base.Lettuce", "Base.BellPepper",
}

C.Loot.cookware = {
    "Base.Pot", "Base.Pan", "Base.Saucepan", "Base.Bowl", "Base.Plate",
    "Base.MugWhite", "Base.KitchenKnife", "Base.BreadKnife", "Base.ButterKnife",
    "Base.CheeseGrater", "Base.RollingPin", "Base.BakingTray",
}

-- Engineering stores: a shuttle carries a tool roll, not a workshop.
C.Loot.tools = {
    "Base.Screwdriver", "Base.Wrench", "Base.PipeWrench", "Base.Hammer",
    "Base.DuctTape", "Base.Rope", "Base.Torch", "Base.Battery",
    "Base.ElectronicsScrap", "Base.Extinguisher", "Base.Crowbar",
    "Base.Saw", "Base.Screws", "Base.Nails", "Base.Wire", "Base.SheetMetal",
}

C.Loot.linen = { "Base.Sheet", "Base.Pillow", "Base.Pillow_Crafted" }

-- The armoury, stowed beside the phasers. A phaser never runs dry, so this is
-- not there to be needed -- it is there because a weapons locker holding four
-- sidearms and nothing else reads as a prop rather than a locker. Heavy on
-- purpose: this is the list that carries the phaser locker to a believable
-- fill without putting thirty phasers in it.
C.Loot.weapons = {
    "Base.Pistol", "Base.Pistol2", "Base.Pistol3", "Base.Shotgun",
    "Base.Bullets9mmBox", "Base.9mmClip", "Base.ShotgunShellsBox",
    "Base.Bullets45Box", "Base.45Clip",
    "Base.HuntingKnife", "Base.Machete", "Base.Nightstick", "Base.HandAxe",
    "Base.Vest_BulletCivilian", "Base.HolsterSimple", "Base.Crowbar",
}

-- Crucial kit: what is worth more than its weight the moment the ship sets
-- down somewhere dark and the hatch opens.
C.Loot.survival = {
    "TrekShuttle.TrekRationPack", "TrekShuttle.TrekJumjaStick",
    "Base.Torch", "Base.Battery", "Base.Lighter", "Base.Matches",
    "Base.Rope", "Base.SheetRope", "Base.DuctTape", "Base.FirstAidKit",
    "Base.WaterRationCan", "Base.Extinguisher", "Base.Map",
    "Base.WalkieTalkie2", "Base.LightBulb", "Base.Bag_DuffelBag",
    "Base.Needle", "Base.Thread", "Base.Sheet", "Base.Pillow",
}

return C
