-- GENERATED by tools/gen_tapes.py -- do not edit by hand.
--
-- The ship's tape shelf. Every string here is a translation key;
-- the text is in Translate/EN/Recorded_Media.json and both files
-- come out of the generator together, because a key that does not
-- resolve prints itself on screen and a key used twice makes the
-- second line silently inert. See LORE.md.

-- Vanilla's shared/RecordedMedia/ISRecordedMedia.lua registers
-- everything in this table on OnInitRecordedMedia, so adding to it
-- is the whole of the integration. The handler at the bottom is
-- insurance against a load order where our table is filled after
-- vanilla has already walked it, and it registers only what the
-- engine does not already have -- registering an id twice is not
-- something the engine is known to survive.
RecMedia = RecMedia or {}

-- Ten Forward Talent Night
RecMedia["TREK_TalentNight"] = {
    itemDisplayName = "RM_TREK_TalentNight_name",
    title = "RM_TREK_TalentNight_title",
    subtitle = "RM_TREK_TalentNight_sub",
    author = "RM_TREK_TalentNight_author",
    extra = "RM_TREK_TalentNight_extra",
    spawning = 0,
    category = "Trek-VHS",
    lines = {
        { text = "RM_TREK_TalentNight_01", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_02", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_03", r = 1.00, g = 0.75, b = 0.00, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_04", r = 1.00, g = 0.75, b = 0.00, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_05", r = 1.00, g = 0.75, b = 0.00, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_06", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_07", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_08", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_09", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_10", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_11", r = 0.00, g = 0.69, b = 0.94, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_12", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_13", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_14", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_15", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_16", r = 0.00, g = 0.69, b = 0.94, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_17", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_18", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_19", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_20", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_21", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_22", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_23", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1,STS-0.2" },
        { text = "RM_TREK_TalentNight_24", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_25", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_26", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_27", r = 0.00, g = 0.69, b = 0.94, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_28", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_29", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1,STS-0.2,UHP-1" },
        { text = "RM_TREK_TalentNight_30", r = 0.00, g = 0.69, b = 0.94, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_31", r = 0.00, g = 0.69, b = 0.94, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_32", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_33", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_34", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_35", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_36", r = 0.00, g = 0.69, b = 0.94, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_37", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_38", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_39", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_40", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_41", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_42", r = 1.00, g = 0.75, b = 0.00, codes = "BOR-1" },
        { text = "RM_TREK_TalentNight_43", r = 1.00, g = 0.75, b = 0.00, codes = "BOR-1,UHP-1" },
    },
}

-- Dear Grandpa Tuvix
RecMedia["TREK_Tuvix"] = {
    itemDisplayName = "RM_TREK_Tuvix_name",
    title = "RM_TREK_Tuvix_title",
    subtitle = "RM_TREK_Tuvix_sub",
    author = "RM_TREK_Tuvix_author",
    extra = "RM_TREK_Tuvix_extra",
    spawning = 0,
    category = "Trek-VHS",
    lines = {
        { text = "RM_TREK_Tuvix_01", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_02", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_03", r = 1.00, g = 0.75, b = 0.00, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_04", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_05", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_06", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_07", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_08", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_09", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_10", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_11", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_12", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_13", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_14", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_15", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_16", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_17", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_18", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_19", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_20", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_21", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_22", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_23", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_24", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_25", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1,STS-0.2" },
        { text = "RM_TREK_Tuvix_26", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_27", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_28", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_29", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_30", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_31", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_32", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_33", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_34", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_35", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_36", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1,UHP-1" },
        { text = "RM_TREK_Tuvix_37", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_38", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_39", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_40", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_41", r = 0.44, g = 0.19, b = 0.63, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_42", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_43", r = 0.00, g = 0.69, b = 0.31, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_44", r = 1.00, g = 1.00, b = 1.00, codes = "BOR-1" },
        { text = "RM_TREK_Tuvix_45", r = 1.00, g = 0.75, b = 0.00, codes = "BOR-1,UHP-1" },
    },
}

-- The ids the ship is issued with, in shelf order. TREK_Build
-- reads this to stock the tape shelf, so a tape added above
-- reaches the shelf without a second list to keep in step.
TREK_TapeIds = {
    "TREK_TalentNight",
    "TREK_Tuvix",
}

Events.OnInitRecordedMedia.Add(function(rc)
    if not rc then return end
    for _, id in ipairs(TREK_TapeIds) do
        local known = nil
        local ok = pcall(function() known = rc:getMediaData(id) end)
        if ok and not known then
            local v = RecMedia[id]
            if v then
                local data = rc:register(v.category, id,
                                         v.itemDisplayName, v.spawning or 0)
                if data then
                    if v.title then data:setTitle(v.title) end
                    if v.subtitle then data:setSubtitle(v.subtitle) end
                    if v.author then data:setAuthor(v.author) end
                    if v.extra then data:setExtra(v.extra) end
                    for _, j in ipairs(v.lines) do
                        data:addLine(j.text, j.r, j.g, j.b, j.codes)
                    end
                end
            end
        end
    end
end)
