--[[ Shuttlecraft -- the Adirondack channel: its record, and how to read it
    (COMMS.md, PADD.md 12).

    Shared, and read-only everywhere but the authority. The server walks the
    tree and writes these tables (server/TREK/TREK_CommsServer.lua); every
    client holds the copy the server last published and renders from it.

    **Two keys, for two sizes of table.**

      * C.CommsKey is the **live channel** -- the call, the flags, what has
        fired. It is published on every choice a player makes, so it holds
        nothing that grows: a call's own steps, and counters.
      * C.CommsLogKey is the **history** -- one row per finished call. It is
        published when a call ends and never inside one. A row is node ids and
        option numbers; the words are rendered from the generated tree at
        display time (PADD.md 12.2), so a line fixed in the generator is fixed
        in every transcript, and no rendered text is ever stored or sent.

    The tree itself is `TREK_CommsTree`, generated by tools/gen_comms.py
    along with every string it names.
]]

require "TREK/TREK_Config"
require "TREK/TREK_Util"
require "TREK/TREK_CommsTree"

TREK = TREK or {}
local C = TREK.Config
local U = TREK.Util

local Cm = {}
TREK.Comms = Cm

Cm.listeners = {}

--- The generated tree. A function rather than a field, so a test can swap
--- the tree for one written to exercise a single edge.
function Cm.tree()
    return TREK_CommsTree
end

---------------------------------------------------------------------------
-- The stores
---------------------------------------------------------------------------
--- The live channel. On the authority the fields are filled in; on a client
--- this is whatever the server last sent and is never repaired here.
function Cm.store()
    local d = ModData.getOrCreate(C.CommsKey)
    if isClient() then
        d.flags = d.flags or {}
        return d
    end
    d.serial = tonumber(d.serial) or 0
    d.flags = d.flags or {}
    d.fired = d.fired or {}
    d.misses = d.misses or {}
    d.lastAt = d.lastAt or {}
    d.retryAt = d.retryAt or {}
    d.rescued = tonumber(d.rescued) or 0
    d.lost = tonumber(d.lost) or 0
    d.issued = d.issued or {}
    d.pendingTapes = d.pendingTapes or {}
    d.converted = d.converted or {}
    return d
end

--- The history: `rows`, oldest first.
function Cm.log()
    local d = ModData.getOrCreate(C.CommsLogKey)
    d.rows = d.rows or {}
    return d
end

function Cm.call()
    return Cm.store().call
end

function Cm.onChange(fn)
    table.insert(Cm.listeners, fn)
end

function Cm.notify()
    for _, fn in ipairs(Cm.listeners) do U.try("commsListener", fn) end
end

--- Publishes the live channel. Authority only.
function Cm.publish()
    if isClient() then
        U.warnOnce("commsOnClient", "a client tried to publish the channel; ignored")
        return
    end
    if isServer() then
        U.try("transmitComms", function() ModData.transmit(C.CommsKey) end)
    end
    Cm.notify()
end

--- Publishes the history. Authority only, and only when a call ends.
function Cm.publishLog()
    if isClient() then return end
    if isServer() then
        U.try("transmitCommsLog", function() ModData.transmit(C.CommsLogKey) end)
    end
    Cm.notify()
end

Events.OnInitGlobalModData.Add(function()
    if not isClient() then return end
    U.try("requestComms", function()
        ModData.request(C.CommsKey)
        ModData.request(C.CommsLogKey)
    end)
end)

Events.OnReceiveGlobalModData.Add(function(key, data)
    if key ~= C.CommsKey and key ~= C.CommsLogKey then return end
    if not isClient() or type(data) ~= "table" then return end
    ModData.add(key, data)
    Cm.notify()
end)

---------------------------------------------------------------------------
-- Day zero
---------------------------------------------------------------------------
--- Days since the ship was commissioned, or nil before that.
---
--- **Commissioned means first boarded**, for now: the first time the cabin
--- was built. ROADMAP2 1.6's cold start will change what sets `day0` and
--- nothing that reads it (COMMS.md 4: "two weeks later" has to mean two
--- weeks of the crew's own time, not of the world's).
---
--- The sandbox's first-call setting shifts the whole calendar: the story is
--- written with first contact on day C.CommsFirstContactDay, so a server
--- that wants it sooner gets every later thread sooner by the same amount.
function Cm.day()
    local d = Cm.store()
    if not d.day0 then return nil end
    local shift = C.CommsFirstContactDay - C.commsFirstDay()
    return math.floor((U.worldHours() - d.day0) / 24) + shift
end

---------------------------------------------------------------------------
-- Conditions
---------------------------------------------------------------------------
--- Fragment N as an item id (C.FragmentItems, LORE.md 1c).
function Cm.fragmentItem(n)
    return C.FragmentItems[n]
end

--- Which unconverted fragments this player has on them, as a set.
function Cm.fragmentsCarried(player)
    local out = {}
    if not player then return out end
    U.try("comms.fragments", function()
        local inv = player:getInventory()
        for n = 1, 6 do
            local id = Cm.fragmentItem(n)
            local list = inv:getAllTypeRecurse(id:match("%.(.+)$"))
            for i = 0, list:size() - 1 do
                -- getAllTypeRecurse compares the bare type (DEV_GUIDE); the
                -- id is what says it is ours.
                if list:get(i):getFullType() == Cm.fragmentItem(n) then
                    out[n] = true
                end
            end
        end
    end)
    return out
end

--- Whether this player has heard every line of a registered recording.
--- **Asked on the authority**: in multiplayer the server's copy of the
--- player is the one that learns a tape's lines, because the server walks a
--- world television's tape (DeviceData.updateMediaPlaying bci 0-36 returns
--- on a client for anything that is not an inventory device).
function Cm.watched(player, tapeId)
    if not player then return false end
    return U.try("comms.watched", function()
        local rm = getZomboidRadio():getRecordedMedia()
        local data = rm:getMediaData(tapeId)
        if not data then return false end
        return rm:hasListenedToAll(player, data)
    end) == true
end

--- One condition: a flag, or one of the dynamic questions gen_comms.py's
--- DYNAMIC list declares. `holder` may be nil, and every question about a
--- person answers false without one.
function Cm.check(cond, holder)
    local d = Cm.store()
    if d.flags[cond] then return true end
    if cond == "emh" then return U.state().emh == true end
    local n = cond:match("^rescued>=(%d+)$")
    if n then return (d.rescued or 0) >= tonumber(n) end
    n = cond:match("^lost>=(%d+)$")
    if n then return (d.lost or 0) >= tonumber(n) end
    n = cond:match("^day>=(%d+)$")
    if n then return (Cm.day() or -1) >= tonumber(n) end
    local tape = cond:match("^watched:(TREK_[%w_]+)$")
    if tape then return Cm.watched(holder, tape) end
    if cond == "carrying" then
        local have = Cm.fragmentsCarried(holder)
        for k in pairs(have) do
            if not (d.converted or {})[k] then return true end
        end
        return false
    end
    n = cond:match("^carrying:(%d)$")
    if n then
        n = tonumber(n)
        return Cm.fragmentsCarried(holder)[n] == true
               and not (d.converted or {})[n]
    end
    n = cond:match("^converted:(%d)$")
    if n then return (d.converted or {})[tonumber(n)] == true end
    n = cond:match("^converted>=(%d)$")
    if n then
        local count = 0
        for _ in pairs(d.converted or {}) do count = count + 1 end
        return count >= tonumber(n)
    end
    return false
end

--- Every condition in `requires` holds and none in `forbids` does.
function Cm.allow(requires, forbids, holder)
    for _, c in ipairs(requires or {}) do
        if not Cm.check(c, holder) then return false end
    end
    for _, c in ipairs(forbids or {}) do
        if Cm.check(c, holder) then return false end
    end
    return true
end

---------------------------------------------------------------------------
-- Rendering
---------------------------------------------------------------------------
--- The colour and label of a voice.
function Cm.voice(v)
    local t = Cm.tree().voices[v] or Cm.tree().voices.card
    return t
end

local function text(key, a1, a2)
    return getText(key, a1 or "", a2 or "")
end

--- A call as lines, in order: each node's lines in its speaker's colour,
--- then what the holder chose (or their silence) in the player's own.
---
--- `steps` is the call's own list, `{ n = node, o = option }`, where `o` is
--- nil for the node the call is on (or ended on), 0 for silence. `a1` and
--- `a2` are the names the call was made with (the holder's, the ensign's).
---
--- Pure: reads the tree and getText and nothing else, so the history is
--- drawn exactly as the live call was.
function Cm.render(steps, a1, a2)
    local out = {}
    local tree = Cm.tree()
    local you = Cm.voice("you")
    for _, step in ipairs(steps or {}) do
        local nd = tree.nodes[step.n]
        if nd then
            for _, ln in ipairs(nd.lines or {}) do
                local v = Cm.voice(ln.v)
                table.insert(out, { voice = ln.v, who = getText(v.name),
                                    text = text(ln.k, a1, a2),
                                    r = v.r, g = v.g, b = v.b })
            end
            if step.o == 0 then
                table.insert(out, { voice = "you", who = getText(you.name),
                                    text = getText("IGUI_TREK_CommsSilence"),
                                    r = you.r, g = you.g, b = you.b,
                                    silence = true })
            elseif step.o and nd.options and nd.options[step.o] then
                table.insert(out, { voice = "you", who = getText(you.name),
                                    text = text(nd.options[step.o].k, a1, a2),
                                    r = you.r, g = you.g, b = you.b })
            end
        end
    end
    return out
end

--- The options the holder can take on the live call, as `{ index, text }`.
--- The server decides which are available and publishes the indices
--- (`call.avail`); nothing here re-asks the conditions, because the
--- questions about a person -- what they carry, what they have watched --
--- are only answered truly on the authority.
function Cm.options(call)
    local out = {}
    if not call or not call.node then return out end
    local nd = Cm.tree().nodes[call.node]
    if not nd or not nd.options then return out end
    for _, i in ipairs(call.avail or {}) do
        local o = nd.options[i]
        if o then
            table.insert(out, { index = i, text = text(o.k, call.a1, call.a2) })
        end
    end
    return out
end

--- A thread's display title.
function Cm.title(threadId)
    local t = Cm.tree().threads[threadId]
    return t and getText(t.title) or tostring(threadId)
end

return Cm
