--[[ Shuttlecraft -- Captain Imogen Titus: the rules both halves share
    (CAPTAIN.md).

    She sits in the captain's chair on the Adirondack's bridge, and a player
    who right-clicks near her can sit down and ask what is going on. What she
    says is `TREK_CaptainTree`, generated by tools/gen_captain.py.

    **The conversation is the server's.** Every step goes to the authority,
    which checks the player is on the bridge and in reach, that the node they
    answer is the one it last sent them and the option is one it offered, and
    replies with the next node and what this player may ask next
    (TREK_CaptainServer). The panel draws what it is told (TREK_CaptainUI).

    **She is keyed to her chair, not her body** (CAPTAIN.md 5.5): the crew
    director seats a body there, but the conversation works whether or not one
    is sitting in it -- a sandbox with no zombies has no crew at all.

    This file is shared because the menu and the server must measure reach the
    same way, and because the conditions are asked on the server with the same
    code the tests call.
]]

require "TREK/TREK_Config"
require "TREK/TREK_Util"
require "TREK/TREK_Adirondack"
require "TREK/TREK_CaptainTree"

TREK = TREK or {}
local C = TREK.Config
local U = TREK.Util
local A = TREK.Adirondack

local Cap = {}
TREK.Captain = Cap

--- The generated tree. A function, so a test can swap in a tree of its own.
function Cap.tree()
    return TREK_CaptainTree
end

---------------------------------------------------------------------------
-- Her chair
---------------------------------------------------------------------------
local chair = nil

--- Her chair: deck, deck square and the way it faces -- k, lx, ly, face. The
--- first `captain_chair` on C.CaptainDeck; the field station has one too, and
--- she is not there.
function Cap.chair()
    if chair then return chair.k, chair.lx, chair.ly, chair.face end
    local k = C.CaptainDeck
    local deck = A.Layout.decks[k]
    if not deck then return nil end
    for _, o in ipairs(deck.objects) do
        if o[5] == "captain_chair" then
            chair = { k = k, lx = o[1], ly = o[2], face = o[6] or "N" }
            return chair.k, chair.lx, chair.ly, chair.face
        end
    end
    return nil
end

--- The chair's world square: x, y, z.
function Cap.chairSquare()
    local k, lx, ly = Cap.chair()
    if not k then return nil end
    local x, y = A.at(k, lx, ly)
    return x, y, A.Z
end

--- True when a character is on her deck and within C.CaptainReach of her
--- chair. The server refuses a step from anybody else; the panel closes.
function Cap.inReach(player)
    if not player then return false end
    local ok, px, py, pz = pcall(function()
        return player:getX(), player:getY(), player:getZ()
    end)
    if not ok or not px then return false end
    local k = A.locate(px, py, pz)
    if k ~= C.CaptainDeck then return false end
    local x, y = Cap.chairSquare()
    if not x then return false end
    return U.dist2(px, py, x + 0.5, y + 0.5) <= C.CaptainReach * C.CaptainReach
end

--- For a right-click: the clicked square is her chair or within
--- C.CaptainMenuMargin of it, on her deck.
function Cap.clicked(x, y, z)
    if not x or not y then return false end
    local k = A.locate(x, y, z)
    if k ~= C.CaptainDeck then return false end
    local cx, cy = Cap.chairSquare()
    if not cx then return false end
    local m = C.CaptainMenuMargin
    return math.abs(math.floor(x) - cx) <= m and math.abs(math.floor(y) - cy) <= m
end

---------------------------------------------------------------------------
-- What she remembers of a player
---------------------------------------------------------------------------
--- The player's record, on whichever copy of the player this is. **Written
--- only on the authority** (TREK_CaptainServer): a client's copy is never the
--- server's (DEV_GUIDE.md, *Player mod data a client writes is not the
--- server's*), which is why every reply carries what the panel needs.
function Cap.record(player)
    local md = player and U.try("captain.md", function() return player:getModData() end)
    if not md then return { heard = {}, marks = {} } end
    local r = md[C.CaptainKey]
    if type(r) ~= "table" then
        r = {}
        md[C.CaptainKey] = r
    end
    r.heard = type(r.heard) == "table" and r.heard or {}
    r.marks = type(r.marks) == "table" and r.marks or {}
    return r
end

---------------------------------------------------------------------------
-- Conditions
---------------------------------------------------------------------------
local function rescuesOf(player)
    local md = player and U.try("captain.rescues", function() return player:getModData() end)
    return md and tonumber(md[C.RescuesKey]) or 0
end

--- Whether she will tell this player what her people think happened
--- (CAPTAIN.md 2). The sandbox decides how much it takes.
function Cap.truth(player)
    local mode = C.captainTruth()
    if mode == 3 then return true end
    local Cm = TREK.Comms
    if Cm and Cm.check("revealDone", player) then return true end
    if mode == 1 then return false end
    if Cm and Cm.check("watched:TREK_LogSix", player) then return true end
    return rescuesOf(player) >= C.CaptainTruthRescues
end

--- Whether rescues have earned this player a rank she has not yet given.
function Cap.promotionDue(player)
    local TS = TREK.TraitsServer
    local T = TREK.Traits
    if not (TS and T and player) then return false end
    return (TS.earnedRank(player) or 0) > (T.rank(player) or 0)
end

local function inUniform(player)
    return U.try("captain.worn", function()
        local worn = player:getWornItems()
        for i = 0, worn:size() - 1 do
            local item = worn:getItemByIndex(i)
            local t = item and item:getFullType()
            for _, u in ipairs(C.UniformIssue) do
                if t == u then return true end
            end
        end
        return false
    end) == true
end

--- One condition, asked of the player in front of her. Anything not hers is
--- the channel's (TREK_Comms.check): its flags, rescues, fragments, tapes.
function Cap.check(cond, player)
    if cond == "truth" then return Cap.truth(player) end
    if cond == "promotionDue" then return Cap.promotionDue(player) end
    if cond == "ranked" then
        return TREK.Traits ~= nil and (TREK.Traits.rank(player) or 0) > 0
    end
    if cond == "uniform" then return player ~= nil and inUniform(player) end
    if cond == "shipDark" then
        local s = U.state()
        return s.dark == true or s.commissioned == false
    end
    if cond == "distressLive" then
        local P = TREK.Probes
        return P ~= nil and (P.distress() ~= nil or P.mission() ~= nil)
    end
    if cond == "probed" then
        local P = TREK.Probes
        return P ~= nil and (tonumber(P.store().launches) or 0) > 0
    end
    local n = cond:match("^myRescues>=(%d+)$")
    if n then return rescuesOf(player) >= tonumber(n) end
    local mark = cond:match("^me:(%a+)$")
    if mark then return Cap.record(player).marks[mark] == true end
    local Cm = TREK.Comms
    return Cm ~= nil and Cm.check(cond, player) == true
end

function Cap.allow(requires, forbids, player)
    for _, c in ipairs(requires or {}) do
        if not Cap.check(c, player) then return false end
    end
    for _, c in ipairs(forbids or {}) do
        if Cap.check(c, player) then return false end
    end
    return true
end

---------------------------------------------------------------------------
-- Walking the tree
---------------------------------------------------------------------------
--- The first arm of a route this player passes, as a node id; an arm naming
--- several nodes picks one of them.
function Cap.route(route, player, rnd)
    rnd = rnd or function(n) return ZombRand(n) end
    for _, arm in ipairs(route or {}) do
        if Cap.allow(arm.requires, arm.forbids, player) then
            local go = arm.go
            if #go == 1 then return go[1] end
            return go[rnd(#go) + 1]
        end
    end
    return nil
end

--- Whether a node's tier is open to this player. A hub node has none.
function Cap.tierOpen(nodeId, player)
    local tree = Cap.tree()
    local nd = tree.nodes[nodeId]
    if not nd then return false end
    if not nd.tier then return true end
    local topic = tree.topics[nd.topic]
    for _, t in ipairs(topic and topic.tiers or {}) do
        if t.id == nd.tier then return Cap.allow(t.requires, t.forbids, player) end
    end
    return false
end

--- True for a node that shows the topics beneath it: a hub node with no
--- options of its own.
function Cap.isList(nodeId)
    local nd = Cap.tree().nodes[nodeId]
    return nd ~= nil and nd.topic == "HUB" and not nd.options
end

--- True for a goodbye: a node the hub's `bye` route can reach.
function Cap.isBye(nodeId)
    for _, arm in ipairs(Cap.tree().hub.bye or {}) do
        for _, g in ipairs(arm.go) do
            if g == nodeId then return true end
        end
    end
    return false
end

--- The indices of a node's options this player may take: the option's own
--- conditions, and a target whose tier is open.
function Cap.available(nodeId, player)
    local out = {}
    local nd = Cap.tree().nodes[nodeId]
    if not nd or not nd.options then return out end
    for i, o in ipairs(nd.options) do
        if Cap.allow(o.requires, o.forbids, player)
           and (o.go == "HUB" or o.go == "BYE" or Cap.tierOpen(o.go, player)) then
            table.insert(out, i)
        end
    end
    return out
end

--- The topics this player may ask about, in order: { { id, new } }. A topic is
--- new while one of its open tiers is one they have not heard.
function Cap.topics(player)
    local tree = Cap.tree()
    local heard = Cap.record(player).heard
    local out = {}
    for _, id in ipairs(tree.order) do
        local t = tree.topics[id]
        if t and Cap.allow(t.requires, t.forbids, player) then
            local new = false
            for _, tier in ipairs(t.tiers) do
                if not heard[id .. ":" .. tier.id]
                   and Cap.allow(tier.requires, tier.forbids, player) then
                    new = true
                end
            end
            table.insert(out, { id = id, new = new })
        end
    end
    return out
end

---------------------------------------------------------------------------
-- Words
---------------------------------------------------------------------------
--- How she addresses this player, for %1: rank and surname once she has both,
--- the rank alone, the first name alone, or a plain word -- never a name she
--- was not told (CAPTAIN.md 6). `named` is the server's answer.
function Cap.address(player, named)
    local T = TREK.Traits
    local _, path = 0, nil
    if T then _, path = T.rank(player) end
    local rank = path and getText("UI_trait_trek_" .. path) or nil
    local sur = U.try("captain.sur", function() return player:getDescriptor():getSurname() end)
    local fore = U.try("captain.fore", function() return player:getDescriptor():getForename() end)
    if rank and named and sur and sur ~= "" then return rank .. " " .. sur end
    if rank then return rank end
    if named and fore and fore ~= "" then return fore end
    return getText("IGUI_TREK_CaptAddressNone")
end

--- The player's own name, for %3 in their options.
function Cap.fullName(player)
    local fore = U.try("captain.fore", function() return player:getDescriptor():getForename() end) or ""
    local sur = U.try("captain.sur", function() return player:getDescriptor():getSurname() end) or ""
    local name = (fore .. " " .. sur):gsub("^%s+", ""):gsub("%s+$", "")
    if name == "" then
        name = U.try("captain.user", function() return player:getUsername() end) or "?"
    end
    return name
end

--- This player's rank title, for %2, or "".
function Cap.rankTitle(player)
    local T = TREK.Traits
    if not T then return "" end
    local _, path = T.rank(player)
    return path and getText("UI_trait_trek_" .. path) or ""
end

return Cap
