-- GENERATED by tools/gen_comms.py -- do not edit by hand.
--
-- The Adirondack channel's dialogue tree (COMMS.md 3). Every string
-- here is a translation key into Translate/EN/Print_Text.json, and
-- both files come out of the generator together. The server walks
-- this; the PADD renders history from it, so a line fixed here is
-- fixed in every player's transcript (PADD.md 12.2).

TREK_CommsTree = {}
local T = TREK_CommsTree

T.voices = {
    card = { name = "Print_Text_TREK_COMM_Voice_card", r = 1.00, g = 1.00, b = 1.00 },
    shepard = { name = "Print_Text_TREK_COMM_Voice_shepard", r = 1.00, g = 0.75, b = 0.00 },
    emh = { name = "Print_Text_TREK_COMM_Voice_emh", r = 0.00, g = 0.69, b = 0.31 },
    officer = { name = "Print_Text_TREK_COMM_Voice_officer", r = 0.62, g = 0.45, b = 0.85 },
    crew = { name = "Print_Text_TREK_COMM_Voice_crew", r = 0.00, g = 0.69, b = 0.94 },
    you = { name = "Print_Text_TREK_COMM_Voice_you", r = 0.80, g = 0.80, b = 0.80 },
}

-- The order threads are considered in, which is their priority.
T.order = { "FIRST", "THANKS", "LOST", "CLUE", "STAY", "ELEVEN", "SCIENCE", "DENIAL", "ARCHIVE", "REVEAL", "GOLD", "GRIEF", "CONVERT", "QUIET", "RESUME" }

T.systemFlags = { "clueSeen", "commissioned", "lostDue", "thanksDue" }

T.threads = {
    FIRST = { title = "Print_Text_TREK_COMM_FIRST_Title", kind = "incoming", entries = { "FIRST_01", "FIRST_01M", "FIRST_01MM" }, requires = {}, forbids = { "quiet" }, retry = true, repeatable = false, day = 7 },
    THANKS = { title = "Print_Text_TREK_COMM_THANKS_Title", kind = "incoming", entries = { "THANKS_01" }, requires = { "thanksDue", "met" }, forbids = { "quiet" }, retry = false, repeatable = true },
    LOST = { title = "Print_Text_TREK_COMM_LOST_Title", kind = "incoming", entries = { "LOST_01" }, requires = { "lostDue", "met" }, forbids = { "quiet" }, retry = false, repeatable = true },
    CLUE = { title = "Print_Text_TREK_COMM_CLUE_Title", kind = "incoming", entries = { "CLUE_01", "CLUE_01M" }, requires = { "clueSeen", "met" }, forbids = { "quiet" }, retry = true, repeatable = false },
    STAY = { title = "Print_Text_TREK_COMM_STAY_Title", kind = "incoming", entries = { "STAY_01", "STAY_01M" }, requires = {}, forbids = { "quiet" }, retry = true, repeatable = false, after = "FIRST", afterHours = 40 },
    ELEVEN = { title = "Print_Text_TREK_COMM_ELEVEN_Title", kind = "incoming", entries = { "ELEVEN_01", "ELEVEN_01M" }, requires = {}, forbids = { "quiet" }, retry = true, repeatable = false, after = "STAY", afterHours = 40 },
    SCIENCE = { title = "Print_Text_TREK_COMM_SCIENCE_Title", kind = "incoming", entries = { "SCIENCE_01", "SCIENCE_01M" }, requires = {}, forbids = { "quiet" }, retry = true, repeatable = false, after = "ELEVEN", afterHours = 30 },
    DENIAL = { title = "Print_Text_TREK_COMM_DENIAL_Title", kind = "incoming", entries = { "DENIAL_01", "DENIAL_01M" }, requires = {}, forbids = { "quiet" }, retry = true, repeatable = false, after = "SCIENCE", afterHours = 36 },
    ARCHIVE = { title = "Print_Text_TREK_COMM_ARCHIVE_Title", kind = "incoming", entries = { "ARCHIVE_01", "ARCHIVE_01M" }, requires = {}, forbids = { "quiet" }, retry = true, repeatable = false, after = "DENIAL", afterHours = 36 },
    REVEAL = { title = "Print_Text_TREK_COMM_REVEAL_Title", kind = "incoming", entries = { "REVEAL_01", "REVEAL_01M" }, requires = {}, forbids = { "quiet" }, retry = true, repeatable = false, after = "ARCHIVE", afterHours = 48 },
    GOLD = { title = "Print_Text_TREK_COMM_GOLD_Title", kind = "incoming", entries = { "GOLD_01", "GOLD_01M" }, requires = { "converted>=6", "met" }, forbids = { "quiet" }, retry = true, repeatable = false },
    GRIEF = { title = "Print_Text_TREK_COMM_GRIEF_Title", kind = "incoming", entries = { "GRIEF_01", "GRIEF_01M" }, requires = { "revealDone", "goldDone" }, forbids = { "quiet" }, retry = true, repeatable = false },
    CONVERT = { title = "Print_Text_TREK_COMM_CONVERT_Title", kind = "hail", entries = { "CONVERT_01" }, requires = { "carrying" }, forbids = {}, retry = true, repeatable = true, cooldown = 1 },
    QUIET = { title = "Print_Text_TREK_COMM_QUIET_Title", kind = "hail", entries = { "QUIET_01" }, requires = { "met" }, forbids = { "quiet" }, retry = true, repeatable = true, cooldown = 24 },
    RESUME = { title = "Print_Text_TREK_COMM_RESUME_Title", kind = "hail", entries = { "RESUME_01" }, requires = { "quiet" }, forbids = {}, retry = true, repeatable = false },
}

T.nodes = {
    ["FIRST_01"] = { thread = "FIRST", lines = { { v = "card", k = "Print_Text_TREK_COMM_FIRST_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_01_O1", go = "FIRST_02" },
        { k = "Print_Text_TREK_COMM_FIRST_01_O2", go = "FIRST_02R" },
        { k = "Print_Text_TREK_COMM_FIRST_01_O3", go = "FIRST_02H" },
    }, timeout = 60, silence = "FIRST_01S" },
    ["FIRST_01M"] = { thread = "FIRST", lines = { { v = "card", k = "Print_Text_TREK_COMM_FIRST_01M_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01M_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01M_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01M_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_01M_O1", go = "FIRST_02" },
        { k = "Print_Text_TREK_COMM_FIRST_01M_O2", go = "FIRST_02R" },
        { k = "Print_Text_TREK_COMM_FIRST_01M_O3", go = "FIRST_02H" },
    }, timeout = 60, silence = "FIRST_01S" },
    ["FIRST_01MM"] = { thread = "FIRST", lines = { { v = "card", k = "Print_Text_TREK_COMM_FIRST_01MM_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01MM_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01MM_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_01MM_O1", go = "FIRST_02" },
        { k = "Print_Text_TREK_COMM_FIRST_01MM_O2", go = "FIRST_02R" },
    }, timeout = 45, silence = "FIRST_01S" },
    ["FIRST_01S"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01S_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_01S_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_01S_O1", go = "FIRST_02" },
    } },
    ["FIRST_02R"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02R_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02R_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02R_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_02R_O1", go = "FIRST_02" },
    } },
    ["FIRST_02H"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02H_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02H_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_02H_O1", go = "FIRST_02" },
        { k = "Print_Text_TREK_COMM_FIRST_02H_O2", go = "FIRST_02" },
    } },
    ["FIRST_02"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L4" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_02_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_02_O1", go = "FIRST_03" },
        { k = "Print_Text_TREK_COMM_FIRST_02_O2", go = "FIRST_03" },
        { k = "Print_Text_TREK_COMM_FIRST_02_O3", go = "FIRST_03J" },
    } },
    ["FIRST_03J"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_03J_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_03J_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_03J_O1", go = "FIRST_03" },
    } },
    ["FIRST_03"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_03_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_03_O1", go = "FIRST_04N" },
        { k = "Print_Text_TREK_COMM_FIRST_03_O2", go = "FIRST_04S" },
        { k = "Print_Text_TREK_COMM_FIRST_03_O3", go = "FIRST_04X", sets = { "named" } },
        { k = "Print_Text_TREK_COMM_FIRST_03_O4", go = "FIRST_04X" },
    }, timeout = 60, silence = "FIRST_04Q" },
    ["FIRST_04N"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04N_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04N_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04N_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04N_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_04N_O1", go = "FIRST_05" },
        { k = "Print_Text_TREK_COMM_FIRST_04N_O2", go = "FIRST_05" },
        { k = "Print_Text_TREK_COMM_FIRST_04N_O3", go = "FIRST_05" },
    } },
    ["FIRST_04S"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04S_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04S_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04S_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04S_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_04S_O1", go = "FIRST_05" },
        { k = "Print_Text_TREK_COMM_FIRST_04S_O2", go = "FIRST_05" },
    } },
    ["FIRST_04X"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04X_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_04X_O1", go = "FIRST_05" },
    } },
    ["FIRST_04Q"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04Q_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_04Q_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_04Q_O1", go = "FIRST_05" },
    } },
    ["FIRST_05"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_05_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_05_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_05_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_05_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_05_O1", go = "FIRST_06" },
        { k = "Print_Text_TREK_COMM_FIRST_05_O2", go = "FIRST_06U" },
        { k = "Print_Text_TREK_COMM_FIRST_05_O3", go = "FIRST_06W" },
    } },
    ["FIRST_06U"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06U_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06U_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06U_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06U_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_06U_O1", go = "FIRST_06" },
        { k = "Print_Text_TREK_COMM_FIRST_06U_O2", go = "FIRST_06" },
    } },
    ["FIRST_06W"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06W_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06W_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_06W_O1", go = "FIRST_06" },
    } },
    ["FIRST_06"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_06_O1", go = "FIRST_07" },
        { k = "Print_Text_TREK_COMM_FIRST_06_O2", go = "FIRST_06Q" },
        { k = "Print_Text_TREK_COMM_FIRST_06_O3", go = "FIRST_07" },
    } },
    ["FIRST_06Q"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06Q_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06Q_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_06Q_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_06Q_O1", go = "FIRST_07" },
    } },
    ["FIRST_07"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_07_O1", go = "FIRST_07A", requires = { "watched:TREK_LogSix" } },
        { k = "Print_Text_TREK_COMM_FIRST_07_O2", go = "FIRST_08" },
        { k = "Print_Text_TREK_COMM_FIRST_07_O3", go = "FIRST_08" },
    } },
    ["FIRST_07A"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07A_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07A_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_07A_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_FIRST_07A_O1", go = "FIRST_08" },
        { k = "Print_Text_TREK_COMM_FIRST_07A_O2", go = "FIRST_08" },
    } },
    ["FIRST_08"] = { thread = "FIRST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_08_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_08_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_FIRST_08_L3" } }, sets = { "met" }, terminal = true },
    ["THANKS_01"] = { thread = "THANKS", lines = { { v = "card", k = "Print_Text_TREK_COMM_THANKS_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_THANKS_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_THANKS_01_O1", go = "THANKS_02" },
        { k = "Print_Text_TREK_COMM_THANKS_01_O2", go = "THANKS_03" },
    }, clears = { "thanksDue" } },
    ["THANKS_02"] = { thread = "THANKS", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_THANKS_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_THANKS_02_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_THANKS_02_O1", go = "THANKS_03" },
        { k = "Print_Text_TREK_COMM_THANKS_02_O2", go = "THANKS_03" },
    } },
    ["THANKS_03"] = { thread = "THANKS", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_THANKS_03_L1" } }, terminal = true },
    ["LOST_01"] = { thread = "LOST", lines = { { v = "card", k = "Print_Text_TREK_COMM_LOST_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_LOST_01_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_LOST_01_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_LOST_01_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_LOST_01_O1", go = "LOST_02" },
        { k = "Print_Text_TREK_COMM_LOST_01_O2", go = "LOST_02" },
        { k = "Print_Text_TREK_COMM_LOST_01_O3", go = "LOST_03" },
    }, clears = { "lostDue" } },
    ["LOST_02"] = { thread = "LOST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_LOST_02_L1" } }, terminal = true },
    ["LOST_03"] = { thread = "LOST", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_LOST_03_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_LOST_03_L2" } }, terminal = true },
    ["CLUE_01"] = { thread = "CLUE", lines = { { v = "card", k = "Print_Text_TREK_COMM_CLUE_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_CLUE_01_O1", go = "CLUE_02" },
        { k = "Print_Text_TREK_COMM_CLUE_01_O2", go = "CLUE_02" },
    }, timeout = 60, silence = "CLUE_02" },
    ["CLUE_01M"] = { thread = "CLUE", lines = { { v = "card", k = "Print_Text_TREK_COMM_CLUE_01M_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_01M_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_CLUE_01M_O1", go = "CLUE_02" },
    }, timeout = 60, silence = "CLUE_02" },
    ["CLUE_02"] = { thread = "CLUE", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_02_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_CLUE_02_O1", go = "CLUE_03" },
        { k = "Print_Text_TREK_COMM_CLUE_02_O2", go = "CLUE_03" },
    } },
    ["CLUE_03"] = { thread = "CLUE", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_03_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_03_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_03_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_03_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_CLUE_03_O1", go = "CLUE_04" },
        { k = "Print_Text_TREK_COMM_CLUE_03_O2", go = "CLUE_04" },
    } },
    ["CLUE_04"] = { thread = "CLUE", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_04_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_04_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_04_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_CLUE_04_O1", go = "CLUE_05" },
        { k = "Print_Text_TREK_COMM_CLUE_04_O2", go = "CLUE_05" },
    } },
    ["CLUE_05"] = { thread = "CLUE", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CLUE_05_L1" } }, sets = { "clueTold" }, terminal = true },
    ["STAY_01"] = { thread = "STAY", lines = { { v = "card", k = "Print_Text_TREK_COMM_STAY_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_01_O1", go = "STAY_02" },
        { k = "Print_Text_TREK_COMM_STAY_01_O2", go = "STAY_02" },
        { k = "Print_Text_TREK_COMM_STAY_01_O3", go = "STAY_02" },
    }, timeout = 60, silence = "STAY_02" },
    ["STAY_01M"] = { thread = "STAY", lines = { { v = "card", k = "Print_Text_TREK_COMM_STAY_01M_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_01M_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_01M_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_01M_O1", go = "STAY_02" },
        { k = "Print_Text_TREK_COMM_STAY_01M_O2", go = "STAY_02" },
    }, timeout = 60, silence = "STAY_02" },
    ["STAY_02"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_02_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_02_O1", go = "STAY_03" },
        { k = "Print_Text_TREK_COMM_STAY_02_O2", go = "STAY_02X" },
        { k = "Print_Text_TREK_COMM_STAY_02_O3", go = "STAY_03" },
    } },
    ["STAY_02X"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_02X_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_02X_O1", go = "STAY_03" },
    } },
    ["STAY_03"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_03_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_03_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_03_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_03_L4" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_03_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_03_O1", go = "STAY_04A" },
        { k = "Print_Text_TREK_COMM_STAY_03_O2", go = "STAY_04B" },
        { k = "Print_Text_TREK_COMM_STAY_03_O3", go = "STAY_04C" },
    } },
    ["STAY_04A"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04A_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04A_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04A_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_04A_O1", go = "STAY_05" },
        { k = "Print_Text_TREK_COMM_STAY_04A_O2", go = "STAY_05" },
    } },
    ["STAY_04B"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04B_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04B_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04B_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_04B_O1", go = "STAY_04BS" },
        { k = "Print_Text_TREK_COMM_STAY_04B_O2", go = "STAY_04BT" },
    } },
    ["STAY_04BS"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04BS_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_04BS_O1", go = "STAY_05" },
    } },
    ["STAY_04BT"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04BT_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04BT_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_04BT_O1", go = "STAY_05" },
    } },
    ["STAY_04C"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04C_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04C_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_04C_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_04C_O1", go = "STAY_05" },
        { k = "Print_Text_TREK_COMM_STAY_04C_O2", go = "STAY_05" },
    } },
    ["STAY_05"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_05_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_05_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_05_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_STAY_05_O1", go = "STAY_06Y" },
        { k = "Print_Text_TREK_COMM_STAY_05_O2", go = "STAY_06N" },
        { k = "Print_Text_TREK_COMM_STAY_05_O3", go = "STAY_06L" },
    } },
    ["STAY_06Y"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_06Y_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_06Y_L2" } }, sets = { "stayed" }, terminal = true },
    ["STAY_06N"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_06N_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_STAY_06N_L2" } }, sets = { "stayed" }, terminal = true },
    ["STAY_06L"] = { thread = "STAY", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_STAY_06L_L1" } }, sets = { "stayed" }, terminal = true },
    ["ELEVEN_01"] = { thread = "ELEVEN", lines = { { v = "card", k = "Print_Text_TREK_COMM_ELEVEN_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_01_O1", go = "ELEVEN_02" },
        { k = "Print_Text_TREK_COMM_ELEVEN_01_O2", go = "ELEVEN_02" },
    }, timeout = 60, silence = "ELEVEN_02" },
    ["ELEVEN_01M"] = { thread = "ELEVEN", lines = { { v = "card", k = "Print_Text_TREK_COMM_ELEVEN_01M_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_01M_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_01M_O1", go = "ELEVEN_02" },
    }, timeout = 60, silence = "ELEVEN_02" },
    ["ELEVEN_02"] = { thread = "ELEVEN", route = { { go = "ELEVEN_02R", requires = { "rescued>=1" } }, { go = "ELEVEN_02N" } } },
    ["ELEVEN_02R"] = { thread = "ELEVEN", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_02R_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_02R_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_02R_O1", go = "ELEVEN_03" },
    } },
    ["ELEVEN_02N"] = { thread = "ELEVEN", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_02N_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_02N_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_02N_O1", go = "ELEVEN_03" },
    } },
    ["ELEVEN_03"] = { thread = "ELEVEN", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03_L4" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_03_O1", go = "ELEVEN_04" },
        { k = "Print_Text_TREK_COMM_ELEVEN_03_O2", go = "ELEVEN_03W" },
        { k = "Print_Text_TREK_COMM_ELEVEN_03_O3", go = "ELEVEN_03C" },
    } },
    ["ELEVEN_03W"] = { thread = "ELEVEN", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03W_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03W_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_03W_O1", go = "ELEVEN_04" },
    } },
    ["ELEVEN_03C"] = { thread = "ELEVEN", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03C_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_03C_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_03C_O1", go = "ELEVEN_04" },
    } },
    ["ELEVEN_04"] = { thread = "ELEVEN", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_04_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_04_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_04_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_04_O1", go = "ELEVEN_05" },
        { k = "Print_Text_TREK_COMM_ELEVEN_04_O2", go = "ELEVEN_05Y" },
    } },
    ["ELEVEN_05Y"] = { thread = "ELEVEN", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_05Y_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_ELEVEN_05Y_O1", go = "ELEVEN_05" },
    } },
    ["ELEVEN_05"] = { thread = "ELEVEN", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_05_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_ELEVEN_05_L2" } }, sets = { "elevenDone" }, terminal = true },
    ["SCIENCE_01"] = { thread = "SCIENCE", lines = { { v = "card", k = "Print_Text_TREK_COMM_SCIENCE_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_SCIENCE_01_L2" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_01_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_01_O1", go = "SCIENCE_02" },
        { k = "Print_Text_TREK_COMM_SCIENCE_01_O2", go = "SCIENCE_02" },
    }, timeout = 60, silence = "SCIENCE_02" },
    ["SCIENCE_01M"] = { thread = "SCIENCE", lines = { { v = "card", k = "Print_Text_TREK_COMM_SCIENCE_01M_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_01M_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_SCIENCE_01M_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_01M_O1", go = "SCIENCE_02" },
    }, timeout = 60, silence = "SCIENCE_02" },
    ["SCIENCE_02"] = { thread = "SCIENCE", route = { { go = "SCIENCE_02E", requires = { "emh" } }, { go = "SCIENCE_02S" } } },
    ["SCIENCE_02E"] = { thread = "SCIENCE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_02E_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_02E_L2" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_02E_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_02E_O1", go = "SCIENCE_03" },
    } },
    ["SCIENCE_02S"] = { thread = "SCIENCE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_02S_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_02S_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_02S_O1", go = "SCIENCE_03" },
    } },
    ["SCIENCE_03"] = { thread = "SCIENCE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_03_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_03_L2" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_03_L3" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_03_L4" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_03_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_03_O1", go = "SCIENCE_04" },
        { k = "Print_Text_TREK_COMM_SCIENCE_03_O2", go = "SCIENCE_03P" },
    } },
    ["SCIENCE_03P"] = { thread = "SCIENCE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_03P_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_03P_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_03P_O1", go = "SCIENCE_04" },
    } },
    ["SCIENCE_04"] = { thread = "SCIENCE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_04_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_04_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_SCIENCE_04_L3" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_04_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_04_O1", go = "SCIENCE_05" },
        { k = "Print_Text_TREK_COMM_SCIENCE_04_O2", go = "SCIENCE_04W" },
        { k = "Print_Text_TREK_COMM_SCIENCE_04_O3", go = "SCIENCE_04M" },
    } },
    ["SCIENCE_04W"] = { thread = "SCIENCE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_04W_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_04W_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_04W_O1", go = "SCIENCE_05" },
    } },
    ["SCIENCE_04M"] = { thread = "SCIENCE", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_SCIENCE_04M_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_04M_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_SCIENCE_04M_O1", go = "SCIENCE_05" },
    } },
    ["SCIENCE_05"] = { thread = "SCIENCE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_05_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_05_L2" }, { v = "emh", k = "Print_Text_TREK_COMM_SCIENCE_05_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_SCIENCE_05_L4" } }, sets = { "scienceDone" }, terminal = true },
    ["DENIAL_01"] = { thread = "DENIAL", lines = { { v = "card", k = "Print_Text_TREK_COMM_DENIAL_01_L1" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_01_L2" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_01_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_01_O1", go = "DENIAL_02" },
        { k = "Print_Text_TREK_COMM_DENIAL_01_O2", go = "DENIAL_01Q" },
        { k = "Print_Text_TREK_COMM_DENIAL_01_O3", go = "DENIAL_01S" },
    }, timeout = 60, silence = "DENIAL_01Q" },
    ["DENIAL_01M"] = { thread = "DENIAL", lines = { { v = "card", k = "Print_Text_TREK_COMM_DENIAL_01M_L1" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_01M_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_01M_O1", go = "DENIAL_02" },
        { k = "Print_Text_TREK_COMM_DENIAL_01M_O2", go = "DENIAL_01Q" },
    }, timeout = 60, silence = "DENIAL_01Q" },
    ["DENIAL_01S"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_01S_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_01S_O1", go = "DENIAL_02" },
        { k = "Print_Text_TREK_COMM_DENIAL_01S_O2", go = "DENIAL_01Q" },
    } },
    ["DENIAL_01Q"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_01Q_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_01Q_O1", go = "DENIAL_02" },
    } },
    ["DENIAL_02"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_02_L1" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_02_L2" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_02_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_02_O1", go = "DENIAL_03P" },
        { k = "Print_Text_TREK_COMM_DENIAL_02_O2", go = "DENIAL_03B" },
        { k = "Print_Text_TREK_COMM_DENIAL_02_O3", go = "DENIAL_03W" },
    } },
    ["DENIAL_03P"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_03P_L1" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_03P_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_03P_O1", go = "DENIAL_04P" },
        { k = "Print_Text_TREK_COMM_DENIAL_03P_O2", go = "DENIAL_05" },
    } },
    ["DENIAL_04P"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_04P_L1" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_04P_L2" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_04P_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_04P_O1", go = "DENIAL_04T" },
        { k = "Print_Text_TREK_COMM_DENIAL_04P_O2", go = "DENIAL_05" },
    }, sets = { "pressed" } },
    ["DENIAL_04T"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_04T_L1" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_04T_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_04T_O1", go = "DENIAL_05" },
    } },
    ["DENIAL_03B"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_03B_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_03B_O1", go = "DENIAL_05" },
    } },
    ["DENIAL_03W"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_03W_L1" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_03W_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_DENIAL_03W_O1", go = "DENIAL_05" },
    } },
    ["DENIAL_05"] = { thread = "DENIAL", lines = { { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_05_L1" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_05_L2" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_05_L3" }, { v = "officer", k = "Print_Text_TREK_COMM_DENIAL_05_L4" } }, sets = { "denialDone" }, terminal = true },
    ["ARCHIVE_01"] = { thread = "ARCHIVE", lines = { { v = "card", k = "Print_Text_TREK_COMM_ARCHIVE_01_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ARCHIVE_01_O1", go = "ARCHIVE_02" },
        { k = "Print_Text_TREK_COMM_ARCHIVE_01_O2", go = "ARCHIVE_02" },
    }, timeout = 60, silence = "ARCHIVE_02" },
    ["ARCHIVE_01M"] = { thread = "ARCHIVE", lines = { { v = "card", k = "Print_Text_TREK_COMM_ARCHIVE_01M_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_01M_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ARCHIVE_01M_O1", go = "ARCHIVE_02" },
    }, timeout = 60, silence = "ARCHIVE_02" },
    ["ARCHIVE_02"] = { thread = "ARCHIVE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_02_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_02_L2" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_02_L3" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_02_L4" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_02_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_ARCHIVE_02_O1", go = "ARCHIVE_03" },
        { k = "Print_Text_TREK_COMM_ARCHIVE_02_O2", go = "ARCHIVE_03" },
        { k = "Print_Text_TREK_COMM_ARCHIVE_02_O3", go = "ARCHIVE_02P" },
    } },
    ["ARCHIVE_02P"] = { thread = "ARCHIVE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_02P_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_02P_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ARCHIVE_02P_O1", go = "ARCHIVE_03" },
    } },
    ["ARCHIVE_03"] = { thread = "ARCHIVE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_03_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_03_L2" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_03_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_ARCHIVE_03_O1", go = "ARCHIVE_04" },
        { k = "Print_Text_TREK_COMM_ARCHIVE_03_O2", go = "ARCHIVE_04K" },
    } },
    ["ARCHIVE_04K"] = { thread = "ARCHIVE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_04K_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_04K_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_ARCHIVE_04K_O1", go = "ARCHIVE_04" },
    } },
    ["ARCHIVE_04"] = { thread = "ARCHIVE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_04_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_04_L2" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_04_L3" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_04_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_ARCHIVE_04_O1", go = "ARCHIVE_05" },
        { k = "Print_Text_TREK_COMM_ARCHIVE_04_O2", go = "ARCHIVE_05" },
    } },
    ["ARCHIVE_05"] = { thread = "ARCHIVE", lines = { { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_05_L1" }, { v = "emh", k = "Print_Text_TREK_COMM_ARCHIVE_05_L2" } }, sets = { "archiveDone" }, terminal = true },
    ["REVEAL_01"] = { thread = "REVEAL", lines = { { v = "card", k = "Print_Text_TREK_COMM_REVEAL_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_REVEAL_01_O1", go = "REVEAL_02" },
        { k = "Print_Text_TREK_COMM_REVEAL_01_O2", go = "REVEAL_02" },
    }, timeout = 60, silence = "REVEAL_02" },
    ["REVEAL_01M"] = { thread = "REVEAL", lines = { { v = "card", k = "Print_Text_TREK_COMM_REVEAL_01M_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_01M_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_REVEAL_01M_O1", go = "REVEAL_02" },
    }, timeout = 60, silence = "REVEAL_02" },
    ["REVEAL_02"] = { thread = "REVEAL", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_02_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_02_L4" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_02_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_REVEAL_02_O1", go = "REVEAL_03T", requires = { "watched:TREK_LogSix" } },
        { k = "Print_Text_TREK_COMM_REVEAL_02_O2", go = "REVEAL_03" },
        { k = "Print_Text_TREK_COMM_REVEAL_02_O3", go = "REVEAL_04" },
    } },
    ["REVEAL_03T"] = { thread = "REVEAL", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_03T_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_03T_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_REVEAL_03T_O1", go = "REVEAL_05" },
    } },
    ["REVEAL_03"] = { thread = "REVEAL", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_03_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_03_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_REVEAL_03_O1", go = "REVEAL_04" },
    } },
    ["REVEAL_04"] = { thread = "REVEAL", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_04_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_04_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_04_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_04_L4" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_04_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_REVEAL_04_O1", go = "REVEAL_05" },
    } },
    ["REVEAL_05"] = { thread = "REVEAL", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_05_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_05_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_05_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_REVEAL_05_O1", go = "REVEAL_06" },
        { k = "Print_Text_TREK_COMM_REVEAL_05_O2", go = "REVEAL_06" },
        { k = "Print_Text_TREK_COMM_REVEAL_05_O3", go = "REVEAL_06N" },
    } },
    ["REVEAL_06N"] = { thread = "REVEAL", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_06N_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_06N_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_REVEAL_06N_O1", go = "REVEAL_06" },
    } },
    ["REVEAL_06"] = { thread = "REVEAL", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_06_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_06_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_06_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_REVEAL_06_L4" } }, sets = { "revealDone" }, terminal = true },
    ["GOLD_01"] = { thread = "GOLD", lines = { { v = "card", k = "Print_Text_TREK_COMM_GOLD_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_GOLD_01_O1", go = "GOLD_02" },
        { k = "Print_Text_TREK_COMM_GOLD_01_O2", go = "GOLD_02" },
    }, timeout = 60, silence = "GOLD_02" },
    ["GOLD_01M"] = { thread = "GOLD", lines = { { v = "card", k = "Print_Text_TREK_COMM_GOLD_01M_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_01M_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_GOLD_01M_O1", go = "GOLD_02" },
    }, timeout = 60, silence = "GOLD_02" },
    ["GOLD_02"] = { thread = "GOLD", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_02_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_02_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_GOLD_02_O1", go = "GOLD_03" },
        { k = "Print_Text_TREK_COMM_GOLD_02_O2", go = "GOLD_02Q" },
        { k = "Print_Text_TREK_COMM_GOLD_02_O3", go = "GOLD_04" },
    } },
    ["GOLD_02Q"] = { thread = "GOLD", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_02Q_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_02Q_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_GOLD_02Q_O1", go = "GOLD_03" },
    } },
    ["GOLD_03"] = { thread = "GOLD", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_03_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_03_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_03_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_03_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_GOLD_03_O1", go = "GOLD_04" },
        { k = "Print_Text_TREK_COMM_GOLD_03_O2", go = "GOLD_04" },
        { k = "Print_Text_TREK_COMM_GOLD_03_O3", go = "GOLD_04" },
    } },
    ["GOLD_04"] = { thread = "GOLD", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_04_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_04_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_GOLD_04_L3" } }, sets = { "goldDone" }, terminal = true },
    ["GRIEF_01"] = { thread = "GRIEF", lines = { { v = "card", k = "Print_Text_TREK_COMM_GRIEF_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_01_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_01_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_GRIEF_01_O1", go = "GRIEF_02" },
        { k = "Print_Text_TREK_COMM_GRIEF_01_O2", go = "GRIEF_02" },
    }, timeout = 60, silence = "GRIEF_02" },
    ["GRIEF_01M"] = { thread = "GRIEF", lines = { { v = "card", k = "Print_Text_TREK_COMM_GRIEF_01M_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_01M_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_GRIEF_01M_O1", go = "GRIEF_02" },
    }, timeout = 60, silence = "GRIEF_02" },
    ["GRIEF_02"] = { thread = "GRIEF", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_02_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_02_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_GRIEF_02_O1", go = "GRIEF_03" },
        { k = "Print_Text_TREK_COMM_GRIEF_02_O2", go = "GRIEF_03" },
        { k = "Print_Text_TREK_COMM_GRIEF_02_O3", go = "GRIEF_03E" },
    } },
    ["GRIEF_03E"] = { thread = "GRIEF", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_03E_L1" } }, options = {
        { k = "Print_Text_TREK_COMM_GRIEF_03E_O1", go = "GRIEF_03" },
    } },
    ["GRIEF_03"] = { thread = "GRIEF", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_03_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_03_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_03_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_GRIEF_03_L4" } }, sets = { "griefDone" }, terminal = true },
    ["CONVERT_01"] = { thread = "CONVERT", route = { { go = "CONVERT_HANG", forbids = { "converted>=1" } }, { go = "CONVERT_PICK" } } },
    ["CONVERT_HANG"] = { thread = "CONVERT", lines = { { v = "card", k = "Print_Text_TREK_COMM_CONVERT_HANG_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_HANG_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_HANG_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_HANG_L4" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_HANG_L5" } }, options = {
        { k = "Print_Text_TREK_COMM_CONVERT_HANG_O1", go = "CONVERT_PICK" },
        { k = "Print_Text_TREK_COMM_CONVERT_HANG_O2", go = "CONVERT_HANGT" },
    } },
    ["CONVERT_HANGT"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_HANGT_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_HANGT_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_CONVERT_HANGT_O1", go = "CONVERT_PICK" },
    } },
    ["CONVERT_PICK"] = { thread = "CONVERT", route = { { go = "CONVERT_F1", requires = { "carrying:1" } }, { go = "CONVERT_F2", requires = { "carrying:2" } }, { go = "CONVERT_F3", requires = { "carrying:3" } }, { go = "CONVERT_F4", requires = { "carrying:4" } }, { go = "CONVERT_F5", requires = { "carrying:5" } }, { go = "CONVERT_F6", requires = { "carrying:6" } }, { go = "CONVERT_NONE" } } },
    ["CONVERT_NONE"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_NONE_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_NONE_L2" } }, terminal = true },
    ["CONVERT_F1"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F1_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F1_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F1_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_CONVERT_F1_O1", go = "CONVERT_COUNT" },
        { k = "Print_Text_TREK_COMM_CONVERT_F1_O2", go = "CONVERT_COUNT" },
    }, convert = 1 },
    ["CONVERT_F2"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F2_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F2_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F2_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_CONVERT_F2_O1", go = "CONVERT_COUNT" },
        { k = "Print_Text_TREK_COMM_CONVERT_F2_O2", go = "CONVERT_COUNT" },
    }, convert = 2 },
    ["CONVERT_F3"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F3_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F3_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F3_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_CONVERT_F3_O1", go = "CONVERT_COUNT" },
        { k = "Print_Text_TREK_COMM_CONVERT_F3_O2", go = "CONVERT_COUNT" },
    }, convert = 3 },
    ["CONVERT_F4"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F4_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F4_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F4_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_CONVERT_F4_O1", go = "CONVERT_COUNT" },
        { k = "Print_Text_TREK_COMM_CONVERT_F4_O2", go = "CONVERT_COUNT" },
    }, convert = 4 },
    ["CONVERT_F5"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F5_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F5_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F5_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_CONVERT_F5_O1", go = "CONVERT_COUNT" },
        { k = "Print_Text_TREK_COMM_CONVERT_F5_O2", go = "CONVERT_COUNT" },
    }, convert = 5 },
    ["CONVERT_F6"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F6_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F6_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_F6_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_CONVERT_F6_O1", go = "CONVERT_COUNT" },
        { k = "Print_Text_TREK_COMM_CONVERT_F6_O2", go = "CONVERT_COUNT" },
    }, convert = 6 },
    ["CONVERT_COUNT"] = { thread = "CONVERT", route = { { go = "CONVERT_ALL", requires = { "converted>=6" } }, { go = "CONVERT_LAST", requires = { "converted>=5" } }, { go = "CONVERT_MID", requires = { "converted>=3" } }, { go = "CONVERT_EARLY", requires = { "converted>=2" } }, { go = "CONVERT_FIRSTONE" } } },
    ["CONVERT_FIRSTONE"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_FIRSTONE_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_FIRSTONE_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_FIRSTONE_L3" } }, terminal = true },
    ["CONVERT_EARLY"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_EARLY_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_EARLY_L2" } }, terminal = true },
    ["CONVERT_MID"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_MID_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_MID_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_MID_L3" } }, terminal = true },
    ["CONVERT_LAST"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_LAST_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_LAST_L2" } }, terminal = true },
    ["CONVERT_ALL"] = { thread = "CONVERT", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_ALL_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_ALL_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_CONVERT_ALL_L3" } }, terminal = true },
    ["QUIET_01"] = { thread = "QUIET", lines = { { v = "card", k = "Print_Text_TREK_COMM_QUIET_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_01_L2" } }, options = {
        { k = "Print_Text_TREK_COMM_QUIET_01_O1", go = "QUIET_02" },
        { k = "Print_Text_TREK_COMM_QUIET_01_O2", go = "QUIET_09" },
    } },
    ["QUIET_02"] = { thread = "QUIET", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_02_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_02_L3" }, { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_02_L4" } }, options = {
        { k = "Print_Text_TREK_COMM_QUIET_02_O1", go = "QUIET_03" },
        { k = "Print_Text_TREK_COMM_QUIET_02_O2", go = "QUIET_03" },
    } },
    ["QUIET_03"] = { thread = "QUIET", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_03_L1" } }, sets = { "quiet" }, terminal = true },
    ["QUIET_09"] = { thread = "QUIET", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_QUIET_09_L1" } }, terminal = true },
    ["RESUME_01"] = { thread = "RESUME", lines = { { v = "card", k = "Print_Text_TREK_COMM_RESUME_01_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_01_L2" }, { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_01_L3" } }, options = {
        { k = "Print_Text_TREK_COMM_RESUME_01_O1", go = "RESUME_02" },
        { k = "Print_Text_TREK_COMM_RESUME_01_O2", go = "RESUME_03" },
    } },
    ["RESUME_02"] = { thread = "RESUME", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_02_L1" }, { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_02_L2" } }, clears = { "quiet" }, terminal = true },
    ["RESUME_03"] = { thread = "RESUME", lines = { { v = "shepard", k = "Print_Text_TREK_COMM_RESUME_03_L1" } }, terminal = true },
}

return T
