"""The Adirondack channel, as written (COMMS.md 6).

The machinery is in tools/gen_comms.py; this file is only the conversation.
Run the generator after any edit here -- it refuses to write a tree that
fails its checks, and says which node and why.

House rules, from COMMS.md 3 and LORE.md 4, because they are the whole of the
style:

  * **A line is a shot.** Thirty to seventy characters. A speech is several
    lines, not one long one.
  * **Colour is the speaker.** Shepard amber, the Doctor green, the officer
    violet, anybody else aboard blue, the player grey.
  * **The player's options are characterisation, not a quiz.** No option is
    correct. At least one in every node is what a tired, frightened person
    actually says, which is usually shorter and ruder than the others.
  * **Write for the player who has not watched the logs, and let the one who
    has enjoy being ahead** (COMMS.md 4). Never a call that is nothing but a
    log read aloud.
  * **Nothing here confirms who the player is** (COMMS.md 6.1). She believes
    them or she does not, and the dialogue carries both for ever.

Tokens: %1 is the holder's first name, %2 the ensign most recently brought up
(or lost). Only use %1 in a line after the player has given it -- the flag
`named` -- or in the player's own options.
"""
from comms_vocab import say, opt, branch, node, thread

S, E, O, K, Y, CARD = "shepard", "emh", "officer", "crew", "you", "card"


# ---------------------------------------------------------------------------
# 6.1 First contact
# ---------------------------------------------------------------------------
# She is astonished anyone is aboard her shuttle. Three facts: she is alive,
# the ship cannot leave, they can still transport. And the player decides who
# they are, and the mod never says whether that is true.
FIRST = thread(
    "FIRST", "First contact", "incoming",
    day=7, forbids=["quiet"],
    entries=["01", "01M", "01MM"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shuttlecraft, this is the Adirondack. Please respond."),
             say(S, "Somebody has been aboard my shuttle. The core says so."),
             say(S, "If you can hear me, say something. Anything at all."),
             options=[
                 opt("I hear you. Who is this?", "02"),
                 opt("Your shuttle? Finders keepers.", "02R"),
                 opt("Is anyone coming to get us?", "02H"),
             ],
             timeout=60, silence="01S"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK -- SECOND ATTEMPT"),
             say(S, "Shuttlecraft, Adirondack. Second time of asking."),
             say(S, "I know somebody is down there. The core keeps count."),
             say(S, "Pick up. Please."),
             options=[
                 opt("Sorry. I'm here. Who is this?", "02"),
                 opt("I was busy staying alive.", "02R"),
                 opt("Is anyone coming to get us?", "02H"),
             ],
             timeout=60, silence="01S"),
        node("01MM",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Third time. I'm going to assume you're busy."),
             say(S, "Or dead. I would rather busy. Answer if you can."),
             options=[
                 opt("Busy. Not dead. Go ahead.", "02"),
                 opt("Stop calling me.", "02R"),
             ],
             timeout=45, silence="01S"),
        node("01S",
             say(S, "Nothing. All right. Then I'll talk, and you listen."),
             say(S, "If you're hurt, or scared, that is fine. Just listen."),
             options=[opt("...Go on.", "02")]),
        node("02R",
             say(S, "Ha. No. Mine. Logged item by item, every lamp."),
             say(S, "But you're alive and you found her, so she's yours now."),
             say(S, "Look after her. She's the only one left down there."),
             options=[opt("Who are you?", "02")]),
        node("02H",
             say(S, "No. I'm sorry. Nobody is coming. Not for years."),
             say(S, "I'd rather tell you that now than have you hope."),
             options=[opt("Then who are you?", "02"),
                      opt("Great. Thanks.", "02")]),
        node("02",
             say(S, "Lieutenant Lucy Shepard. Cultural survey. And that"),
             say(S, "is my shuttle you're standing in. My fridge, my oven."),
             say(S, "My chair, which I would quite like back one day."),
             say(S, "I have talked to the same hundred and forty faces"),
             say(S, "since July. You are the first new voice in months."),
             options=[opt("Lucky me.", "03"),
                      opt("What happened to you?", "03"),
                      opt("July? What happened in July?", "03J")]),
        node("03J",
             say(S, "You know what happened in July. You're living in it."),
             say(S, "I meant up here. It's been a long summer in orbit."),
             options=[opt("Right. Sorry.", "03")]),
        node("03",
             say(S, "So. Who am I talking to?"),
             options=[
                 opt("I'm from around here. I found this in a field.", "04N"),
                 opt("Starfleet. Same as you.", "04S"),
                 opt("My name's %1. That's all you get.", "04X",
                     sets=["named"]),
                 opt("Doesn't matter who I am.", "04X"),
             ],
             timeout=60, silence="04Q"),
        node("04N",
             say(S, "A local. Of course you are. Of course you are."),
             say(S, "Then I owe you an apology, and it is a very big one."),
             say(S, "We were up here watching when it happened to you."),
             say(S, "We watched, and we wrote it down, and we did nothing."),
             options=[opt("You couldn't have stopped it.", "05"),
                      opt("Yeah. You did.", "05"),
                      opt("Write down what, exactly?", "05")]),
        node("04S",
             say(S, "Starfleet."),
             say(S, "Nobody told me. Nobody told any of us anything."),
             say(S, "I'll take it. I'm not in any position to check."),
             say(S, "And frankly, I've stopped caring whose side anyone is on."),
             options=[opt("Good. Neither have I.", "05"),
                      opt("I'm not here to argue.", "05")]),
        node("04X",
             say(S, "Fair. I wouldn't tell me either, after this summer."),
             options=[opt("So what do you want?", "05")]),
        node("04Q",
             say(S, "Nothing? All right. I'll call you the shuttle, then."),
             say(S, "Plenty of people up here I'd rather not know better."),
             options=[opt("...Fine.", "05")]),
        node("05",
             say(S, "Three things, and then you can hang up on me."),
             say(S, "One. I'm alive. So are a hundred and forty others."),
             say(S, "Two. The Adirondack cannot leave. No warp. No impulse."),
             say(S, "Three. We can still transport. That is what we kept."),
             options=[opt("Transport what, where?", "06"),
                      opt("Then get me out of here.", "06U"),
                      opt("Why tell me any of this?", "06W")]),
        node("06U",
             say(S, "I would. I can't. Not yet, and it isn't my call."),
             say(S, "The Doctor won't bring anyone up from the surface"),
             say(S, "until he knows how it spreads. Quarantine. Hard stop."),
             say(S, "I'm sorry. I know exactly what I'm asking you to live in."),
             options=[opt("Of course you do.", "06"),
                      opt("I'll hold you to 'not yet'.", "06")]),
        node("06W",
             say(S, "Because you're in my shuttle, and my shuttle works."),
             say(S, "And because there are people down there who are mine."),
             options=[opt("Go on.", "06")]),
        node("06",
             say(S, "Eleven of my crew stayed on the ground. For the work."),
             say(S, "Some of them are still calling. Distress beacons."),
             say(S, "Your shuttle hears them. I can't find them without you."),
             say(S, "Get to one, call it in, and we pull them up from here."),
             options=[opt("I'll see what I can do.", "07"),
                      opt("Why should I risk my neck for your people?", "06Q"),
                      opt("No promises.", "07")]),
        node("06Q",
             say(S, "You shouldn't. I'm not going to pretend otherwise."),
             say(S, "The ship pays for it. Patterns for the replicator,"),
             say(S, "supplies. And they would do it for you. Every one."),
             options=[opt("We'll see.", "07")]),
        node("07",
             say(S, "One more thing, and it's the one that matters to me."),
             say(S, "The tapes by the television. They're mine. Watch them."),
             say(S, "Everything I know about what happened is on those."),
             options=[opt("I have. All six logs.", "07A",
                          requires=["watched:TREK_LogSix"]),
                      opt("I'll get to them.", "08"),
                      opt("Not my kind of television.", "08")]),
        node("07A",
             say(S, "Then you know more than Starfleet does."),
             say(S, "That's a low bar. I'm sorry you had to clear it."),
             say(S, "And you know about the chair. Don't sit in it for me."),
             options=[opt("Too late.", "08"),
                      opt("It's a good chair.", "08")]),
        node("08",
             say(S, "I'll call again. Or you call me, off your PADD."),
             say(S, "Most of the time nobody answers up here. Try anyway."),
             say(S, "Shepard out."),
             sets=["met"]),
    ])


# ---------------------------------------------------------------------------
# The quiet path (COMMS.md 6.2)
# ---------------------------------------------------------------------------
# The player tells her to stop calling, and she does. Cheap, respectful, and a
# mod whose premise is "nobody is coming" should be able to honour somebody
# who would rather it stayed that way.
# Repeatable, with a day's cooldown: the one hail that is always there once
# you have met her, so it is also what "she picks up about once a day" means.
# Not repeatable, a player who said "wrong button" once would lose the quiet
# path for good.
QUIET = thread(
    "QUIET", "Stop calling", "hail",
    requires=["met"], forbids=["quiet"], repeatable=True, cooldown=24,
    nodes=[
        node("01",
             say(CARD, "HAILING -- U.S.S. ADIRONDACK"),
             say(S, "Adirondack. Shepard. Everything all right down there?"),
             options=[opt("I want you to stop calling.", "02"),
                      opt("Nothing. Wrong button.", "09")]),
        node("02",
             say(S, "..."),
             say(S, "All right. I can do that."),
             say(S, "The shuttle will still hear the beacons. That's hers."),
             say(S, "If you ever want me, hail. I'll pick up if I can."),
             options=[opt("Thank you.", "03"),
                      opt("I won't.", "03")]),
        node("03",
             say(S, "Look after yourself. Shepard out."),
             sets=["quiet"]),
        node("09",
             say(S, "Happens. Shepard out."),),
    ])

RESUME = thread(
    "RESUME", "Opening the channel", "hail",
    requires=["quiet"],
    nodes=[
        node("01",
             say(CARD, "HAILING -- U.S.S. ADIRONDACK"),
             say(S, "..."),
             say(S, "Hello, you. I did wonder."),
             options=[opt("You can call again.", "02"),
                      opt("Just checking you're there.", "03")]),
        node("02",
             say(S, "I will, then. Sparingly. I promise."),
             say(S, "Shepard out."),
             clears=["quiet"]),
        node("03",
             say(S, "Still here. Still going nowhere. Shepard out."),),
    ])


# ---------------------------------------------------------------------------
# The eleven, as they come up (COMMS.md 6.2)
# ---------------------------------------------------------------------------
# Distress calls carry random names, so a rescue is not a roster. What she
# can do is say the name back -- which is the thing a counter never does.
THANKS = thread(
    "THANKS", "Somebody came up", "incoming",
    requires=["thanksDue", "met"], forbids=["quiet"],
    repeatable=True, retry=False,
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "It's Shepard. %2 is aboard. In quarantine, but aboard."),
             route=None,
             options=[opt("How are they?", "02"),
                      opt("Good.", "03")],
             clears=["thanksDue"]),
        node("02",
             say(S, "Thin. Filthy. Asked for coffee before a blanket."),
             say(S, "The Doctor says that's a good sign. I think he's lying."),
             options=[opt("Tell them they owe me one.", "03"),
                      opt("I'm glad.", "03")]),
        node("03",
             say(S, "I'll tell them. Thank you. Really. Shepard out."),),
    ])

LOST = thread(
    "LOST", "A beacon stopped", "incoming",
    requires=["lostDue", "met"], forbids=["quiet"],
    repeatable=True, retry=False,
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "It's Shepard. %2's beacon stopped an hour ago."),
             say(S, "I'm not calling to blame you. I'm calling so someone"),
             say(S, "hears the name out loud. That's all."),
             options=[opt("I couldn't get there.", "02"),
                      opt("I'm sorry.", "02"),
                      opt("There'll be others.", "03")],
             clears=["lostDue"]),
        node("02",
             say(S, "I know. Nobody could. Shepard out."),),
        node("03",
             say(S, "There will. That's the worst thing anyone's said today."),
             say(S, "It's also true. Shepard out."),),
    ])


# ---------------------------------------------------------------------------
# The spine (COMMS.md 6.2)
# ---------------------------------------------------------------------------
# Each is an incoming call after the one before it, and each has a worse
# opening for having been missed. None of them waits on a system the player
# might never build: the science reads the shuttle's Doctor if he is up, and
# the Adirondack's own if he is not.

# Come up / stay down. She explains why she stayed on the ground for five
# months. The player can argue, and should be able to lose the argument.
STAY = thread(
    "STAY", "Why she stayed", "incoming",
    after=("FIRST", 40), forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. Have you got a minute? A real one."),
             options=[opt("Go ahead.", "02"),
                      opt("I've got about thirty seconds.", "02"),
                      opt("Is something wrong?", "02")],
             timeout=60, silence="02"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "I tried you yesterday. I'll assume the dead were busy."),
             say(S, "Have you got a minute now?"),
             options=[opt("Go ahead.", "02"),
                      opt("Make it quick.", "02")],
             timeout=60, silence="02"),
        node("02",
             say(S, "Something you asked, or didn't. Why I stayed down."),
             say(S, "February to July, on the ground, with a ship overhead"),
             say(S, "begging me to come up. I owe somebody the answer."),
             options=[opt("Why did you?", "03"),
                      opt("You don't owe me anything.", "02X"),
                      opt("I figured it was the work.", "03")]),
        node("02X",
             say(S, "I owe the ten who stayed because I did. You'll do."),
             options=[opt("All right. Why?", "03")]),
        node("03",
             say(S, "Because it was the best work anybody in my field"),
             say(S, "will ever get to do. A living world, unannounced."),
             say(S, "And because I could pass. Six months of market days."),
             say(S, "The others could sit in orbit and read my notes."),
             say(S, "Ten of them didn't. They came down because I did."),
             options=[opt("That's on them, not you.", "04A"),
                      opt("You got them killed.", "04B"),
                      opt("Would you do it again?", "04C")]),
        node("04A",
             say(S, "That's kind. It's also not how command works."),
             say(S, "A lieutenant who plants a flag is a place to stand."),
             say(S, "I knew that. I planted it anyway."),
             options=[opt("Then you'd better start carrying it.", "05"),
                      opt("Okay.", "05")]),
        node("04B",
             say(S, "..."),
             say(S, "Some of them. Yes. Say it again if it helps you."),
             say(S, "It doesn't help me, but I'm not the one down there."),
             options=[opt("I'm sorry. That was cruel.", "04BS"),
                      opt("It's the truth.", "04BT")]),
        node("04BS",
             say(S, "It was fair. Cruel and fair aren't opposites."),
             options=[opt("...", "05")]),
        node("04BT",
             say(S, "It is. I'll be carrying it a long time."),
             say(S, "You don't have to carry it with me. That's all."),
             options=[opt("...", "05")]),
        node("04C",
             say(S, "Knowing what I know now? No."),
             say(S, "Knowing what I knew then? Yes. Every time."),
             say(S, "That's the whole problem with being a historian."),
             options=[opt("That's a terrible answer.", "05"),
                      opt("That's an honest one.", "05")]),
        node("05",
             say(S, "They've asked me to ask you to come up. For the file."),
             say(S, "I told them it's quarantine and you'd say no anyway."),
             say(S, "Would you? If the Doctor cleared it?"),
             options=[opt("Yes. Tomorrow.", "06Y"),
                      opt("No. Somebody has to stay down here.", "06N"),
                      opt("Ask me when he's cleared it.", "06L")]),
        node("06Y",
             say(S, "Then I hope he's quick. I really do."),
             say(S, "Until then the beacons are yours. Shepard out."),
             sets=["stayed"]),
        node("06N",
             say(S, "..."),
             say(S, "Now you know why I stayed. Shepard out."),
             sets=["stayed"]),
        node("06L",
             say(S, "Fair. I'll ask. He'll say not yet. Shepard out."),
             sets=["stayed"]),
    ])


# The eleven. Coordinates for crew on the ground, and what the channel knows
# about the ones who came up.
ELEVEN = thread(
    "ELEVEN", "The eleven", "incoming",
    after=("STAY", 40), forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. I want to talk about my people. The eleven."),
             options=[opt("Go on.", "02"),
                      opt("I'm listening.", "02")],
             timeout=60, silence="02"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Twice now. I'm going to keep calling about this one."),
             options=[opt("Go on.", "02")],
             timeout=60, silence="02"),
        node("02",
             route=[branch("02R", requires=["rescued>=1"]),
                    branch("02N")]),
        node("02R",
             say(S, "You've already brought some of them up. %2, last."),
             say(S, "I read the quarantine log every morning. Every name."),
             options=[opt("How many are left?", "03")]),
        node("02N",
             say(S, "Nobody has come up yet. That isn't a complaint."),
             say(S, "Beacons come and go. The shuttle hears them first."),
             options=[opt("How many are left?", "03")]),
        node("03",
             say(S, "I don't know. That's the honest answer."),
             say(S, "Eleven went down. The beacons don't say who's calling."),
             say(S, "Some are from people I trained. Some I barely knew."),
             say(S, "Some have stopped, and I don't know which of those"),
             say(S, "are dead and which just dropped the combadge."),
             options=[opt("What happens to them up there?", "04"),
                      opt("Why don't they walk to a clearing?", "03W"),
                      opt("I can't save everyone.", "03C")]),
        node("03W",
             say(S, "Some can't walk. Some are in a basement with forty"),
             say(S, "of the dead on the stairs. Clear ground is a luxury."),
             options=[opt("What happens to them up there?", "04")]),
        node("03C",
             say(S, "Nobody asked you to. Least of all me."),
             say(S, "One is a lot more than none. I'll take one."),
             options=[opt("What happens to them up there?", "04")]),
        node("04",
             say(S, "Quarantine. Showers, blood, the Doctor's bad jokes."),
             say(S, "Then a bunk, and a lot of staring at the viewport."),
             say(S, "Nobody has turned. Not one. He doesn't know why yet."),
             options=[opt("That's good news.", "05"),
                      opt("Yet.", "05Y")]),
        node("05Y",
             say(S, "Yet. You and he would get on."),
             options=[opt("...", "05")]),
        node("05",
             say(S, "Keep answering them. The ship pays you for each one."),
             say(S, "I pay you in gratitude, which is worth less. Shepard out."),
             sets=["elevenDone"]),
    ])


# The science: the graft. Morphogenic markers plus something the Doctor
# cannot place -- he is reading half a signature (LORE.md 1b, entry four).
SCIENCE = thread(
    "SCIENCE", "Half a signature", "incoming",
    after=("ELEVEN", 30), forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK -- TWO VOICES"),
             say(S, "Shepard. I've got the Doctor with me. Ours."),
             say(E, "Good afternoon. Or whatever it is on the surface."),
             options=[opt("Hello, Doctor.", "02"),
                      opt("Is this going to be bad news?", "02")],
             timeout=60, silence="02"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK -- TWO VOICES"),
             say(E, "I did say they wouldn't pick up. I said it twice."),
             say(S, "You did. Shuttle, have you got a moment?"),
             options=[opt("Sorry. Go on.", "02")],
             timeout=60, silence="02"),
        node("02",
             route=[branch("02E", requires=["emh"]),
                    branch("02S")]),
        node("02E",
             say(E, "Your shuttle's hologram has been sending me readings."),
             say(E, "Sensibly formatted, which I did not expect from a"),
             say(E, "copy of myself. I suppose I should be flattered."),
             options=[opt("What did he find?", "03")]),
        node("02S",
             say(E, "The crew you've sent up brought samples on their boots."),
             say(E, "Accidentally. I have made the most of them."),
             options=[opt("And?", "03")]),
        node("03",
             say(E, "The dead down there are not dead in the usual way."),
             say(E, "Something rebuilt them. Morphogenic markers, yes --"),
             say(E, "the Founders' own chemistry, which is bad enough."),
             say(E, "But there's a second signature underneath it."),
             say(E, "Something is holding the tissue together. Running it."),
             options=[opt("What is it?", "04"),
                      opt("In words I'd understand?", "03P")]),
        node("03P",
             say(E, "Two different things did this. I can see one of them."),
             say(E, "The other is a shape in the dark where one should be."),
             options=[opt("What's the shape?", "04")]),
        node("04",
             say(E, "I don't know. That's the sentence I dislike most."),
             say(E, "I can support the chemistry. I cannot support the author."),
             say(S, "He keeps saying that. It still sounds like Section 31."),
             say(E, "It sounds like whoever you have already decided on."),
             options=[opt("Could it be cured?", "05"),
                      opt("Who do you think it is?", "04W"),
                      opt("Does it matter who?", "04M")]),
        node("04W",
             say(E, "I think it is two people who never met. One made"),
             say(E, "the poison and one made the engine. Don't quote me."),
             options=[opt("Could it be cured?", "05")]),
        node("04M",
             say(S, "It matters to me. It'll matter to whoever gets home."),
             say(E, "It matters to a cure. Which is my department."),
             options=[opt("Could it be cured?", "05")]),
        node("05",
             say(E, "The living, if they're caught early? Your shuttle"),
             say(E, "does that already, at a price. The dead? No."),
             say(E, "I'm sorry. I would like to be wrong about that."),
             say(S, "Thank you, Doctor. Shuttle, Shepard out."),
             sets=["scienceDone"]),
    ])


# The denial: log five, now interactive. The Section 31 officer. The player
# may press or let it go, and neither answer changes what is true.
DENIAL = thread(
    "DENIAL", "Commander Okafor", "incoming",
    after=("SCIENCE", 36), forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK -- UNLOGGED"),
             say(O, "Commander Okafor. You don't know me. Shepard does."),
             say(O, "She tells me you have questions about my employer."),
             options=[opt("Section 31.", "02"),
                      opt("I don't have any questions.", "01Q"),
                      opt("Where's Shepard?", "01S")],
             timeout=60, silence="01Q"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK -- UNLOGGED"),
             say(O, "Okafor. I called once already. I don't usually."),
             options=[opt("Section 31.", "02"),
                      opt("I don't have any questions.", "01Q")],
             timeout=60, silence="01Q"),
        node("01S",
             say(O, "Asleep, for once. This is not her conversation."),
             options=[opt("Section 31.", "02"),
                      opt("Then I don't want it.", "01Q")]),
        node("01Q",
             say(O, "Then I'll answer the one you didn't ask."),
             options=[opt("Go on.", "02")]),
        node("02",
             say(O, "It wasn't us. It wasn't anyone I know of."),
             say(O, "We did not disable this ship. We did not do that"),
             say(O, "to the county below you. We were as blind as she was."),
             options=[opt("That's exactly what you'd say.", "03P"),
                      opt("I believe you.", "03B"),
                      opt("Why tell me at all?", "03W")]),
        node("03P",
             say(O, "It is. If it were us, I would not be calling you."),
             say(O, "I'd be letting you believe it. It's cheaper."),
             options=[opt("Prove it.", "04P"),
                      opt("...Fine.", "05")]),
        node("04P",
             say(O, "I can't. There is nothing I could show you that"),
             say(O, "an organisation like mine could not also forge."),
             say(O, "That is the problem with us. We earned it."),
             options=[opt("Then why should anyone trust you?", "04T"),
                      opt("All right. I'll let it go.", "05")],
             sets=["pressed"]),
        node("04T",
             say(O, "They shouldn't. Believe the evidence, not me."),
             say(O, "The Doctor's reading half a signature. Follow that."),
             options=[opt("...", "05")]),
        node("03B",
             say(O, "Don't, particularly. Believe what the Doctor finds."),
             options=[opt("...", "05")]),
        node("03W",
             say(O, "Because she will not hear it from me any more."),
             say(O, "And because whoever did this is still out there."),
             options=[opt("...", "05")]),
        node("05",
             say(O, "Five months she's been angry at the wrong people."),
             say(O, "Somebody left the room before we were blinded,"),
             say(O, "and came back for the test. I want to know who."),
             say(O, "Okafor out."),
             sets=["denialDone"]),
    ])


# The archive: Phlox's omicron note, 2153. Paperwork, not a miracle -- the
# right job for a hologram who reads everything.
ARCHIVE = thread(
    "ARCHIVE", "Paperwork", "incoming",
    after=("DENIAL", 36), forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK -- SICKBAY"),
             say(E, "Shuttle. The Doctor. I have been reading. Don't sigh."),
             options=[opt("Reading what?", "02"),
                      opt("I didn't sigh.", "02")],
             timeout=60, silence="02"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK -- SICKBAY"),
             say(E, "I have a finding and nobody to tell it to. Please."),
             options=[opt("Go on, then.", "02")],
             timeout=60, silence="02"),
        node("02",
             say(E, "Medical logs. The old ones. Two hundred and eighty"),
             say(E, "years of them, filed and unread, which is a crime."),
             say(E, "In 2153 a Denobulan named Phlox stopped nanoprobes."),
             say(E, "Borg nanoprobes, in a crewman, with omicron radiation."),
             say(E, "He wrote it down. Nobody ever read it. Until now."),
             options=[opt("Nanoprobes? That's the second signature?", "03"),
                      opt("What does that mean for us?", "03"),
                      opt("Who's Phlox?", "02P")]),
        node("02P",
             say(E, "A colleague. Before my time, and everybody's."),
             say(E, "He wrote beautifully. I envy that more than anything."),
             options=[opt("And the nanoprobes?", "03")]),
        node("03",
             say(E, "It fits the shape I couldn't see. Something Borg is"),
             say(E, "holding those bodies together. Rebuilding. Running."),
             say(E, "And omicron radiation takes nanoprobes apart."),
             options=[opt("So you can cure it.", "04"),
                      opt("So we can kill them.", "04K")]),
        node("04K",
             say(E, "They're already dead. You'd be switching them off."),
             say(E, "I'm not sure that's different. I'm not sure it isn't."),
             options=[opt("Can you cure the living?", "04")]),
        node("04",
             say(E, "No. I want to be very clear, because it's tempting."),
             say(E, "It's a note in a file. It needs a laboratory, months,"),
             say(E, "and a ship that can go somewhere. We have none of it."),
             say(E, "But it tells us what this is made of. That matters."),
             options=[opt("Thank you, Doctor.", "05"),
                      opt("Tell Shepard.", "05")]),
        node("05",
             say(E, "I have. She cried, which I am choosing to take well."),
             say(E, "Sickbay out."),
             sets=["archiveDone"]),
    ])


# The reveal: a rogue Changeling, the Founders' virus grafted to Borg
# nanoprobes, and the plan for the Federation worlds. The logs have told it;
# this is what it means now that she knows.
REVEAL = thread(
    "REVEAL", "The one who left the Link", "incoming",
    after=("ARCHIVE", 48), forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. Are you somewhere you can sit down?"),
             options=[opt("I'm sitting.", "02"),
                      opt("No. Talk anyway.", "02")],
             timeout=60, silence="02"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. Please pick up. This is the one that matters."),
             options=[opt("I'm here.", "02")],
             timeout=60, silence="02"),
        node("02",
             say(S, "We put the pieces together. Okafor, the Doctor, me."),
             say(S, "The Founders' virus. Borg nanoprobes. One engine."),
             say(S, "A Changeling left the Great Link, years ago, on purpose."),
             say(S, "It knew what Section 31 did to its people. The virus."),
             say(S, "And it spent sixty years making that into this."),
             options=[opt("I know. It's on your last tape.", "03T",
                          requires=["watched:TREK_LogSix"]),
                      opt("A Changeling did all this?", "03"),
                      opt("Why here?", "04")]),
        node("03T",
             say(S, "Then you know I left the chair where it was. Good."),
             say(S, "What the tape doesn't have is the part that's next."),
             options=[opt("What's next?", "05")]),
        node("03",
             say(S, "One. Alone. That's the part I can't get past."),
             say(S, "One person, grieving for long enough, did all of it."),
             options=[opt("Why here?", "04")]),
        node("04",
             say(S, "Because nobody was watching. Nothing filed. No relay."),
             say(S, "An order saying do not interfere. The Prime Directive"),
             say(S, "is what left this world undefended. I helped write it."),
             say(S, "And because your world is the closest thing to Earth"),
             say(S, "anybody has ever found. It's a rehearsal."),
             options=[opt("A rehearsal for what?", "05")]),
        node("05",
             say(S, "For the Federation. The worlds that did this to it."),
             say(S, "A horde is a Collective with no Queen, and nobody at"),
             say(S, "home knows it exists. We can't warn them. Comms dark."),
             options=[opt("Then we have to get word out.", "06"),
                      opt("What do you want me to do?", "06"),
                      opt("It's not my Federation.", "06N")]),
        node("06N",
             say(S, "No. It's the one that watched you die and took notes."),
             say(S, "You don't owe it anything. I'm not going to ask."),
             options=[opt("...", "06")]),
        node("06",
             say(S, "Stay alive. Bring my people up. Keep the tapes."),
             say(S, "If a ship ever does come, I want the whole record."),
             say(S, "Not a report. A record. Everything, in order."),
             say(S, "Shepard out."),
             sets=["revealDone"]),
    ])


# ---------------------------------------------------------------------------
# The clue chain (COMMS.md 6.3, LORE.md 1c)
# ---------------------------------------------------------------------------
# Starfleet's answer for this planet is a Q, and it is wrong. Nobody says so:
# she mentions it early, less as the fragments come in, and not at all once
# they are all on tape. The theory dies of accumulation.
CLUE = thread(
    "CLUE", "Something old", "incoming",
    requires=["clueSeen", "met"], forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. Your probe flagged something. Not dilithium."),
             options=[opt("What is it?", "02"),
                      opt("Is it dangerous?", "02")],
             timeout=60, silence="02"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. The probe's signal. Have you looked yet?"),
             options=[opt("Not yet. What is it?", "02")],
             timeout=60, silence="02"),
        node("02",
             say(S, "A holo emitter. A small one, very old. Three hundred"),
             say(S, "years, give or take, in a world that shouldn't have"),
             say(S, "a holo emitter at all. Somebody left a recording."),
             options=[opt("Who?", "03"),
                      opt("Why would anyone do that here?", "03")]),
        node("03",
             say(S, "There's a file on this planet. You'll have heard"),
             say(S, "of the Q. Starfleet's view is that one made this place."),
             say(S, "A copy of Earth, dropped here, for a joke or a test."),
             say(S, "It's the only category they have. It's not a bad one."),
             options=[opt("Do you believe that?", "04"),
                      opt("A Q? Really?", "04")]),
        node("04",
             say(S, "I believe I'd like to hear the recording."),
             say(S, "Bring it to me, off the PADD. Hail me with it on you."),
             say(S, "And don't die with it. It's the only one we know of."),
             options=[opt("I'll find it.", "05"),
                      opt("No promises.", "05")]),
        node("05",
             say(S, "Good hunting. Shepard out."),
             sets=["clueTold"]),
    ])


def fragment(n, lines, count_to="COUNT"):
    """A fragment's own node: what she makes of it, and the conversion."""
    return node(f"F{n}", *lines, convert=n,
                options=[opt("Is it all there?", count_to),
                         opt("...", count_to)])


# The conversion. A hail with a fragment on you: one per call, the first
# the holder carries. "Hang on. I can put that on magnetic tape."
CONVERT = thread(
    "CONVERT", "On tape", "hail",
    requires=["carrying"], repeatable=True, cooldown=1,
    nodes=[
        node("01",
             route=[branch("HANG", forbids=["converted>=1"]),
                    branch("PICK")]),
        node("HANG",
             say(CARD, "HAILING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. You found it? Hold it up to the PADD."),
             say(S, "..."),
             say(S, "Hang on. I can put that on magnetic tape."),
             say(S, "It's what I've been doing with holos all year."),
             options=[opt("Do it.", "PICK"),
                      opt("On tape?", "HANGT")]),
        node("HANGT",
             say(S, "The television takes tape. So everything goes on tape."),
             say(S, "Once it's on the shelf, it can't be lost. Ready?"),
             options=[opt("Do it.", "PICK")]),
        node("PICK",
             route=[branch("F1", requires=["carrying:1"]),
                    branch("F2", requires=["carrying:2"]),
                    branch("F3", requires=["carrying:3"]),
                    branch("F4", requires=["carrying:4"]),
                    branch("F5", requires=["carrying:5"]),
                    branch("F6", requires=["carrying:6"]),
                    branch("NONE")]),
        node("NONE",
             say(S, "I'm not reading one on you. Did you drop it?"),
             say(S, "Hail me again when it's in your hands. Shepard out."),),
        fragment(1, [
            say(S, "It's a man. Old, recording himself. It's numbered one."),
            say(S, "He says he was something that doesn't die, once."),
            say(S, "Curious about a species that does. I'm dubbing it now."),
        ]),
        fragment(2, [
            say(S, "Number two. He's talking about a woman. Gently."),
            say(S, "He says his kind can't love anything. And then he did."),
            say(S, "It's going on tape. You'll want to watch this one."),
        ]),
        fragment(3, [
            say(S, "Three. It's about her dying. A war over furs."),
            say(S, "Fought by people she'd never met, miles away."),
            say(S, "I'm putting it on tape. I'm not going to watch it twice."),
        ]),
        fragment(4, [
            say(S, "Four. He copied it. The land, the river, the falls."),
            say(S, "And the people. He copied the people. And her."),
            say(S, "That's-- I need a minute. It's going on tape."),
        ]),
        fragment(5, [
            say(S, "Five. He gave it up. The power. Made himself mortal"),
            say(S, "so he could grow old with her. And he wonders if he"),
            say(S, "ever told her what she was. Taping it now."),
        ]),
        fragment(6, [
            say(S, "Six. He's old. Dying, I think. And he's talking to"),
            say(S, "whoever found this. To you, I suppose. Not by name."),
            say(S, "He knew the world would outlive them both. Taping it."),
        ]),
        node("COUNT",
             route=[branch("ALL", requires=["converted>=6"]),
                    branch("LAST", requires=["converted>=5"]),
                    branch("MID", requires=["converted>=3"]),
                    branch("EARLY", requires=["converted>=2"]),
                    branch("FIRSTONE")]),
        node("FIRSTONE",
             say(S, "It'll be on the shelf by the television. One of six,"),
             say(S, "he says. The Q file is going to hate this. Or love it."),
             say(S, "Find the rest if you can. Shepard out."),),
        node("EARLY",
             say(S, "On the shelf. Out of order, but he numbered them,"),
             say(S, "bless him. A historian's dream. Shepard out."),),
        node("MID",
             say(S, "That's half of him, near enough, on the shelf."),
             say(S, "Whoever he was, he meant these to be found."),
             say(S, "Shepard out."),),
        node("LAST",
             say(S, "One left. I've been counting days by these."),
             say(S, "Shepard out."),),
        node("ALL",
             say(S, "That's all six. The whole of him. On the shelf."),
             say(S, "..."),
             say(S, "I'll call you when I've listened. Shepard out."),),
    ])


# All six on tape. Nobody announces that the Q theory is wrong; she just
# says his name, which the fragments gave her and the file never had.
GOLD = thread(
    "GOLD", "Tucker Gold", "incoming",
    requires=["converted>=6", "met"], forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. I've watched them. All six. Twice."),
             options=[opt("And?", "02"),
                      opt("Me too.", "02")],
             timeout=60, silence="02"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. When you have a minute. About the six."),
             options=[opt("I have a minute.", "02")],
             timeout=60, silence="02"),
        node("02",
             say(S, "His name was Tucker Gold. The name he chose, when he"),
             say(S, "stopped being what he was. That's in number five."),
             say(S, "There's a case like him on file. Rana Four. A Douwd."),
             say(S, "Beings that can make a world out of grief. Or end one."),
             options=[opt("He made all this? The whole county?", "03"),
                      opt("So it wasn't a Q.", "02Q"),
                      opt("Does it change anything?", "04")]),
        node("02Q",
             say(S, "I'm writing it up. I'm not going to write it that way."),
             say(S, "I'm going to write what he said. They can decide."),
             options=[opt("He made all this?", "03")]),
        node("03",
             say(S, "The land and the river, and the people on it. Then"),
             say(S, "he put it down and grew old with her, and the towns"),
             say(S, "grew on their own for three hundred years."),
             say(S, "Your parents were real. Your town was real. Is."),
             options=[opt("It doesn't feel any different.", "04"),
                      opt("I needed to hear that.", "04"),
                      opt("I'm not from here.", "04")]),
        node("04",
             say(S, "It's real either way. That's the only line I'd hold."),
             say(S, "The place was made. The people weren't. Nobody made you."),
             say(S, "Thank you for bringing him in. Shepard out."),
             sets=["goldDone"]),
    ])


# The last call, once both halves of the story are in: the world made by
# grief, being unmade by grief. Both makers the last of something.
GRIEF = thread(
    "GRIEF", "Two griefs", "incoming",
    requires=["revealDone", "goldDone"], forbids=["quiet"],
    entries=["01", "01M"],
    nodes=[
        node("01",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. Nothing's wrong. I just want to say a thing"),
             say(S, "out loud to somebody who'll understand it."),
             options=[opt("Go on.", "02"),
                      opt("I'm listening.", "02")],
             timeout=60, silence="02"),
        node("01M",
             say(CARD, "INCOMING -- U.S.S. ADIRONDACK"),
             say(S, "Shepard. No emergency. When you've got a second."),
             options=[opt("I've got one.", "02")],
             timeout=60, silence="02"),
        node("02",
             say(S, "A Douwd made this county because he couldn't bear"),
             say(S, "one death. A Changeling is emptying it because it"),
             say(S, "couldn't bear a genocide. Made by grief, and unmade."),
             say(S, "Both of them the last of something. Both alone."),
             options=[opt("And us?", "03"),
                      opt("That's bleak.", "03"),
                      opt("Grief doesn't excuse it.", "03E")]),
        node("03E",
             say(S, "No. It explains it. That's all I'm good for."),
             options=[opt("...", "03")]),
        node("03",
             say(S, "We're the ones who aren't alone. That's the difference."),
             say(S, "A hundred and forty up here. You down there."),
             say(S, "The ones you've brought up. We have each other."),
             say(S, "It's not a plan. It's just true. Shepard out."),
             sets=["griefDone"]),
    ])


# Priority, top first. The rescue reactions come before the spine because
# they are about somebody who just came up; the conversion before the idle
# hail, because a player holding a fragment is hailing about the fragment.
THREADS = [FIRST, THANKS, LOST, CLUE, STAY, ELEVEN, SCIENCE, DENIAL, ARCHIVE,
           REVEAL, GOLD, GRIEF, CONVERT, QUIET, RESUME]
