"""The phaser's beam and the spark where it lands.

    python tools/gen_phaser_beam.py TrekShuttle/42

Writes two textures the beam overlay draws in screen space (PHASERS.md 5):

    media/ui/TREK_PhaserBeam.png    a strip, stretched and turned along the
                                    line from the emitter to the target
    media/ui/TREK_PhaserSpark.png   the impact, drawn at the target

and `design/art/ui/phaser_beam_sheet.png`, the beam and spark composited over
the ground the game draws, at two zooms. **The sheet is the point** -- the
torpedo's lesson (tools/gen_torpedo_flight.py) is that a bright effect judged
on its own passes, and then vanishes over a pale roof.

Three decisions, all carried over from the torpedo and the reticle:

- **Drawn, not generated by an image model.** A beam is a hard bright line
  read at a few pixels thick over a moving world; what survives that is a
  hard core with a clean falloff, which is arithmetic, not illustration.
- **White-cored.** The Lua tints at draw time and a tint multiplies, so any
  colour baked in would fight the one the draw is saying. `TINT` below is
  the colour the sheet previews and the Lua should use.
- **A dark skirt** outside the glow: invisible on dark ground, and the only
  thing that makes the beam read on a pale one.

The strip is uniform along its length on purpose. It is stretched to any
length at draw time, and anything that varied along it would stretch with
it; the life in the beam -- flicker, a crawl of brightness -- belongs in the
Lua, which can move it every frame.
"""
import math
import os
import random
import sys

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)

BEAM_W, BEAM_H = 32, 16       # the strip; only its vertical profile matters
CORE = 1.3                    # half-thickness drawn at full white, in px
GLOW = 5.2                    # half-thickness at which the glow has faded
SKIRT_END = 7.9               # half-thickness at which the skirt has faded
SKIRT = (10, 12, 22)          # very dark blue: a shadow, not a hole
SKIRT_ALPHA = 44              # 70 drew a hard grey box on a pale roof

# The recipe the overlay follows, and the sheet previews: the same strip
# twice. A tint multiplies, so one tinted draw can never have a white-hot
# middle -- the first sheet's beam was orange from edge to edge.
GLOW_PASS = 1.0               # thickness factor, tinted TINT
CORE_PASS = 0.42              # thickness factor, untinted (white), on top
CORE_ALPHA = 0.9
IMPACT = 1.7                  # spark size at the target, x SPARK px at zoom 1:
                              # at 1.0 it was barely wider than the beam, and
                              # the cut point is where the eye goes
MUZZLE = 0.55                 # the flare at the emitter

SPARK = 32
TINT = (255, 120, 40)         # phaser orange, what the Lua multiplies by


def profile(d):
    """(rgb, alpha) at distance d from the beam's centre line, or the spark's
    centre. White core, a glow that fades out, then the dark skirt."""
    if d <= CORE:
        return (255, 255, 255), 255
    if d <= GLOW:
        t = (d - CORE) / (GLOW - CORE)
        a = int(255 * (1.0 - t) ** 1.8)
        # The glow is white too; it is the tint that colours it. It fades to
        # a slightly lower value so the core stays the brightest thing.
        v = int(255 - 40 * t)
        return (v, v, v), max(a, int(SKIRT_ALPHA * t))
    if d <= SKIRT_END:
        t = (d - GLOW) / (SKIRT_END - GLOW)
        return SKIRT, int(SKIRT_ALPHA * (1.0 - t) ** 2)
    return (0, 0, 0), 0


def beam_strip():
    img = Image.new("RGBA", (BEAM_W, BEAM_H), (0, 0, 0, 0))
    px = img.load()
    cy = (BEAM_H - 1) / 2.0
    for y in range(BEAM_H):
        rgb, a = profile(abs(y - cy))
        for x in range(BEAM_W):
            px[x, y] = rgb + (a,)
    return img


def spark():
    """The impact: the beam's own profile made round, with four soft rays so
    it reads as something being cut rather than a second torpedo. (Six hard
    ones, the first draft, read as an arrowhead on every beam.)"""
    img = Image.new("RGBA", (SPARK, SPARK), (0, 0, 0, 0))
    px = img.load()
    c = (SPARK - 1) / 2.0
    for y in range(SPARK):
        for x in range(SPARK):
            dx, dy = x - c, y - c
            d = math.hypot(dx, dy)
            ang = math.atan2(dy, dx)
            # rays stretch the profile outward along six directions
            ray = max(0.0, math.cos(2 * ang + 0.4)) ** 10
            reach = 1.0 + 0.6 * ray
            rgb, a = profile(d / reach * (GLOW / 6.0) * 1.15)
            px[x, y] = rgb + (a,)
    return img


def tinted(img, tint):
    r, g, b, a = img.split()
    r = r.point(lambda v: v * tint[0] // 255)
    g = g.point(lambda v: v * tint[1] // 255)
    b = b.point(lambda v: v * tint[2] // 255)
    return Image.merge("RGBA", (r, g, b, a))


def ground(w, h, rgb, seed):
    """A flat ground colour with a little clutter, so the beam is judged over
    something like the game's tiles rather than a perfect fill."""
    rng = random.Random(seed)
    img = Image.new("RGBA", (w, h), rgb + (255,))
    d = ImageDraw.Draw(img)
    for _ in range(w * h // 180):
        x, y = rng.randrange(w), rng.randrange(h)
        k = rng.uniform(-18, 18)
        c = tuple(max(0, min(255, int(v + k))) for v in rgb)
        d.rectangle((x, y, x + rng.randrange(2, 7), y + rng.randrange(1, 4)),
                    fill=c + (255,))
    return img


def draw_beam(canvas, strip, spark_img, start, end, zoom, tint):
    """What the overlay will do, so the sheet shows the game's beam and not a
    nicer one: the strip stretched along start->end and turned, drawn twice
    (tinted glow, then an untinted core on top), a small flare at the emitter
    to cover the strip's square start, and the spark on the target.
    Thickness divides by zoom, as the torpedo's sizes do."""
    (x0, y0), (x1, y1) = start, end
    length = max(1, int(math.hypot(x1 - x0, y1 - y0)))
    angle = -math.degrees(math.atan2(y1 - y0, x1 - x0))
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2

    def band(factor, colour, alpha):
        thick = max(2, int(BEAM_H * factor / zoom))
        b = tinted(strip, colour).resize((length, thick), Image.BILINEAR)
        if alpha < 1.0:
            b.putalpha(b.getchannel("A").point(lambda v: int(v * alpha)))
        b = b.rotate(angle, resample=Image.BICUBIC, expand=True)
        canvas.alpha_composite(b, (int(cx - b.width / 2), int(cy - b.height / 2)))

    def flare(x, y, size, colour):
        s = max(4, int(size / zoom))
        f = tinted(spark_img, colour).resize((s, s), Image.BILINEAR)
        canvas.alpha_composite(f, (int(x - s / 2), int(y - s / 2)))

    band(GLOW_PASS, tint, 1.0)
    band(CORE_PASS, (255, 255, 255), CORE_ALPHA)
    flare(x0, y0, SPARK * MUZZLE, tint)
    flare(x1, y1, SPARK * IMPACT, tint)
    flare(x1, y1, SPARK * IMPACT * 0.45, (255, 255, 255))


def sheet(strip, spark_img, path):
    grounds = [("grass", (74, 92, 52)), ("tarmac", (70, 70, 72)),
               ("pale roof", (178, 170, 156)), ("night", (18, 20, 28))]
    cw, ch = 300, 150
    out = Image.new("RGBA", (cw * 4, ch * 2 + 24), (28, 30, 36, 255))
    d = ImageDraw.Draw(out)
    for gi, (label, rgb) in enumerate(grounds):
        for zi, zoom in enumerate((1.0, 2.0)):
            cell = ground(cw, ch, rgb, seed=gi * 7 + zi)
            # a bolt at a shallow angle and a sustained cut at a steep one
            draw_beam(cell, strip, spark_img, (20, 120), (270, 70), zoom, TINT)
            draw_beam(cell, strip, spark_img, (40, 30), (150, 135), zoom, TINT)
            out.paste(cell, (gi * cw, 24 + zi * ch))
        d.text((gi * cw + 6, 6), f"{label}: zoom 1 (top), zoom 2 (below)",
               fill=(210, 210, 210, 255))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    out.convert("RGB").save(path, optimize=True)


def main(root):
    ui = os.path.join(root, "media", "ui")
    os.makedirs(ui, exist_ok=True)
    strip, spk = beam_strip(), spark()
    strip.save(os.path.join(ui, "TREK_PhaserBeam.png"), optimize=True)
    spk.save(os.path.join(ui, "TREK_PhaserSpark.png"), optimize=True)
    vet = os.path.join(REPO, "design", "art", "ui", "phaser_beam_sheet.png")
    sheet(strip, spk, vet)
    print("wrote media/ui/TREK_PhaserBeam.png and TREK_PhaserSpark.png")
    print("wrote", os.path.relpath(vet, REPO),
          "-- grass / road / roof / night, at two zooms. Look at it.")


if __name__ == "__main__":
    main(sys.argv[1])
