"""The hydroponics crops, rendered at every growth stage (FARMING.md 6.1).

    python tools/gen_adirondack_crops.py

Writes design/tiles/2x/trek_adirondack_03.png, its index
design/tiles/trek_adirondack_03.json and a contact sheet at
design/art/adirondack/crops_sheet.png.

**One mesh per crop, grown by scale.** Each crop is a TRELLIS mesh of the mature
plant (its concept and mesh are in the ledger, tools/adirondack_jobs.py),
rendered with tools/isorender.py at eight sizes -- vanilla farming's eight
stages, where 5 is ready to harvest and 6 fully grown -- so the same plant
visibly grows in its tray rather than being eight unrelated drawings.

Vanilla wants five sprite tables per crop, each eight long (MOFarming counts
all five): healthy, unhealthy, dying, dead and trampled. The last four are the
healthy renders tinted -- yellowing, browning, grey -- and trampled reuses dead.
That is 32 tiles a crop.

**They stand in the tray.** A crop tile is drawn on the square of a hydroponic
tray (the tray is furniture, trek_adirondack_02), so the plant starts at the
height of the tray's growing medium, TRAY_TOP, not at the floor.
"""
import json
import os
import sys

import numpy as np
from PIL import Image, ImageDraw

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_adirondack_furniture as F  # noqa: E402
import isorender as iso  # noqa: E402

ROOT = F.ROOT
SHEET = "trek_adirondack_03"
OUT = os.path.join(F.TILES, SHEET + ".png")
INDEX = os.path.join(ROOT, "design", "tiles", SHEET + ".json")
CONTACT = os.path.join(F.ART, "crops_sheet.png")
CW, CH = 128, 256

# The top of the tray's growing medium, in world units (the tray is 0.55 tall).
TRAY_TOP = 0.47

# Each crop: its mesh, its mature height and spread (world units), and the
# vanilla crop it borrows its growing numbers from (TREK_Farm.lua).
CROPS = [
    ("TrekTeaBush", "crop_tea", 1.00, 0.78),
    ("TrekBergamot", "crop_bergamot", 1.20, 0.78),
    ("TrekKlingonCoffee", "crop_klingon_coffee", 1.25, 0.72),
    ("TrekPlomeek", "crop_plomeek", 0.60, 0.70),
    ("TrekLeolaRoot", "crop_leola", 0.80, 0.70),
    ("TrekAndorianTuber", "crop_andorian_tuber", 0.70, 0.72),
    ("TrekHasperatPepper", "crop_hasperat", 0.90, 0.75),
]

# Size of each of the eight stages against the mature plant.
STAGE_SCALE = [0.16, 0.28, 0.42, 0.58, 0.80, 1.00, 1.00, 0.96]
# A light cast on the late stages: 7 is setting seed, 8 is going over.
STAGE_TINT = [None, None, None, None, None, None, ((214, 180, 90), 0.12), ((150, 110, 60), 0.22)]

TINTS = {
    "unhealthy": ((205, 190, 70), 0.38, 0.25),   # colour, blend, desaturate
    "dying": ((140, 100, 50), 0.55, 0.45),
    "dead": ((95, 80, 60), 0.78, 0.85),
}


def tint(img, colour, amount, desat=0.0):
    arr = np.asarray(img).astype(np.float32)
    rgb, a = arr[..., :3], arr[..., 3:]
    if desat:
        grey = rgb.mean(axis=2, keepdims=True)
        rgb = rgb * (1 - desat) + grey * desat
    rgb = rgb * (1 - amount) + np.array(colour, np.float32) * amount
    return Image.fromarray(np.concatenate([rgb, a], axis=2).clip(0, 255).astype(np.uint8), "RGBA")


def render_stage(v, faces, uv, img, height, spread, scale):
    """One stage: the plant fitted to scale x its mature size, centred on the
    square and standing on the tray's growing medium."""
    w = max(0.08, spread * scale)
    world, _ = F.place(v, "S", w, w, height * scale, front="+z", z0=TRAY_TOP, back=False, inset=0.0)
    off = (1.0 - w) / 2.0
    world = world + np.array([off, off, 0.0])
    out = iso.render_mesh(world, faces, uv, img, (1, 1))
    return out.get((0, 0))


def soil_tile():
    """A disc of dark growing medium at the tray's top, in the tray's middle."""
    import random
    rnd = random.Random(1701)
    t = Image.new("RGBA", (CW, CH), (0, 0, 0, 0))
    d = ImageDraw.Draw(t)
    lift = TRAY_TOP * (192 / 2.449)
    cx, cy = 64, 224 - lift
    rx, ry = 26, 13
    d.ellipse((cx - rx, cy - ry, cx + rx, cy + ry), fill=(52, 38, 28, 255))
    for _ in range(90):
        a, r = rnd.uniform(0, 6.283), rnd.random() ** 0.5
        x = cx + np.cos(a) * r * (rx - 2)
        y = cy + np.sin(a) * r * (ry - 1)
        shade = rnd.randint(30, 80)
        d.point((x, y), fill=(shade + 14, shade, shade - 12, 255))
    return t


def write_lua(index):
    """TREK_FarmSprites.lua: every crop's five sprite tables, by name, for
    TREK_Farm to hand to vanilla farming."""
    lines = ["-- GENERATED by tools/gen_adirondack_crops.py -- do not edit.",
             "-- The hydroponics crops' growth sprites (FARMING.md 6.1): five tables of",
             "-- eight per crop, as vanilla farming wants them, and the tray's soil.",
             "TREK_FarmSprites = {"]
    for crop in sorted(k for k in index if not k.startswith("_")):
        lines.append("    %s = {" % crop)
        for table in ("sprite", "unhealthy", "dying", "dead", "trampled"):
            names = ", ".join('"%s_%d"' % (SHEET, i) for i in index[crop][table])
            lines.append("        %s = { %s }," % (table, names))
        lines.append("    },")
    lines.append("}")
    lines.append('TREK_FarmSoil = "%s_%d"' % (SHEET, index["_soil"]))
    lines.append("return TREK_FarmSprites")
    path = os.path.join(ROOT, "TrekShuttle", "42", "media", "lua", "shared", "TREK", "TREK_FarmSprites.lua")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")


def main():
    tiles, index, rows = [], {}, []

    def add(t):
        tiles.append(t)
        return len(tiles) - 1

    for prop, mesh, height, spread in CROPS:
        path = os.path.join(F.MESHES, mesh + ".glb")
        if not os.path.exists(path):
            raise SystemExit("no mesh for %s: fetch it (tools/adirondack_jobs.py fetch)" % mesh)
        v, faces, uv, img = F.load_glb(path)
        healthy = []
        for stage, scale in enumerate(STAGE_SCALE):
            t = render_stage(v, faces, uv, img, height, spread, scale)
            if t is None:
                raise SystemExit("%s stage %d rendered nothing" % (prop, stage + 1))
            if STAGE_TINT[stage]:
                t = tint(t, *STAGE_TINT[stage])
            healthy.append(t)
        entry = {"sprite": [add(t) for t in healthy]}
        for kind, (colour, amount, desat) in TINTS.items():
            entry[kind] = [add(tint(t, colour, amount, desat)) for t in healthy]
        entry["trampled"] = list(entry["dead"])
        index[prop] = entry
        rows.append((prop, healthy))
        print("rendered", prop)

    # The tray's soil, for a tray that is primed and waiting for a seed.
    # Vanilla's plowed-earth sprite is drawn at floor level, beside the tray
    # rather than in it; TREK_Farm swaps this in after it plows a tray.
    index["_soil"] = add(soil_tile())

    n_rows = (len(tiles) + 7) // 8
    sheet = Image.new("RGBA", (CW * 8, CH * n_rows), (0, 0, 0, 0))
    for k, t in enumerate(tiles):
        sheet.paste(t, ((k % 8) * CW, (k // 8) * CH))
    tmp = OUT + ".tmp.png"
    sheet.save(tmp)
    os.replace(tmp, OUT)
    with open(INDEX, "w") as f:
        json.dump(index, f, indent=1, sort_keys=True)
    write_lua(index)

    # The contact sheet: every crop's eight stages in a row, cropped to the
    # plant, then the three tints of the mature stage.
    cell = 96
    c = Image.new("RGBA", (cell * 11 + 180, cell * len(rows)), (44, 46, 54, 255))
    d = ImageDraw.Draw(c)
    for r, (prop, healthy) in enumerate(rows):
        d.text((6, r * cell + 6), prop, fill=(235, 235, 235, 255))
        ents = index[prop]
        shown = healthy + [tiles[ents[k][5]] for k in ("unhealthy", "dying", "dead")]
        for k, t in enumerate(shown):
            crop = t.crop((0, 60, 128, 256)).resize((cell * 128 // 196, cell), Image.LANCZOS)
            c.alpha_composite(crop, (180 + k * cell, r * cell))
    c.save(CONTACT)
    print("wrote %d tiles for %d crops -> %s" % (len(tiles), len(index), os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
