"""The photon torpedo as it looks in flight.

    python tools/gen_torpedo_flight.py TrekShuttle/42

Writes media/ui/TREK_TorpedoFlight.png -- the glowing head that TREK_Torpedo
.lua draws between the ship and the target, and again, fainter and smaller,
for each echo of its trail.

**Drawn, not generated by an image model**, for the reason gen_reticle.py and
gen_radial_icons.py both give: this is a small bright thing read at about
twenty pixels over a moving, cluttered world, and what survives that is a hard
core with a clean falloff around it. An image model paints soft edges, cannot
emit alpha, and would hand back a lens flare with a background attached.

**It is drawn white-cored on purpose**, like the reticle: TREK_Torpedo.lua
tints it at draw time and a tint multiplies, so any colour baked in here would
fight the one the draw is trying to say. The core stays near-white so the tint
reads as the *glow* colour rather than washing the whole sprite flat.

**It is a glow with a dark skirt, and the skirt was not in the first draft.**
The torpedo is composited over grass, roads, roofs and darkness within one
second of flight, and a purely bright sprite has contrast against three of
those and almost none against a pale roof -- which is exactly what a shuttle
firing from above the buildings spends its time crossing. The contact sheet
sheet() writes is what showed it; the source never would have. So the glow
fades out through a very dark ring, invisible on dark ground and the making of
it on light. Run the script and look at the sheet before changing any of the
five constants above.

Note this is **not** media/ui/TREK_Torpedo.png. That one is a 48px flat radial
*menu* icon from gen_radial_icons.py, left behind when the radial slice was
removed, and it is the wrong shape for this job: a menu icon is a silhouette
read against a dark ring, a projectile is a light source read against anything
at all. PHOTON_TORPEDOS.md section 9 still lists that file as orphaned.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngwrite import Image

S = 24                  # about half a tile at default zoom
CX = CY = (S - 1) / 2.0

CORE = 2.1              # radius drawn at full white
GLOW = 8.0              # radius at which the bright glow has faded out
HALO = 11.8             # radius at which the dark skirt has faded out
FALLOFF = 2.2           # >1 tightens the glow toward the core

# The dark skirt. Nearly black, and deliberately not pure black: a pure black
# ring reads as a hole punched in bright ground, where a very dark blue reads
# as the shadow side of the same glow.
SKIRT = (10, 14, 26)
SKIRT_ALPHA = 58        # at its strongest, just outside the glow


def head():
    """One round torpedo head: a white core, a glow, and a dark skirt.

    The alpha is computed per pixel from the distance to the centre rather
    than stamped from a table, because the only thing that matters here is
    that the ramp is smooth -- a banded glow reads as a sprite, and a sprite
    is exactly what this must not look like.

    **The skirt is why this is not simply a glow.** A bright sprite has
    contrast against dark ground and almost none against light, and the first
    version of this file proved it: rendered over grass, tarmac, a pale roof
    and night (see sheet()), the torpedo was unmissable on three of them and
    nearly gone on the roof -- which is a surface it crosses constantly, since
    a shuttle fires from above the buildings.

    So the glow fades out through a dark ring instead of to nothing. On dark
    ground it is invisible, because dark on dark is nothing; on a pale roof it
    is the separation that makes the bright core read. This is the same trick
    the UI uses when it drops a shadow behind white text, and the reason it is
    baked into the sprite rather than drawn separately is that the tint applied
    at draw time *multiplies* -- a dark pixel stays dark whatever colour the
    game asks for.
    """
    img = Image(S, S)
    for y in range(S):
        for x in range(S):
            dx, dy = x - CX, y - CY
            d = (dx * dx + dy * dy) ** 0.5
            if d >= HALO:
                continue

            if d <= CORE:
                # The core is pure white; the tint does the colouring.
                img.set(x, y, (255, 255, 255, 255))
                continue

            if d <= GLOW:
                t = 1.0 - (d - CORE) / (GLOW - CORE)
                a = int(round(255 * (t ** FALLOFF)))
                # The glow keeps a touch more blue than red, so an untinted
                # draw still reads as plasma rather than as a headlamp.
                f = (d - CORE) / (GLOW - CORE)
                r = int(round(255 - 70 * f))
                g = int(round(255 - 30 * f))
                # Cross-fade into the skirt over the outer third of the glow,
                # so there is no hard edge where one becomes the other.
                if f > 0.78:
                    k = (f - 0.78) / 0.22
                    r = int(round(r + (SKIRT[0] - r) * k))
                    g = int(round(g + (SKIRT[1] - g) * k))
                    b = int(round(255 + (SKIRT[2] - 255) * k))
                    a = int(round(a + (SKIRT_ALPHA - a) * k))
                else:
                    b = 255
                if a > 0:
                    img.set(x, y, (r, g, b, a))
                continue

            # The skirt proper: fades from SKIRT_ALPHA to nothing.
            t = 1.0 - (d - GLOW) / (HALO - GLOW)
            a = int(round(SKIRT_ALPHA * (t ** 1.5)))
            if a > 0:
                img.set(x, y, (SKIRT[0], SKIRT[1], SKIRT[2], a))
    return img


# The trail, exactly as TREK_Torpedo.lua draws it: C.TorpedoTrail echoes
# behind the head, each at f = 1 - e/(trail+1) of full size with alpha f*f.
# Duplicated here rather than imported because the Lua is the thing that runs
# and this is the thing that judges it -- if they drift, the sheet is wrong and
# that is worth seeing. Keep them in step by hand.
TRAIL = 6


def blend(dst, x, y, src):
    """Alpha-composites one pixel of the sprite onto the sheet."""
    r, g, b, a = src
    if a <= 0:
        return
    dr, dg, db, _ = dst.get(x, y)
    t = a / 255.0
    dst.set(x, y, (int(dr + (r - dr) * t),
                   int(dg + (g - dg) * t),
                   int(db + (b - db) * t), 255))


def stamp(dst, img, cx, cy, scale, alpha, tint):
    """Draws the head at a size and opacity, tinted the way the game tints it.

    Nearest-neighbour, because this is judging whether the thing reads at
    twenty pixels over clutter, not producing a beauty render -- and the game's
    own scaling is the engine's, which this cannot reproduce anyway.
    """
    n = max(1, int(round(S * scale)))
    for py in range(n):
        for px in range(n):
            sx = min(S - 1, int(px / n * S))
            sy = min(S - 1, int(py / n * S))
            r, g, b, a = img.get(sx, sy)
            if a <= 0:
                continue
            x, y = cx - n // 2 + px, cy - n // 2 + py
            if 0 <= x < dst.w and 0 <= y < dst.h:
                blend(dst, x, y, (int(r * tint[0]), int(g * tint[1]),
                                  int(b * tint[2]), int(a * alpha)))


def sheet(img):
    """The torpedo in flight, over every background it has to read against.

    **This is the vet, and it is the point of the file.** A glow cannot be
    judged on transparency -- it is nothing but a soft edge, so it looks fine
    alone and can vanish completely over the wrong ground. The four strips are
    grass, tarmac, a pale roof and night, which is most of what a torpedo
    crosses, and each shows the full head-and-trail at the tint and the sizes
    TREK_Torpedo.lua actually draws.

    Same discipline as tools/vet_icons.py: render it against the real thing at
    the real size, and look at it.
    """
    TINT = (0.70, 0.88, 1.00)      # FLIGHT_TINT in TREK_Torpedo.lua
    BANDS = [
        ("grass", (86, 110, 60)),
        ("road", (92, 92, 98)),
        ("roof", (158, 146, 132)),
        ("night", (18, 22, 38)),
    ]
    # Two zoom levels, because size is divided by getCore():getZoom() in game
    # and a torpedo that reads close up can be a smudge zoomed out.
    ZOOMS = (1.0, 2.0)

    pad, step = 14, 26
    w = pad * 2 + step * (TRAIL + 1) + 60
    bandH = 44
    h = len(BANDS) * len(ZOOMS) * bandH

    out = Image(w, h)
    row = 0
    for name, bg in BANDS:
        for z in ZOOMS:
            y0 = row * bandH
            out.rect(0, y0, w - 1, y0 + bandH - 1, (bg[0], bg[1], bg[2], 255))
            cy = y0 + bandH // 2
            # Drawn tail-first so the brightest is on top, as in the overlay.
            for e in range(TRAIL, -1, -1):
                f = 1 - (e / (TRAIL + 1))
                cx = pad + (TRAIL - e) * step
                stamp(out, img, cx, cy, f / z, f * f, TINT)
            row += 1
    return out


def show(img):
    """An ASCII view of the alpha ramp, printed on every run.

    The same habit as gen_reticle.py's: four of this project's asset bugs were
    invisible in the source and obvious in one render. A glow whose core has
    vanished or whose falloff has banded shows up here immediately.
    """
    ramp = " .:-=+*#%@"
    rows = []
    for y in range(0, S, 2):
        line = ""
        for x in range(S):
            a = img.get(x, y)[3]
            line += ramp[min(len(ramp) - 1, a * len(ramp) // 256)]
        rows.append(line.rstrip())
    return "\n".join(rows)


def main(root):
    out = os.path.join(root, "media", "ui")
    os.makedirs(out, exist_ok=True)
    path = os.path.join(out, "TREK_TorpedoFlight.png")
    img = head()
    img.save(path)
    print("wrote", path)
    print(show(img))

    # The contact sheet the sprite was judged on lives in design/, beside the
    # bat'leth's mesh previews and the drinks' vetting sheets. design/ is
    # neither deployed nor packaged, so it costs the Workshop build nothing,
    # and re-judging this later needs the picture rather than the numbers.
    # DEV_GUIDE.md, "Source art lives in design/art/".
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    art = os.path.join(here, "design", "art", "ui")
    os.makedirs(art, exist_ok=True)
    vet = os.path.join(art, "torpedo_flight_sheet.png")
    sheet(img).save(vet)
    print("wrote", vet, "-- grass / road / roof / night, at two zooms. Look at it.")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "TrekShuttle/42")
