"""The photon torpedo targeting reticle.

    python tools/gen_reticle.py TrekShuttle/42

Drawn rather than generated by an image model, for the reason
gen_radial_icons.py gives about the radial set: this is thin chrome read at
about 40 pixels over a moving, cluttered world, and nothing survives that but
hard edges. An image model paints soft ones and cannot emit alpha, and the
whole point of a reticle is that it is mostly hole.

**It is drawn pure white on purpose.** TREK_Torpedo.lua tints it at draw time
-- green when the tubes are loaded and the target is in range, gold while they
cycle, red when it is out of range -- and a tint multiplies. Any colour baked
in here would fight the one the state is trying to say. The same reason
vanilla's own UI chrome is white.

The shape is four corner brackets around a gap, not a cross: a cross covers
the thing being aimed at, and the thing being aimed at is a zombie the pilot
needs to see. LCARS corners are square-cut rather than mitred, which is also
what makes it read as this mod's furniture rather than a generic FPS crosshair.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngwrite import Image

S = 40                  # a touch under a tile at default zoom
WHITE = (255, 255, 255, 255)
SOFT = (255, 255, 255, 140)

ARM = 11                # how far a bracket runs along each edge
THICK = 3               # bracket weight
INSET = 2               # from the frame edge


def span(a, b):
    """Normalised [lo, hi) for a rect edge, whichever way it was measured.

    Written out because the first draft passed `cx + dx * THICK` straight to
    rect() with dx negative, which gives a right edge left of its left edge:
    two of the four corners simply did not draw, and the printout is the only
    thing that showed it.
    """
    lo, hi = sorted((a, b))
    return lo, hi + 1


def bracket(img, cx, cy, dx, dy):
    """One corner: two square-cut arms meeting at (cx, cy), running inward."""
    x0, x1 = span(cx, cx + dx * ARM)          # horizontal arm
    y0, y1 = span(cy, cy + dy * (THICK - 1))
    img.rect(x0, y0, x1, y1, WHITE)
    x0, x1 = span(cx, cx + dx * (THICK - 1))  # vertical arm
    y0, y1 = span(cy, cy + dy * ARM)
    img.rect(x0, y0, x1, y1, WHITE)


def reticle():
    img = Image(S, S)
    lo, hi = INSET, S - INSET - 1
    bracket(img, lo, lo, 1, 1)
    bracket(img, hi, lo, -1, 1)
    bracket(img, lo, hi, 1, -1)
    bracket(img, hi, hi, -1, -1)
    # A single centre pip, faint: enough to say exactly which square without
    # hiding what is standing on it.
    c = S // 2
    img.rect(c - 1, c - 1, c + 1, c + 1, SOFT)
    return img


def show():
    img = reticle()
    rows = []
    for y in range(0, S, 2):
        line = ""
        for x in range(S):
            a = img.get(x, y)[3]
            line += "#" if a > 200 else ("." if a > 40 else " ")
        rows.append(line.rstrip())
    return "\n".join(rows)


def main(root):
    out = os.path.join(root, "media", "ui")
    os.makedirs(out, exist_ok=True)
    path = os.path.join(out, "TREK_Reticle.png")
    reticle().save(path)
    print("wrote", path)
    print(show())


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "TrekShuttle/42")
