"""Generates the dilithium crystal's inventory icon.

    python tools/gen_dilithium.py TrekShuttle/42

Drawn procedurally rather than generated by an image model, for the reason
gen_phaser.py draws its own: the shape is a faceted gem, which is four
straight lines and a colour ramp, and describing that to an image model is
harder than drawing it. The contact sheet it is judged on goes in
design/art/dilithium/ on every run, so the generator and the vet are one
command (ROADMAP.md, "How art gets made").

**It has to read at 32x32**, which is what the inventory actually draws, and
that decides everything about it: one big silhouette, three flat facets, and
a colour nothing else in this mod uses. The ship's own gear is Starfleet
off-white and LCARS orange; the galley food is brown and green. A violet
crystal with a cyan edge is unmistakable in a loot window at a glance, which
matters for an item the whole power system now depends on finding.
"""
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngwrite import Image

SIZE = 64

# The crystal, as a vertical bipyramid: a point at the top, shoulders a third
# of the way down, and a longer taper to the bottom point. That asymmetry is
# what stops it reading as a diamond playing-card pip.
TOP_Y, SHOULDER_Y, BOTTOM_Y = 9, 25, 57
HALF = 17

CORE       = (214, 150, 255, 255)   # the lit middle facet
LEFT       = (118, 66, 176, 255)    # in shadow
RIGHT      = (166, 104, 220, 255)
EDGE       = (232, 214, 255, 255)   # the ridge down the middle
RIM        = (96, 226, 255, 255)    # a cyan rim, so it is not just purple
DEEP       = (58, 28, 96, 255)
SPARK      = (255, 255, 255, 255)
HALO_RGB   = (150, 90, 235)


def half_width(y):
    """How wide the crystal is at this row."""
    if y < TOP_Y or y > BOTTOM_Y:
        return 0.0
    if y <= SHOULDER_Y:
        return HALF * (y - TOP_Y) / float(SHOULDER_Y - TOP_Y)
    return HALF * (BOTTOM_Y - y) / float(BOTTOM_Y - SHOULDER_Y)


def halo(img):
    """A soft glow behind it.

    pngwrite does not blend, so this goes down first and the crystal is drawn
    straight over the middle of it -- the same trick gen_phaser.py uses for
    the emitter.
    """
    cx, cy = SIZE / 2.0, (SHOULDER_Y + BOTTOM_Y) / 2.0
    rx, ry = HALF + 11, (BOTTOM_Y - TOP_Y) / 2.0 + 9
    for y in range(SIZE):
        for x in range(SIZE):
            d = math.hypot((x - cx) / rx, (y - cy) / ry)
            if d >= 1.0:
                continue
            a = int(120 * (1.0 - d) ** 2.2)
            if a > 0:
                img.set(x, y, HALO_RGB + (a,))


def crystal(img):
    cx = SIZE / 2.0
    for y in range(TOP_Y, BOTTOM_Y + 1):
        w = half_width(y)
        if w < 0.5:
            continue
        x0, x1 = int(round(cx - w)), int(round(cx + w))

        # Three facets: the middle one catches the light, the left is in
        # shadow, the right is between the two. Flat colours on purpose --
        # a gradient across eight pixels is mud at icon size.
        third = max(1, int(round(w * 2 / 3.0)))
        img.rect(x0, y, x1, y + 1, RIGHT)
        img.rect(x0, y, x0 + third, y + 1, LEFT)
        img.rect(int(round(cx - third * 0.45)), y,
                 int(round(cx + third * 0.45)), y + 1, CORE)

        # the ridge, and the rim the silhouette is read by
        img.rect(int(round(cx - 1)), y, int(round(cx + 1)), y + 1, EDGE)
        img.set(x0, y, RIM)
        img.set(x1 - 1, y, RIM)
        if y in (TOP_Y, BOTTOM_Y):
            img.rect(x0, y, x1, y + 1, EDGE)

    # A dark seam under the shoulders, so the two halves of the gem read as
    # separate faces rather than one long lozenge.
    w = half_width(SHOULDER_Y)
    img.rect(int(round(cx - w)), SHOULDER_Y, int(round(cx + w)), SHOULDER_Y + 1, DEEP)
    img.rect(int(round(cx - 1)), SHOULDER_Y, int(round(cx + 1)), SHOULDER_Y + 1, EDGE)

    # two sparks, which is what makes it read as *lit* rather than painted
    img.rect(int(cx) - 6, SHOULDER_Y - 7, int(cx) - 3, SHOULDER_Y - 4, SPARK)
    img.set(int(cx) + 5, SHOULDER_Y + 9, SPARK)


def build(path):
    img = Image(SIZE, SIZE, (0, 0, 0, 0))
    halo(img)
    crystal(img)
    img.save(path)
    print(f"  {os.path.basename(path)}  {SIZE}x{SIZE}")


if __name__ == "__main__":
    root = sys.argv[1] if len(sys.argv) > 1 else "TrekShuttle/42"
    out = os.path.join(root, "media", "textures", "Item_TREK_Dilithium.png")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    build(out)

    # The sheet it is judged on, at the size the inventory draws it.
    art = os.path.join("design", "art", "dilithium")
    os.makedirs(art, exist_ok=True)
    sheet = os.path.join(art, "dilithium_sheet.png")
    import subprocess
    tool = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vet_icons.py")
    subprocess.run([sys.executable, tool, sheet, "Dilithium"], check=False)
    print("dilithium icon written")
