"""Radial-menu icons for the shuttle: go aboard, climb, dive, set down.

Drawn rather than generated by an image model, because these are read at about
48 pixels inside a dark ring and nothing survives that but a big flat
silhouette and one unmistakable arrow. The vanilla vehicle icons they sit
beside (media/ui/vehicles/vehicle_*.png) are the same idea: one white shape on
nothing.

    python tools/gen_radial_icons.py TrekShuttle/42

Every icon is the same 48x48 canvas with the same shuttle shape, so the four
read as a set and differ only in the part that matters -- which way she is
going. The LCARS palette from the helm is reused so they belong to the mod
rather than to the car menu.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pngwrite import Image

S = 48

WHITE = (255, 255, 255, 255)
GOLD = (255, 204, 102, 255)      # LCARS gold: climbing
BLUE = (153, 204, 255, 255)      # LCARS blue: descending
PEACH = (255, 204, 153, 255)     # the cabin
GREY = (170, 180, 200, 255)      # the ground line


CX = S // 2


def shuttle(img, cy, colour):
    """A small shuttle seen from behind: a wedge hull and two nacelles."""
    for i in range(5):
        half = 4 + i
        img.rect(CX - half, cy + i, CX + half, cy + i + 1, colour)
    img.rect(CX - 13, cy + 3, CX - 8, cy + 6, colour)
    img.rect(CX + 8, cy + 3, CX + 13, cy + 6, colour)


def arrow(img, apex_y, direction, colour):
    """A solid arrow. `direction` is -1 for pointing up, +1 for down.

    The apex is where it points. Getting that backwards is easy and invisible
    in the source -- the first draft of this drew the ascend icon as a
    downward triangle -- so the shapes are rendered and looked at
    (tools/gen_radial_icons.py prints them; see DEV_GUIDE.md on vetting art at
    the size it is shown).
    """
    # The head grows *away* from the apex, which is the opposite way to the one
    # it points. Conflating the two is what drew the first ascend icon as a
    # downward triangle.
    grow = -direction
    head = 11
    for i in range(head):
        y = apex_y + grow * i
        img.rect(CX - i - 1, y, CX + i + 1, y + 1, colour)
    base = apex_y + grow * head
    shaft = 12
    y0, y1 = sorted((base, base + grow * shaft))
    img.rect(CX - 4, y0, CX + 4, y1, colour)


def ground(img, y, colour):
    img.rect(5, y, S - 5, y + 3, colour)


def ascend():
    """Take her up / climb: an arrow up, the ship below it."""
    img = Image(S, S)
    arrow(img, 3, -1, GOLD)
    shuttle(img, 36, WHITE)
    return img


def descend():
    """Dive: the ship above, an arrow down."""
    img = Image(S, S)
    shuttle(img, 3, WHITE)
    arrow(img, S - 4, 1, BLUE)
    return img


def land():
    """Set her down: the same, onto ground."""
    img = Image(S, S)
    shuttle(img, 1, WHITE)
    arrow(img, S - 10, 1, BLUE)
    ground(img, S - 7, GREY)
    return img


def aboard():
    """Going aft to the cabin: a hatch with an arrow into it."""
    img = Image(S, S)
    # the hull, seen side on, with a doorway cut out of it
    img.rect(8, 10, S - 8, S - 10, PEACH)
    img.rect(12, 14, S - 12, S - 14, (0, 0, 0, 0))
    img.rect(S - 16, 18, S - 8, S - 18, PEACH)
    # an arrow pointing in
    img.rect(10, S // 2 - 2, 26, S // 2 + 2, WHITE)
    for i in range(7):
        img.rect(26 + i, S // 2 - 7 + i, 27 + i, S // 2 + 7 - i, WHITE)
    return img


ICONS = {
    "TREK_Ascend": ascend,
    "TREK_Descend": descend,
    "TREK_Land": land,
    "TREK_Aboard": aboard,
}


def main(root):
    out = os.path.join(root, "media", "ui")
    os.makedirs(out, exist_ok=True)
    for name, make in sorted(ICONS.items()):
        path = os.path.join(out, name + ".png")
        make().save(path)
        print("wrote", path)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "TrekShuttle/42")


def show(name):
    """Prints an icon as text, because a shape that is wrong is invisible in
    the source and obvious the moment you look at it."""
    rows = []
    img = ICONS[name]()
    for y in range(0, S, 2):
        line = ""
        for x in range(S):
            r, g, b, a = img.get(x, y)
            if a < 40:
                line += " "
            elif r > 230 and g > 230 and b > 230:
                line += "#"
            elif b > 200:
                line += "*"
            elif r > 200:
                line += "o"
            else:
                line += "+"
        rows.append(line.rstrip())
    return "\n".join(rows)
